<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>

<hr>

<a href="https://lms.clarusway.com/mod/lesson/view.php?id=2463&pageid=4531&startlastseen=no"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/2-DAwPY/DAwPy_S01_(Numpy_Arrays).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="90" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DAwPy_S1_%28Numpy_Arrays%29/DAwPy_S1_%28Numpy_Arrays%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="100" height="100" title="Open and Execute in nbviewer"></a><br/>

<hr>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="500" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="text-align: center;"><img src="https://i.ibb.co/XS0bxSH/best-bootcamps.png" width="300" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY_Courses"></p>

<img src=https://i.ibb.co/6gCsHd6/1200px-Pandas-logo-svg.png width="600" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Session - 11 (Part - 01)</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#E51A59; font-size:200%; text-align:center; border-radius:10px 10px;">RegEx in Python</p>

<img src=https://i.ibb.co/3YHkK1K/regex1.jpg width="800" height="200">

[Image Credit](https://medium.com/@rayykim/understanding-regex-101-204853651755)

Regular expressions (Regex or RegExp) are extremely useful in stepping up your algorithm game and will make you a better problem solver. The structure of regular expressions can be intimidating at first, but it is very rewarding once you grasp the patterns and implement them in your work properly.

<a id="toc"></a>

## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [IMPORTING LIBRARIES NEEDED IN THIS NOTEBOOK](#0)
* [RegEx in PYTHON](#1)
* [RAW STRING ("r/ R")](#2)
* [COMMON PYTHON RegEx FUNCTIONS](#3)    
* [PANDAS FUNCTIONS ACCEPTING RegEx](#4)    
* [THE END OF THE SESSION - 07](#5)

## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Importing Libraries Needed in This Notebook</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Once you've installed NumPy & Pandas you can import them as a library:

In [ ]:
import pandas as pd              # DAwPy
import numpy as np               # DAwPy
import seaborn as sns            # Stats-1 & DAwPy
import matplotlib.pyplot as plt  # Stats-1 & DAwPy

# The "re" module provides support for regular expressions in Python.
import re

# import warnings
# warnings.filterwarnings("ignore")  # to suppress all warnings

- **``Importing Libraries``**: Make sure to import the required libraries before beginning your. You need both pandas and numpy.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

- ``import warnings``: This imports the warnings module, which is part of Python's standard library and provides a way to issue warning messages.
- ``warnings.filterwarnings("ignore")``: This function call tells Python to ignore all warning messages that would normally be printed. This can be useful when we want to focus on the output of your program without being distracted by warnings.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢 Caution ❗❗❗</strong></p>


- Ignoring warnings can sometimes hide important issues in our code, so use this approach judiciously. It's generally better to address the underlying causes of warnings rather than suppressing them.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">RegEx in Python</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

- A **Reg**ular **Ex**pression (RegEx) is a special sequence of characters that helps you match or find other strings or sets of strings, using a specialized syntax held in a pattern.

- The **Python module** **``re``** provides full support for regular expressions in Python [Source 01](https://docs.python.org/3/library/re.html#re-objects), [Source 02](https://www.tutorialspoint.com/python/python_reg_expressions.htm) & [Source 03](https://www.w3schools.com/python/python_regex.asp).

**``Regular Expressions (RegEx)``** in Python are a powerful tool for ``**searching, matching, and manipulating strings``** based on **``specific patterns``**. The **``re module``** provides various functions for tasks such as pattern matching, substitution, and splitting strings. Common operations include using **``re.search()``** to find patterns, **``re.match()``** for checking if a string starts with a pattern, and **``re.sub()``** for replacing occurrences of a pattern. RegEx is widely used in data validation, text processing, and web scraping, making it an essential skill for programmers working with text data.


### Common Expressions

- **``\d``** Any numeric digit from ``0`` to ``9``.
- **``\D``** Matches any character which is not a decimal digit. This is the opposite of ``\d``.
- **``\w``** Any letter, numeric digit, or the underscore character. (Think of this as matching "word" characters.)
- **``\W``** Any character that is not a letter, numeric digit, or the underscore character.
- **``\s``** Any space, tab, or newline character. (Think of this as matching white-space characters.)
- **``\S``** Any character that is not a space, tab, or newline.


### Common Metacharacters

- **``"[]"``**	  A set of characters	``"[a-m]"``
- **``"\"``**	      Signals a special sequence (can also be used to escape special characters)
- **``"."``**	      Any character (except newline character)
- **``"^"``**	      Starts with	``"^hello"``
- **``"$"``**	      Ends with	``"world$"``
- **``"*"``**	      Match zero, one or more of the previous
- **``"+"``**	      Match one or more of the previous
- **``"?"``**	      Match zero or one of the previous
- **``"{}"``**	  Match exactly the specified number of occurrences
- **``"|"``**	      Either or	`"falls|stays"`
- **``"()"``**	  Capture and group

## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Raw String ("r / R")</p>

<a id="2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In Python, a **``raw string``** is created by **``prefixing``** a string literal with **``r``** or **``R``**, which tells the **``interpreter to treat backslashes (\)``** as **``literal characters rather than escape characters``**. This is particularly useful in regular expressions and file paths, where backslashes are common. 
- For example, **``r"C:\new_folder"``** will be **``interpreted as a string``** with the **``exact characters``** C:\new_folder, while **``"C:\\new_folder"``** requires **``double backslashes``** to achieve the **``same result``**. Using raw strings simplifies the writing and readability of complex patterns or paths.

<hr>

- Python raw string is created by prefixing a string literal with **'r' or 'R'**.
- Python raw string treats **``backslash (\)``** as a literal character. This is useful when we want to have a string that contains backslash and don’t want it to be treated as an escape character [Source 01](https://blog.devgenius.io/beauty-of-raw-strings-in-python-fa627d674cbf) & [Source 02](https://stackoverflow.com/questions/26318287/what-does-r-mean-before-a-regex-pattern#:~:text=The%20r%20means%20that%20the,escape%20codes%20will%20be%20ignored.).



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>Raw String ("r / R"):</strong></p>


**The following code snippet demonstrates how to print escape sequences in Python**

In [122]:
print("Backslash: \\")
print("New line char: \\n")

Backslash: \
New line char: \n


- **``print("Backslash: \\"):``**
  - This line prints the text Backslash: \. The double backslash (\\) is used to represent a single backslash in the output.
- **``print("New line char: \\n"):``**
  - This line prints New line char: \n. Again, the double backslash is used to display the escape sequence for a new line (i.e., \n) as literal text, rather than interpreting it as a new line.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code snippet uses raw strings in Python, which treat backslashes (\) as literal characters.**

In [124]:
print(r"Backslash: \\")
print(R"New line char: \\n")

Backslash: \\
New line char: \\n


- **``print(r"Backslash: \\"):``**
  - This line prints Backslash: \\. The r prefix indicates that it is a raw string, so the double backslash is interpreted as two literal backslashes.
- **``print(r"New line char: \\n"):``**
  - This line prints New line char: \\n. Similarly, the raw string preserves the backslash and the n, displaying them as literal characters rather than interpreting \n as a newline.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code snippet creates a string with a newline character and then prints it.**

In [125]:
my_string = "Hello\nWorld"
print(my_string)

Hello
World


- **``my_string = "Hello\nWorld":``**
  - This line initializes a variable my_string with the value Hello\nWorld.
  - The \n is an escape sequence that represents a newline character, so when the string is printed, it will break onto a new line.
- **``print(my_string):``**
  - This line outputs the value of my_string to the console.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code snippet uses a raw string to include a backslash and the letter "n" literally.**

In [126]:
my_string = r"Hello\nWorld"
print(my_string)

Hello\nWorld


- **``my_string = r"Hello\nWorld":``**
  - This line initializes a variable my_string with the value Hello\nWorld.
  - The r prefix denotes a raw string, which means that backslashes are treated as literal characters. Therefore, \n is interpreted as the characters \ and n, rather than as a newline character.
- **``print(my_string):``**
  - This line outputs the value of my_string to the console.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>Invalid Raw String:</strong></p>


An **``invalid raw string``** in Python **``occurs when a raw string literal ends with an odd number of backslashes``**. This is because a **``single backslash at the end``** of the string would **``escape the closing quote``**, leading to a **``syntax error``**.
- For example, r"Hello\" is invalid, while r"Hello\\" is valid, as it properly represents two literal backslashes. To avoid such errors, ensure that raw strings do not end with an unpaired backslash.



In [127]:
# print("\") # gives an error

SyntaxError: unterminated string literal (detected at line 1) (443930442.py, line 1)

The statement **``print("\")``** will indeed result in a **``syntax error``** in Python. This happens because the **``backslash (\) is an escape character``**, and Python expects a following character to determine how to interpret it. **``Since there’s NO character after the backslash, Python raises an error``**.



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [128]:
# print(r"\") # gives an error

SyntaxError: unterminated string literal (detected at line 1) (835173915.py, line 1)

The statement **``print(r"\")``** will raise a **``syntax error``** in Python because a **``raw string literal CANNOT end with an unescaped backslash``**. In a raw string, the backslash is treated as a literal character, and **``if it's the last character, there’s NO closing quote for the string``**.

**``Why the Error Occurs?``**
- **``Raw Strings``**: In a raw string (indicated by the prefix r or R), backslashes are treated as literal characters. This means that they do not escape the following characters.
- **``Ending with a Backslash``**: When you write r"\\", it is valid because it represents two literal backslashes. However, r"\\" is invalid because the single backslash at the end does not escape anything, leading to a syntax error.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [129]:
# print(r"abc\") # gives an error

SyntaxError: unterminated string literal (detected at line 1) (2660593944.py, line 1)

The statement **``print(r"abc\")``** will indeed raise a **``syntax error``** in Python because a **``raw string CANNOT end with an unescaped backslash``**. Here’s a detailed explanation of why this occurs:

**``Explanation of the Error:``**
- **``Raw Strings``**: In Python, when you prefix a string with r or R, it tells the interpreter to treat backslashes as literal characters. This means escape sequences are not processed.
- **``Ending with a Backslash``**: When you write r"abc\", the string ends with a single backslash. Since there’s no character following the backslash to escape, Python raises a syntax error.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [131]:
# print(r"abc\\\)" # gives an error

SyntaxError: incomplete input (3603393088.py, line 1)

The statement **``print(r"abc\\\)")``** will produce a **``syntax error``** because a **``raw string CANNOT end with an unescaped backslash``**. Here’s a breakdown of why this happens:

**``Explanation of the Error:``**
- **``Raw Strings``**: When you prefix a string with r or R, Python treats backslashes as literal characters. This means that escape sequences are not processed in raw strings.
- **``Ending with a Backslash``**: In the case of r"abc\\\)", the string ends with a single backslash followed by a closing parenthesis. The backslash is not followed by a valid character that it could escape, leading to a syntax error.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following statement is a ``valid use of a raw string`` in Python.**

In [130]:
print(r"abc\\")

abc\\


- **``Raw String``**: The r prefix indicates that this is a raw string. In raw strings, backslashes are treated as literal characters and do not escape the following characters.
- **``String Content``**: The string abc\\ contains the characters abc followed by two backslashes. Since each backslash is treated literally, both backslashes are preserved in the output.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Common Python RegEx Functions</p>

<a id="3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

- **[re.search()](https://docs.python.org/3/library/re.html):** Scan through string looking for a match to the pattern.
- **[re.match()](https://docs.python.org/3/library/re.html):** Try to apply the pattern at the start of the string.
- **[re.fullmatch()](https://docs.python.org/3/library/re.html):** Try to apply the pattern to all of the string.
- **[re.findall()](https://docs.python.org/3/library/re.html):** Return a list of all non-overlapping matches in the string.
- **[re.sub()](https://docs.python.org/3/library/re.html):** Return the string obtained by replacing the leftmost non-overlapping occurrences of the pattern in string by the replacement repl.
- **[re.split()](https://docs.python.org/3/library/re.html):** Split the source string by the occurrences of the pattern, returning a list containing the resulting substrings.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


The **``dir(re)``** function in Python is used to **``list all the attributes and methods available in the re module``**, which provides support for regular expressions. This includes functions, constants, and classes defined in the module.

In [134]:
dir(re) # shows all functions/methods in re module

['A',
 'ASCII',
 'DEBUG',
 'DOTALL',
 'I',
 'IGNORECASE',
 'L',
 'LOCALE',
 'M',
 'MULTILINE',
 'Match',
 'NOFLAG',
 'Pattern',
 'RegexFlag',
 'S',
 'Scanner',
 'T',
 'TEMPLATE',
 'U',
 'UNICODE',
 'VERBOSE',
 'X',
 '_MAXCACHE',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_cache',
 '_casefix',
 '_compile',
 '_compile_repl',
 '_compiler',
 '_constants',
 '_expand',
 '_parser',
 '_pickle',
 '_special_chars_map',
 '_subx',
 'compile',
 'copyreg',
 'enum',
 'error',
 'escape',
 'findall',
 'finditer',
 'fullmatch',
 'functools',
 'match',
 'purge',
 'search',
 'split',
 'sub',
 'subn',
 'template']

In [ ]:
# We can see docstring of related method with help function

# method = re.match
# help(method)

## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>re.search(pattern, string, flags=0)</strong></p>

**🧐 [re.search()](https://docs.python.org/3/library/re.html)** scans through string looking for a match to the pattern, returning a Match object, or None if no match was found **🧐 [Source](https://www.pythontutorial.net/python-regex/python-regex-flags/)**. In other words Python regex **``re.search()``** method looks for occurrences of the regex pattern inside the entire target string and returns the corresponding Match Object instance where the match found. The **``re.search()``** returns only **the first match** to the pattern from the target string **🧐 [Source](https://pynative.com/python-regex-search/)**.



#### Find numeric digits with search function

In [135]:
# Define a text including letters and numbers

text = "A78L41K"



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``searchs for the substring "78" within the string`` stored in the variable text (which is "A78L41K").**

In [136]:
re.search("78", text)


# text = "A78L41K"
# match = re.search("78", text)

# if match:
#     print("Match found:", match.group())  # Output: Match found: 78
#     print("Match starts at index:", match.start())  # Output: Match starts at index: 1
# else:
#     print("No match found.")

<re.Match object; span=(1, 3), match='78'>

The output <re.Match object; span=(1, 3), match='78'> indicates that the re.search("78", text) function found a match for the substring "78" in the string stored in text (which is "A78L41K"). Here’s a breakdown of what each part of this output means:

- **``<re.Match object>``**: This indicates that a match object was created as a result of the search. A match object contains information about the match.
- **``span=(1, 3)``**:
  - The span attribute provides the start and end positions of the match in the original string.
    - In this case, 1 is the starting index and 3 is the ending index (exclusive). This means that the substring "78" starts at index 1 and ends just before index 3.
- **``match='78'``**: This shows the actual substring that was matched in the original text. In this case, it confirms that the matched substring is "78".

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

#### With regular expressions:

**The following expression ``searches for a pattern`` that consists of ``two consecutive digits`` within the string stored in the variable text (which is "A78L41K").**

In [137]:
re.search("\d\d", text)

<re.Match object; span=(1, 3), match='78'>



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

#### with compile() method

**The following statement ``creates a compiled regular expression object`` in Python.**

In [ ]:
# Create a compiled pattern to search in the text

comp = re.compile("\d\d")  # Using a raw string

**``re.compile(pattern):``**
- This function compiles a regular expression pattern into a regular expression object, which can then be used for matching using methods like **``search()``**, **``match()``**, and **``findall()``**.
- Compiling a pattern can improve performance if we plan to use the **``same pattern multiple times``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following method ``searches for a pattern in the string text using a compiled regular expression object``, comp.**

In [138]:
# Use the compiled pattern to search in the text

comp.search(text)

<re.Match object; span=(1, 3), match='78'>



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following statement is ``storing the result of the search operation in the variable num``.**

In [139]:
# Assign the search operation into num variable
num = comp.search(text)

# Display the search operation
num

<re.Match object; span=(1, 3), match='78'>

- If a match is found, num will be a match object, and you can access its properties (like the matched string and its position) using methods like group(), start(), and end().
- If no match is found, num will be None.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following method ``retrieves the starting index of the match`` found by the regular expression search.**

In [140]:
# Check the starting index of the matched substring

num.start()

1

- The start() method returns the starting index of the matched substring in the original string.
  - If a match is found, calling num.start() will give you the index where the match begins.
  - If num is None (i.e., no match was found), calling num.start() will result in an AttributeError.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following method ``retrieves the ending index of the match`` found by the regular expression search.**

In [141]:
# Check the ending index of the matched substring

num.end()

3

- The end() method returns the ending index (exclusive) of the matched substring in the original string.
  - If a match is found, calling num.end() will provide the index just after the last character of the matched substring.
  - If num is None (i.e., no match was found), calling num.end() will raise an AttributeError.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following method ``retrieves a tuple containing the start and end indices of the match`` found by the regular expression search.**

In [142]:
# Check the starting and ending indices of the matched substring

num.span()

(1, 3)

- The span() method returns a tuple (start, end), where:
  - start is the index of the first character of the matched substring.
  - end is the index just after the last character of the matched substring (exclusive).
- If a match is found, calling num.span() gives you both indices in one call.
- If num is None (i.e., no match was found), calling num.span() will raise an AttributeError.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following method ``retrieves the actual matched substring`` from the match object.**

In [146]:
num.group()

'78'

- The group() method returns the substring that was matched by the regular expression.
- By default, calling num.group() without any arguments returns the entire match.
- We can also pass an argument (e.g., group(1)) to retrieve specific groups if your regular expression contains capturing groups (defined with parentheses).

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**When you execute print(num.group()) in the context of our previous regular expression search, it will ``print the actual substring`` that was matched by the regular expression.**

In [147]:
# Display the matched substring directly

print(num.group())

78




<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



#### Find non decimal digits with search function

In [148]:
# Define a text including numbers and letters

text = "8PM19MIN"



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``searches for the first non-digit character`` in the string text, which is "8PM19MIN".**

In [149]:
# Search for the first non-digit character
nondeci = re.search("\D", text)

# Display the matched substring
nondeci.group()

'P'

- **``Pattern "\D"``**: In regular expressions, \D is a metacharacter that matches any character that is not a digit (0-9).
re.search(pattern, string):
  - This function searches the string for the first occurrence of the specified pattern (\D in this case).
  - It returns a match object if a match is found or None if no match is found.
- **``nondeci.group()``**: The group() method of the match object returns the matched substring.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``searches for the first occurrence of two consecutive non-digit characters`` in the string text, which is "8PM19MIN".**

In [152]:
# Search for the first two consecutive non-digit characters
nondeci = re.search("\D\D", text)

# Display the matched substring
nondeci.group()

'PM'



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``searches for one or more consecutive non-digit characters in the string text``, which is "8PM19MIN".**

In [153]:
# Search for the one or more consecutive non-digit characters
nondeci = re.search("\D+", text)

# Display the matched substring
nondeci.group()

'PM'



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



#### Find phone number pattern

In [154]:
# Define a text including a pattern of phone number

text = 'My phone number is 1234567890'



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``searches for a sequence of exactly ten consecutive digits`` (which represents a phone number) in the string text, which is 'My phone number is 1234567890'.**

In [155]:
# Search for a sequence of ten digits
telno = re.search("\d\d\d\d\d\d\d\d\d\d",text)

# Display the matched substring
telno.group()

'1234567890'



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``searches for a sequence of exactly ten consecutive digits in the string text``, which is  'My phone number is 1234567890'.**

In [156]:
# Search for a sequence of ten digits
telno = re.search("\d+", text)

# Display the matched substring
telno.group()

'1234567890'



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [157]:
telno = re.search("\d*",text)

# Display the matched substring
telno.group()

''

The difference in behavior between <b>``re.search("\d+", text)``</b> and <b>``re.search("\d*", text)``</b> is due to how the **``+``** and **``*``** quantifiers work in regular expressions.

- **``+``** **``(One or More):``**
- The **``+``** quantifier matches **``one or more occurrences``** of the **``preceding element``**.
- In the case of **``"\d+"``**, it will search for a sequence of digits that occurs at least once.
  - Therefore, when we run **``re.search("\d+", text)``**, it successfully finds the sequence "1234567890".
- **``*``** **``(Zero or More):``**
  - The **``*``** quantifier matches **``zero or more occurrences``** of the **``preceding element``**.
  - In the case of <b>``"\d*"``</b>, it will match a sequence of digits or nothing at all.
  - Since the pattern allows for zero occurrences, it will match the position before the first digit in the string, resulting in an empty string as a valid match.
  - When we run <b>``re.search("\d*", text)``</b>, it finds a match at the start of the string (before any digits), which is why telno.group() returns an empty string.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢 Caution ❗❗❗</strong></p>


- **``"\d+"``** requires **``at least one digit to match``**, so it returns the full number.
- <b>``"\d*"``</b> can **``match zero digits``**, so it finds a position where there are NO digits and returns an empty string. This behavior is typical for how regex patterns interpret the presence of characters.


<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [163]:
# Define a text including a pattern of phone number

text = 'My phone number is 123 456 7890'



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``searches for a specific pattern of a phone number formatted with spaces`` in the string text, which is 'My phone number is 123 456 7890'.**

In [165]:
# Search for a pattern of ten digits split by spaces (empty characters)
telno = re.search("\d\d\d \d\d\d \d\d\d\d", text)

# Display the matched substring
telno.group()

'123 456 7890'

- **``Pattern "\d\d\d \d\d\d \d\d\d\d":``**
  - This pattern specifies that you are looking for three digits, followed by a space, three more digits, another space, and then four digits.
  - Specifically, it matches the format XXX XXX XXXX, where X is a digit.
- **``re.search(pattern, string):``**
  - The search() function scans the string to find the first occurrence of the specified pattern.
  - It returns a match object if it finds the pattern; otherwise, it returns None.
- **``telno.group():``**
  - The group() method of the match object returns the matched substring.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [166]:
# Define a text including a pattern of phone number

text = 'My phone number is 123-456-7890'



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``searches for a specific pattern of a phone number formatted with dashes`` in the string text, which is 'My phone number is 123-456-7890'.**

In [167]:
# Search for a pattern of ten digits with dashes
telno = re.search("\d\d\d-\d\d\d-\d\d\d\d",text)

# Display the matched substring
telno.group()

'123-456-7890'

- **``Pattern "\d\d\d-\d\d\d-\d\d\d\d":``**
  - This pattern specifies that you are looking for three digits, followed by a dash, three more digits, another dash, and finally four digits.
  - Specifically, it matches the format XXX-XXX-XXXX.
- **``re.search(pattern, string):``**
  - The search() function scans through the string to find the first occurrence of the specified pattern.
  - Since your string does not contain dashes, the search will return None.
- **``telno.group():``**
  - If a match is found, group() will return the matched substring. If no match is found, calling group() will raise an AttributeError.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression is an attempt to construct a regular expression pattern for a phone number formatted with dashes, but it contains a small mistake in the way the pattern is constructed.**

In [168]:
# Search for a pattern of ten digits with dashes
telno = re.search('\d'*3 + '-' + '\d'*3 + '-' + '\d'*4, text)

# Display the matched substring
telno.group(0)

'123-456-7890'

- **``Pattern Construction:``**
  - <b>``'\d'*3``</b> generates a string that matches three digits (\d\d\d).
  - <b>``'-'``</b> is a literal dash.
  - <b>``'\d'*3``</b> again generates a string that matches three digits (\d\d\d).
  - <b>``'-'``</b> is another literal dash.
  - <b>``'\d'*4``</b> generates a string that matches four digits (\d\d\d\d).

However, using <b>``'\d'*3``</b> will **``NOT create a valid regex pattern``** directly in the way intended. It will result in a string of the form <b>``'\d\d\d-\d\d\d-\d\d\d\d'``</b>, which is **``correct but NOT the most readable``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



#### Find phone number pattern by grouping

**The following expression ``searches for a phone number`` in the ``format XXX-XXX-XXXX within the string text``. The ``parentheses () create capturing groups``, allowing us to extract specific parts of the match.**

In [171]:
# Search for a pattern of ten digits with dashes
telno = re.search("(\d\d\d)-(\d\d\d)-(\d\d\d\d)", text)

# Display the matched substring
telno.group(1) # try 1, 2, 3 for group

'123'

- **``Pattern (\d\d\d)-(\d\d\d)-(\d\d\d\d):``**
  - **``This pattern looks for:``**
    - Three digits followed by a dash (captured in group 1).
    - Three digits followed by another dash (captured in group 2).
    - Four digits (captured in group 3).
  - **``Using re.search():``**
     - This function scans the string for the specified pattern and returns a match object.
  - **``Using telno.group():``**
    - **``telno.group(0)``** returns the entire matched substring. # Output: 123-456-7890
    - **``telno.group(1)``** returns the first captured group (the first three digits).  # Output: 123
    - **``telno.group(2)``** returns the second captured group (the second set of three digits).  # Output: 456
    - **``telno.group(3)``** returns the third captured group (the last four digits).  # Output: 7890

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``searches for a pattern of a phone number formatted with dashes``, where each section can contain zero or more digits due to the * quantifier.**

In [172]:
# Search for a pattern of the phone number with optional digits
telno = re.search("(\d*)-(\d*)-(\d*)", text)

# Display the matched substring
telno.group()

'123-456-7890'

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢 Caution ❗❗❗</strong></p>

- Using <b>``(\d*)``</b> allows for **``flexibility in matching``**, BUT it **``can also lead to empty matches``** if the input does **``NOT contain digits``**. If we want to ensure that there are digits in each part, consider using **``+``** instead of <b>``*``</b>, which **``requires at least one digit in each group``**. 


<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``searches for a phone number formatted as XXX-XXX-XXXX``, where each ``X`` represents a ``digit``.**

In [175]:
# Search for a pattern of the phone number
telno = re.search("(\d+)-(\d+)-(\d+)", text)

# Display the matched substring
telno.group(2)

'456'

- **``Pattern (\d+)-(\d+)-(\d+):``**
  - **``- \d+``** matches **``one or more digits**``. The **``+**`` quantifier ensures that each group must contain **``at least one digit``**.
  - The dashes - are literal characters that separate the groups.
  - **``Using re.search():``**
    - This function searches through the string for the specified pattern and returns a match object if the pattern is found.
- **``Using telno.group():``**
  - **``telno.group(0)``** returns the entire matched substring (the full phone number).
  - **``telno.group(1)``**, **``telno.group(2)``**, and **``telno.group(3)``** return the values of the **``three capturing groups``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



#### Escaping parentheses and create 2 group -> first group:(415) second group:555-1212 print

In [176]:
# Define a text including a pattern of phone number with parentheses and spaces

text = 'My phone number is (415) 555-1212'



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``searches for a phone number`` formatted with ``parentheses`` around the area code and ``spaces`` between the area code and the rest of the number.**

In [177]:
telno = re.search("(\(\d\d\d\)) (\d\d\d-\d\d\d\d)", text)

# Display the matched substrings in each part
print(telno.group(1))
print(telno.group(2))

(415)
555-1212


- **``Pattern (\(\d\d\d\)) (\d\d\d-\d\d\d\d):``**
  - **``\(\d\d\d\)``** matches an area code in parentheses (e.g., (415)).
  - The **``space``** after the parentheses is a **``literal space``**.
  - **``(\d\d\d-\d\d\d\d)``** matches the next part of the phone number, which consists of three digits, a dash, and then four digits (e.g., 555-1212).
- **``Using re.search():``**
  - This function scans the string for the specified pattern and returns a match object if it finds a match.
- Using **``telno.group(1)``** and **``telno.group(2)``**:
  - **``telno.group(1)``** returns the **``first captured group``** (the area code).
  - **``telno.group(2)``** returns the **``second captured group``** (the rest of the phone number).

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>re.match(pattern, string, flags=0)</strong></p>

**🧐 [re.match()](https://docs.python.org/3/library/re.html)** function in Python's re module tries to apply the pattern **at the start of the string**, returning a Match object, or None if no match was found.


- Try to apply the pattern at the start of the string, returning a Match object, or None if no match was found.

- If we want to locate a match anywhere in string, use search() instead of match()

In [178]:
# Define a text including numbers and letters

text = "A78L41K"



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [181]:
# num = re.match("\d\d", text) # gives an error, because match function just look at the begining of string 
# num.group()

AttributeError: 'NoneType' object has no attribute 'group'



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``checks if the string text starts with a non-digit character followed by two digits``.**

In [182]:
# Match a non-digit followed by two digits
alp = re.match("\D\d\d", text)

# Display the matched substring
alp.group()

'A78'

- **``Pattern "\D\d\d":``**
  - **``\D``** matches any character that is not a digit (0-9).
  - **``\d``** matches any digit (0-9).
    - Thus, \D\d\d looks for a non-digit character followed by exactly two digits.
- **``Using re.match():``**
  - This function checks for a match only at the beginning of the string. If the pattern does not start at the beginning, it will return None.
- **``Using alp.group():``**
  - If a match is found, group() returns the matched substring.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>re.fullmatch(pattern, string, flags=0)</strong></p>

**🧐 [re.fullmatch()](https://docs.python.org/3/library/re.html)** method tries to apply the pattern to all of the string. It returns a match object if and **only if the entire string matches the pattern**. Otherwise, it will return None. 
- Try to apply the pattern to all of the string

In [186]:
# Define a text including numbers and letters

text = "A78L41K"



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``checks if the entire string text matches a specific pattern involving word characters (letters, digits, or underscores) and digits``.**

In [187]:
# Full match for the specified pattern
alpnum = re.fullmatch("\D\d+\D\d+\D", text)

# Display the matched substring
alpnum.group()

'A78L41K'

The re.fullmatch() function checks **``if the entire text matches the specified pattern``**. If it does, it returns a match object; otherwise, it returns None.

- **``Pattern "\D\d+\D\d+\D":``**
  - **``\D``** matches any character that is not a digit (0-9).
  - **``\d+``** matches one or more digits.
- **``The pattern looks for:``**
  - A non-digit character.
  - Followed by one or more digits.
  - Followed by another non-digit character.
  - Followed by one or more digits.
  - Followed by a final non-digit character.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``checks if the entire string text matches a specific pattern involving word characters (letters, digits, or underscores) and digits``.**

In [188]:
# Full match for the specified pattern
alpnum = re.fullmatch("\w\d+\w\d+\w", text)

# Display the matched substring
alpnum.group()

'A78L41K'

The **``re.fullmatch()``** function checks **``if the entire text matches the specified pattern``**. If it does, it returns a match object; otherwise, it returns None.


- **``Pattern "\w\d+\w\d+\w":``**
  - **``\w matches any word character, which includes letters (uppercase and lowercase), digits (0-9), and underscores (_).
  - **``\d+ matches one or more digits.
- **``The pattern looks for:``**
  - A word character.
    - Followed by one or more digits.
    - Followed by another word character.
    - Followed by one or more digits.
    - Followed by a final word character.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>re.findall(pattern, string, flags=0)</strong></p>

**🧐 [re.findall()](https://docs.python.org/3/library/re.html)** is **probably the single most powerful function in the re module**. **``re.findall()``** function scans string from left to right, searching for all non-overlapping matches of the pattern in the string. The function returns all the findings as a list. **🧐 [Source-01](https://www.pythontutorial.net/python-regex/python-regex-findall/), [Source-02](https://blog.finxter.com/python-re-findall/), [Source-03](https://pythonexamples.org/python-re-findall/), and [Source-04](https://developers.google.com/edu/python/regular-expressions)**

**🧐 [Difference between re.search() & re.findall()](https://www.tutorialspoint.com/what-is-the-difference-between-re-search-and-re-findall-methods-in-python-regular-expressions#:~:text=Here%20you%20can%20see%20that,end%20of%20the%20given%20string.)**

- The **``re.search()``** method is able to ``find a pattern`` from ``any position of the string``.

- The **``re.findall()``** helps to get a ``list of all matching patterns``. It ``searches from start or end of the given string``. If you use ``findall()`` method to search for a pattern in a given string it will ``return all occurrences`` of the pattern. While searching a pattern, it is ``recommended`` to use ``re.findall()`` always, it works like ``re.search()`` and ``re.match()`` both.

#### Extract numbers from text as a list

In [189]:
# Define a text including zeros, ones, spaces

text = "O 1, t 10, o 100. 100000"



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression ``extracts all individual digits`` from the string text.**
- The pattern **``"\d{1}"``** specifically matches **``any single digit (0-9)``**.

In [190]:
# Find all individual digits

re.findall("\d{1}", text)

['1', '1', '0', '1', '0', '0', '1', '0', '0', '0', '0', '0']

- **``Pattern "\d{1}":``**
  - **``\d``** matches any digit (0-9).
  - **``{1}``** specifies that we want to match **``exactly one digit``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression extracts ``all occurrences of two consecutive digits`` from the string text.**
- The pattern **``"\d{2}"``** specifically matches **``any two digits in sequence``**.

In [191]:
# Find all occurrences of two consecutive digits

re.findall("\d{2}", text)

['10', '10', '10', '00', '00']



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression extracts ``all occurrences of three consecutive digits`` from the string text.**
- The pattern **``"\d{3}"``** specifically matches **``any three digits in sequence``**.

In [192]:
text

'O 1, t 10, o 100. 100000'

In [193]:
# Find all occurrences of three consecutive digits

re.findall("\d{3}", text)

['100', '100', '000']



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression extracts ``all occurrences of four consecutive digits`` from the string text.**
- The pattern **``"\d{4}"``** specifically matches **``any four digits in sequence``**.

In [194]:
# Find all occurrences of four consecutive digits

re.findall("\d{4}", text)

['1000']



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression extracts ``all occurrences of digits`` that are ``between 1 and 6 digits long`` from the string text.**
- The pattern **``"\d{1,6}"``** specifies that we want to match **``any sequence of digits``** that has **``at least 1 digit and at most 6 digits``**.

In [195]:
# Find all occurrences of digits between 1 and 6 digits long

re.findall("\d{1,6}", text)

['1', '10', '100', '100000']

- **``Pattern "\d{1,6}":``**
  - **``\d``** matches **``any digit (0-9)``**.
  - **``{1,6}``** specifies that we want to match sequences of digits that are **``at least 1 digit``** and **``at most 6 digits``** long.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression extracts ``all occurrences of one or more consecutive digits`` from the string text.**
- The pattern **``"\d+"``** specifies that we want to match sequences of digits, where **``+``** indicates **``one or more occurrences``**.

In [196]:
# Find all occurrences of one or more consecutive digits

re.findall("\d+", text)

['1', '10', '100', '100000']

- **``Pattern "\d+":``**
- **``\d``** matches **``any digit (0-9)``**.
- **``+``** specifies that we want to match **``one or more consecutive digits``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



#### Extract words begining with "f"

In [201]:
# Given the string text

text = 'which foot or hand fell fastest'



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression extracts ``all substrings from the string text that start with the letter 'f' followed by zero or more lowercase letters (a-z)``.**
- The pattern **``f[a-z]*``** specifies that we want to match **``any word starting with 'f'``**, and **``*``** means it can be followed by **``any number of lowercase letters, including none``**.

In [202]:
# Find all substrings that start with 'f'

re.findall("f[a-z]*", text)

['foot', 'fell', 'fastest']

- **``Pattern "f[a-z]*":``**
- **``f``** matches the **``literal character 'f'``**.
- **``[a-z]*``** matches **``zero or more lowercase letters following 'f'``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



#### Extract equations made up of words and numbers

In [203]:
# Given the string text

text = 'set width=20 and height=10'



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression extracts ``all key-value pairs`` from the string text where keys consist of word characters (letters, digits, or underscores) and are followed by an equals sign = and a sequence of digits.**

In [204]:
# Find all key-value pairs

re.findall('\w+=\d+', text)

['width=20', 'height=10']

- **``Pattern '\w+=\d+':``**
  - **``\w+``** matches **``one or more word characters``** (letters, digits, or underscores) for the key.
  - **``=``** is a **``literal equals sign``**.
  - **``\d+``** matches **``one or more digits``** for the value.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression extracts ``all key-value pairs`` from the string text, capturing the keys and values separately.**
- The pattern uses capturing groups to return the keys and values as tuples.

In [205]:
# Find all key-value pairs with separate capturing groups for keys and values

re.findall('(\w+)=(\d+)', text)

[('width', '20'), ('height', '10')]

- **``Pattern (\w+)=(\d+):``**
  - **``(\w+)``** captures **``one or more word characters``** (letters, digits, or underscores) for the key.
  - **``=``** is a **``literal equals sign``**.
  - **``(\d+)``** captures **``one or more digits``** for the value.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



#### Check if the string starts with 'hello'

In [206]:
# Given the string text

text = "hello world"



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression checks ``if the string text starts with the word "hello"``.**
- The **``^``** character in the pattern asserts that the match MUST occur at the **``beginning of the string``**.

In [207]:
# Find if the text starts with 'hello'

re.findall("^hello", text)

['hello']

- **``Pattern "^hello":``**
  - **``^``** asserts the position at the start of the string.
  - **``hello``** matches the literal string "hello".

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


**The following expression checks ``if the string text starts with the word "hello"`` and return that match.**
- The **``^``** character in the pattern ensures that the match occurs at the **``beginning of the string``**.



In [210]:
# Attempt to match the start of the string

re.match("^hello", text).group()

'hello'

- **``Pattern "^hello":``**
  - **``^``** asserts the position at the start of the string.
  - **``hello``** matches the literal string "hello".
- **``re.match():``**
  - This function checks for a match only at the beginning of the string.
  - If **``"hello"``** is found **``at the start``**, match.group() returns the matched substring.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression searches for the ``word "hello" at the beginning`` of the string text.**
- The **``^``** character asserts that the match MUST occur at the **``start of the string``, BUT **``re.search()``** will return a match object if it finds **``"hello" anywhere in the string``**, as long as it complies with the pattern.



In [213]:
# Search for 'hello' at the start of the string

re.search("^hello", text).group()

'hello'

- **``Pattern "^hello":``**
- **``^``** asserts the position at the start of the string.
- **``hello``** matches the literal string "hello".
- **``re.search():``**
  - This function looks for the pattern anywhere in the string.
  - If "hello" is found at the start (or anywhere), match.group() returns the matched substring.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

#### Check if the string ends with 'world'


**The following expression checks ``if the string text ends with the word "world"``.**
- The **``$``** character in the pattern asserts that the match must occur at the **``end of the string``**.



In [215]:
text

'hello world'

In [216]:
# Find if the text ends with 'world'

re.findall("world$", text)

['world']

- **``Pattern "world$":``**
  - **``world``** matches the **``literal string "world"``**.
  - **``$``** asserts the position at the **``end of the string``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>re.sub(pattern, repl, string, count=0, flags=0)</strong></p>


**🧐 [re.sub](https://docs.python.org/3/library/re.html) method returns the string obtained by **replacing the leftmost non-overlapping occurrences of the pattern in string by the replacement (repl)**.  repl attribute can be either a string or a callable; if a string, backslash escapes in it are processed.  If it is a callable, it's passed the Match object and must return a replacement string to be used.**



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



#### Remove anything other than digits

In [218]:
# Given the string text

text = "2004-959-559 # This is Phone Number"



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code ``re.sub("\D", " ", text)`` is used to ``replace`` ``all non-digit characters`` in the string text with a ``space``.**

In [219]:
# Replace all non-digit characters with a "space"

re.sub("\D", "", text)

'2004959559'

**Pattern ``\D``:**
- **``\D``** matches any character that is **``NOT a digit (0-9)``**.
**Substitution:**
- **``All occurrences``** of **``non-digit characters``** (like -, #, and spaces) are **``replaced with a space``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

#### Remove digits and replace with "."

**The following code ``re.sub("\d", ".", text)`` is used to ``replace`` ``all digit characters`` in the string text with a ``period (.)``.**

In [220]:
# Replace all digit characters with a "period"

re.sub("\d", ".", text)

'....-...-... # This is Phone Number'

- **Pattern ``\d``:**
  - **``\d``** matches **``any digit (0-9)``**.
- **Substitution:**
  - **``All occurrences``** of digits in the string are **``replaced with a period (.)``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code ``re.sub("\d", ".", text, count=4)`` is used to ``replace`` ``the first four digit characters`` in the string text with a ``period (.)``.**

In [221]:
# Replace the pattern (any numeric digit occurring four times at the beginning) with "."

re.sub("\d", ".", text, count=4)

'....-959-559 # This is Phone Number'

**Pattern ``\d``:**
- **``\d``** matches any digit (0-9).
**Substitution:**
- The **``count=4``** argument specifies that **``only the first four occurrences of digits``** should be **``replaced``** with a **``period (.)``**.
**Result:**
- The **``first four digits (2, 0, 0, and 4)``** are replaced, resulting in **``....-959-559 # This is Phone Number``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**Using ``pd.Series(text).str.replace("\d", ".", regex=True)`` allows you to ``replace`` ``all digit characters`` in a Pandas Series with a ``period (.)``.** 

In [222]:
pd.Series(text).str.replace("\d", ".", regex=True)

# str.replace() method does the same thing

0    ....-...-... # This is Phone Number
dtype: object

**Explanation:**
- **``pd.Series([text])``:** Creates a ``Pandas Series`` from the given text.
- **``.str.replace(r"\d", ".", regex=True)``:**
   - **``r"\d"``**: This pattern matches ``any digit (0-9)``.
   - **``.``**: This is the ``replacement string``.
   - **``regex=True``**: This specifies that the first argument is a regex pattern.
- **``Result``**: ``Each digit`` in the original string is ``replaced`` with ``a period``, resulting in ....-...-... # This is Phone Number.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

📢❗🚨 Note that although **``str.replace()``** method has **count** parameter, it does NOT limit the number of replacements, it simply allows you to see how many replacements were made.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>re.split(pattern, string, maxsplit=0, flags=0)</strong></p>


**🧐 [re.split()](https://docs.python.org/3/library/re.html#re.split)** method splits the source string by the occurrences of the pattern, returning a list containing the resulting substrings. If capturing parentheses are used in pattern, then the text of all groups in the pattern are also returned as part of the resulting list. If maxsplit is nonzero, at most maxsplit splits occur, and the remainder of the string is returned as the final element of the list.

**🧐 [Python Regex Split String Using re.split()](https://pynative.com/python-regex-split/)**<br>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


In [223]:
# Given the string text

text = "ab56cd78_de fg3hıi49"



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code ``re.split("\D+", text)`` is used to ``split`` the ``string text`` at ``every occurrence`` of ``one or more non-digit characters``.**

In [224]:
re.split("\D+", text)

['', '56', '78', '3', '49']

**Explanation:**
- **Pattern ``\D+``:**
   - **``\D``** matches ``any character`` that is ``not a digit (0-9)``.
   - **``+``** means ``one or more occurrences`` of the ``preceding element (non-digit characters)``.
- **Result**: The string is split into parts where non-digit characters occur.
   - The first element of the result is an empty string ('') because the string starts with non-digit characters.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code ``re.split("\D+", text, maxsplit=2)`` is used to ``split`` the ``string text`` at ``every occurrence`` of ``one or more non-digit characters``, ``limiting`` the number of ``splits to 2``.**

In [225]:
re.split("\D+", text, maxsplit=2)

['', '56', '78_de fg3hıi49']

**Explanation:**
- **Pattern ``\D+``:**
   - **``\D``** matches ``any character`` that is ``not a digit (0-9)``.
   - **``+``** means ``one or more occurrences`` of ``non-digit characters``.
- **``maxsplit=2``:**
   - This ``limits`` the ``number of splits to 2``. After two splits, the remainder of the string is returned as the last element.

**Result Breakdown:**
- The string is split into parts where non-digit characters occur.
- The first element is an empty string ('') because the original string starts with non-digit characters.
- The second element is '56', which is the first sequence of digits.
- The third element is '78_de fg3hıi49', which is the remainder of the string after two splits.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code ``re.findall("\d+", text)`` is used to ``find`` ``all sequences of digits`` in the string text.**

In [226]:
re.findall("\d+", text)

['56', '78', '3', '49']

**Explanation:**
- **Pattern ``\d+``:**
   - **``\d``** matches ``any digit (0-9)``.
   - **``+``** means ``one or more occurrences`` of the ``preceding element``, so \d+ matches sequences of digits.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Functions Accepting RegEx</p>

<a id="4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Pandas provides a variety of string functions that accept regular expressions (RegEx), allowing for powerful text manipulation and analysis. These functions, accessible through the **``.str accessor``**, enable operations such as searching, replacing, and splitting strings based on complex patterns. 
- For example, methods like .str.contains(), .str.replace(), and .str.extract() facilitate filtering and transforming data within DataFrames and Series by leveraging the flexibility of RegEx, making it easier to handle and analyze textual data efficiently.



- **[str.count()](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.count.html):** Count occurrences of pattern in each string of the Series/Index
- **[str.replace()](https://pandas.pydata.org/docs/reference/api/pandas.Series.replace.html):** Replace the search string or pattern with the given value
- **[str.contains()](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html):** Test if pattern or regex is contained within a string of a Series or Index. Calls re.search() and returns a boolean
- **[str.findall()](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.findall.html):** Find all occurrences of pattern or regular expression in the Series/Index. Equivalent to applying re.findall() on all elements
- **[str.match()](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.match.html):** Determine if each string matches a regular expression. Calls re.match() and returns a boolean
- **[str.split()](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.split.html):** Split strings around given separator/delimiter and accepts string or regular expression to split on
- **[str.extract()](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.extract.html):** Extract capture groups in the regex pat as columns in a DataFrame and returns the captured groups

In [227]:
# Data setup
data = [['Evert van Dijk', 'Carmine-pink, salmon-pink streaks, stripes, flecks. #94569# Warm pink, clear carmine pink, rose pink shaded salmon.  Mild fragrance.  Large, very double, in small clusters, high-centered bloom form.  Blooms in flushes throughout the season.'],
        ['Every Good Gift', 'Red.  Flowers velvety red.  #079463895689# Moderate fragrance.  Average diameter 4".  Medium-large, full (26-40 petals), borne mostly solitary bloom form.  Blooms in flushes throughout the season.'], 
        ['Evghenya', 'Orange-pink.  75 petals.  Large, very double #68345_686# bloom form.  Blooms in flushes throughout the season.'], 
        ['Evita', 'White or white blend.  None to mild fragrance.  35 petals #9897#.  Large, full (26-40 petals), high-centered bloom form.  Blooms in flushes throughout the season.'],
        ['Evrathin', 'Light pink. [Deep pink.]  Outer petals white. Expand rarely #679754YH89#.  Mild fragrance.  35 to 40 petals.  Average diameter 2.5".  Medium, double (17-25 petals), full (26-40 petals), cluster-flowered, in small clusters bloom form.  Prolific, once-blooming spring or summer.  Glandular sepals, leafy sepals, long sepals buds.'],
        ['Evita 2', 'White, blush shading.  Mild, wild rose fragrance #AGHJS876IOP#.  20 to 25 petals.  Average diameter 1.25".  Small, very double, cluster-flowered bloom form.  Blooms in flushes throughout the season.']]
  
# Create the DataFrame
df = pd.DataFrame(data, columns=['name', 'bloom']) 

# Display the DataFrame
df 

name  \
0   Evert van Dijk   
1  Every Good Gift   
2         Evghenya   
3            Evita   
4         Evrathin   
5          Evita 2   

                                                                                                                                                                                                                                                                                                                                     bloom  
0                                                                                         Carmine-pink, salmon-pink streaks, stripes, flecks. #94569# Warm pink, clear carmine pink, rose pink shaded salmon.  Mild fragrance.  Large, very double, in small clusters, high-centered bloom form.  Blooms in flushes throughout the season.  
1                                                                                                                                     Red.  Flowers velvety red.  #079463895689# Moderate fragrance.  Average diameter 4".  Medium-large, full (26-40 petals), borne mostly solitary bloom form.  Blooms in flushes throughout the season.  
2                                                                                                                                                                                                                           Orange-pink.  75 petals.  Large, very double #68345_686# bloom form.  Blooms in flushes throughout the season.  
3                                                                                                                                                                       White or white blend.  None to mild fragrance.  35 petals #9897#.  Large, full (26-40 petals), high-centered bloom form.  Blooms in flushes throughout the season.  
4  Light pink. [Deep pink.]  Outer petals white. Expand rarely #679754YH89#.  Mild fragrance.  35 to 40 petals.  Average diameter 2.5".  Medium, double (17-25 petals), full (26-40 petals), cluster-flowered, in small clusters bloom form.  Prolific, once-blooming spring or summer.  Glandular sepals, leafy sepals, long sepals buds.  
5                                                                                                                                   White, blush shading.  Mild, wild rose fragrance #AGHJS876IOP#.  20 to 25 petals.  Average diameter 1.25".  Small, very double, cluster-flowered bloom form.  Blooms in flushes throughout the season.



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>pandas.Series.str.count(pat, flags=0)</strong></p>


- Count occurrences of pattern in each string of the Series/Index.

- This function is used to count the number of times a particular regex pattern is repeated in each of the string elements of the Series.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


**The following code ``displays the bloom feature`` of the DataFrame with a ``maximum column width of 400 characters``.**

In [228]:
# Set the maximum column width for display
pd.options.display.max_colwidth = 400

# Display the bloom feature
df[["bloom"]]

bloom
0                                                                                         Carmine-pink, salmon-pink streaks, stripes, flecks. #94569# Warm pink, clear carmine pink, rose pink shaded salmon.  Mild fragrance.  Large, very double, in small clusters, high-centered bloom form.  Blooms in flushes throughout the season.
1                                                                                                                                     Red.  Flowers velvety red.  #079463895689# Moderate fragrance.  Average diameter 4".  Medium-large, full (26-40 petals), borne mostly solitary bloom form.  Blooms in flushes throughout the season.
2                                                                                                                                                                                                                           Orange-pink.  75 petals.  Large, very double #68345_686# bloom form.  Blooms in flushes throughout the season.
3                                                                                                                                                                       White or white blend.  None to mild fragrance.  35 petals #9897#.  Large, full (26-40 petals), high-centered bloom form.  Blooms in flushes throughout the season.
4  Light pink. [Deep pink.]  Outer petals white. Expand rarely #679754YH89#.  Mild fragrance.  35 to 40 petals.  Average diameter 2.5".  Medium, double (17-25 petals), full (26-40 petals), cluster-flowered, in small clusters bloom form.  Prolific, once-blooming spring or summer.  Glandular sepals, leafy sepals, long sepals buds.
5                                                                                                                                   White, blush shading.  Mild, wild rose fragrance #AGHJS876IOP#.  20 to 25 petals.  Average diameter 1.25".  Small, very double, cluster-flowered bloom form.  Blooms in flushes throughout the season.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

### How many numerical values are there in each row of "bloom" feature?

- **The following method ``counts the occurrences of numeric patterns`` in the bloom column of the DataFrame. The pattern ``"\d+"`` matches ``one or more digits``.**

In [229]:
# Count occurrences of numeric patterns in the 'bloom' column

df.bloom.str.count("\d+")

0     1
1     4
2     3
3     4
4    10
5     5
Name: bloom, dtype: int64

- **``df['bloom'].str.count(r"\d+"):``**
  - This counts **``how many times one or more digits appear in each string``** of the bloom column.
  - The result is a Series where each entry corresponds to the **``count of digits``** in the respective row of the bloom descriptions.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



### How many characters are there in each row of "bloom" feature?

- **The following ``apply(len)`` method gets the ``length of each string`` in the bloom column of the DataFrame. This will return a Series containing the number of characters in each bloom description.**

In [230]:
# Apply len to get the length of each bloom description

df.bloom.apply(len)

0    240
1    196
2    110
3    162
4    327
5    198
Name: bloom, dtype: int64

- **``df['bloom'].apply(len):``**
  - This applies the len function to each string in the bloom column, returning the **``number of characters in each description``**.
  - The result is a Series where each entry corresponds to the length of the respective row's bloom description.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following** **[str.count()](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.count.html)** **method ``counts the number of periods (.)`` in each entry of the bloom column of the DataFrame.**
- This will return a Series containing the count of periods in each bloom description.

In [232]:
# Count the number of periods in each bloom description

df.bloom.str.count(".")

0     5
1     6
2     4
3     5
4    11
5     7
Name: bloom, dtype: int64

- **SYNTAX: ``Series.str.count(pat, flags=0)``**
  - 👉 **``pat``** argument is **``valid regular expression``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


- **``df['bloom'].str.count(r"\."):``**
  - This counts **``how many times the period character (.) appears in each string``** of the bloom column.
  - The result is a Series where each entry corresponds to the count of periods in the respective row of the bloom descriptions.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>⚠️ BE CAREFUL: The dot (.) matches any character in regex ❗❗❗ So, it counts all characters in each entry (row). To count literal dots, it's a good practice to escape it using a backslash: '\.'.</strong></p>

- **[Special characters in regular expressions](https://users.pja.edu.pl/~jms/qnx/help/watcom/wd/regexp.html#:~:text=The%20dot%20(.),special%20meaning%20matches%20that%20character.)**
- **[The Dot Matches (Almost) Any Character](https://www.regular-expressions.info/dot.html)**
- **[Special Characters in Regular Expressions](https://simpleregex.dev/special-characters/)**

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



### How many sentences are there in each row of "bloom" feature?

- **The following ``str.count()`` method ``counts the number of periods (.)`` in each entry of the bloom column of the DataFrame.**
  - In this case, we need to **``escape the period``** in the regex pattern to ensure it is treated as a **``literal character``**.

In [233]:
# Count the number of periods in each bloom description

df.bloom.str.count("\.")

0     5
1     6
2     4
3     5
4    11
5     7
Name: bloom, dtype: int64



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>pandas.Series.str.replace(pat, repl, n=- 1, case=None, flags=0, regex=None)</strong></p>


- Replace each occurrence of pattern/regex in the Series/Index.

- Equivalent to str.replace() or re.sub(), depending on the regex value.

### Replace the values finding between the two "#" characters (including "#" characters) with the "" in each row of "bloom" feature.

- **The following ``str.replace()`` method removes substrings that match a specific pattern from the bloom column of the DataFrame.**
  - In this case, the pattern "#\S+#" matches any sequence of characters that starts and ends with a #, including non-whitespace characters in between.

In [234]:
display(df["bloom"][5])

# Remove substrings that match the pattern "#\S+#" and assign it to itself

df["bloom"] = df.bloom.str.replace("#\S+#", "", regex=True)

'White, blush shading.  Mild, wild rose fragrance #AGHJS876IOP#.  20 to 25 petals.  Average diameter 1.25".  Small, very double, cluster-flowered bloom form.  Blooms in flushes throughout the season.'

- This replaces any substring that matches the pattern **``#\S+#``** (i.e., a **``# followed by one or more non-whitespace characters, followed by another #``**) with an empty string.
- The **``regex=True``** argument specifies that the **``pattern should be interpreted as a regular expression``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [235]:
# Display the updated DataFrame

df["bloom"][5]

'White, blush shading.  Mild, wild rose fragrance .  20 to 25 petals.  Average diameter 1.25".  Small, very double, cluster-flowered bloom form.  Blooms in flushes throughout the season.'



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>pandas.Series.str.contains(pat, case=True, flags=0, na=None, regex=True)</strong></p>


- Test if pattern or regex is contained within a string of a Series or Index.

- Return boolean Series or Index based on whether a given pattern or regex is contained within a string of a Series or Index.

### Which rows in "bloom" feature includes "diameter" value?

- **The following str.contains() method checks which entries in the bloom column of the DataFrame contain the word "diameter".**
  - This method returns a boolean Series indicating whether each entry contains the specified substring.

In [236]:
# Check which bloom descriptions contain the word "diameter"

df["bloom"].str.contains("diameter", case=False)

0    False
1     True
2    False
3    False
4     True
5     True
Name: bloom, dtype: bool

In [238]:
df["bloom"]

0                                                                                      Carmine-pink, salmon-pink streaks, stripes, flecks.  Warm pink, clear carmine pink, rose pink shaded salmon.  Mild fragrance.  Large, very double, in small clusters, high-centered bloom form.  Blooms in flushes throughout the season.
1                                                                                                                                         Red.  Flowers velvety red.   Moderate fragrance.  Average diameter 4".  Medium-large, full (26-40 petals), borne mostly solitary bloom form.  Blooms in flushes throughout the season.
2                                                                                                                                                                                                                            Orange-pink.  75 petals.  Large, very double  bloom form.  Blooms in flushes throughout the season.
3                                    

- This checks each string in the bloom column to see if it contains the substring "diameter".
- The **``case=False``** argument makes the search **``case-insensitive``**, so it will match "Diameter", "DIAMETER", etc.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following checks which entries in the bloom column of the DataFrame contain a pattern that matches a ``digit followed by a double quote (")``.**

In [241]:
# Check which bloom descriptions contain a digit followed by a double quote

df["bloom"].str.contains('\d+"')

0    False
1     True
2    False
3    False
4     True
5     True
Name: bloom, dtype: bool

- This checks each string in the bloom column to see if it contains one or more digits (\d+) followed by a double quote (").
  - If the r was used before the string, it would indicate that it's a raw string, which treats backslashes as literal characters, making it easier to write regex patterns.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [240]:
# Display the output as DataFrame format

df[df["bloom"].str.contains('\d+"')]

name  \
1  Every Good Gift   
4         Evrathin   
5          Evita 2   

                                                                                                                                                                                                                                                                                                                         bloom  
1                                                                                                                                       Red.  Flowers velvety red.   Moderate fragrance.  Average diameter 4".  Medium-large, full (26-40 petals), borne mostly solitary bloom form.  Blooms in flushes throughout the season.  
4  Light pink. [Deep pink.]  Outer petals white. Expand rarely .  Mild fragrance.  35 to 40 petals.  Average diameter 2.5".  Medium, double (17-25 petals), full (26-40 petals), cluster-flowered, in small clusters bloom form.  Prolific, once-blooming spring or summer.  Glandular sepals, leafy sepals, long sepals buds.  
5                                                                                                                                    White, blush shading.  Mild, wild rose fragrance .  20 to 25 petals.  Average diameter 1.25".  Small, very double, cluster-flowered bloom form.  Blooms in flushes throughout the season.



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>pandas.Series.str.findall(pat, flags=0)</strong></p>


- Find all occurrences of pattern or regular expression in the Series/Index.

- Equivalent to applying re.findall() to all the elements in the Series/Index.

### Find all numeric values in each rows of the "bloom" feature:

- **The following str.findall() method extracts all occurrences of one or more digits from each entry in the bloom column of the DataFrame. This method returns a list of all matches found in each string.**

In [242]:
# Find all occurrences of digits in each bloom description

df["bloom"].str.findall("\d+")

0                                []
1                       [4, 26, 40]
2                              [75]
3                      [35, 26, 40]
4    [35, 40, 2, 5, 17, 25, 26, 40]
5                   [20, 25, 1, 25]
Name: bloom, dtype: object

- This extracts **``all sequences of one or more digits``** from each string in the bloom column.
- The result is a Series where each entry is a list of strings representing the digit sequences found in the corresponding bloom description.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

### Find diameter values in each rows of the "bloom" feature:

- **The following str.findall() method extracts ``both numbers with decimal points and numbers followed by a double quote`` from each entry in the bloom column of the DataFrame.**

In [243]:
# Find all occurrences of numbers with decimal points and numbers followed by a double quote

df["bloom"].str.findall('\d+\.\d+"|\d+"')

0         []
1       [4"]
2         []
3         []
4     [2.5"]
5    [1.25"]
Name: bloom, dtype: object

- This extracts all sequences that match either a number with decimals followed by a double quote or a whole number followed by a double quote from each string in the bloom column.
- The result is a Series where each entry is a list of strings representing the matches found in the corresponding bloom description.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


- The regex pattern **``'\d+\.\d+"|\d+"'``** matches either:
 - **``\d+\.\d+"``**: One or more digits, followed by a decimal point, followed by one or more digits, and ending with a double quote.
 - **``\d+"``**: One or more digits followed by a double quote.
 


<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>pandas.Series.str.match(pat, case=True, flags=0, na=None)</strong></p>


- Determine if each string starts with a match of a regular expression.

### Find the rows of pink blooms (this information is available in the first words of the rows):

- **The following str.match() method checks if each entry in the bloom column of the DataFrame starts with a string that matches the specified pattern.**
  - In this case, we're looking for entries that either **``contain "pink"``**, **``end with "-pink"``**, or **``have "pink" preceded by a word``**.

In [244]:
df["bloom"]

0                                                                                      Carmine-pink, salmon-pink streaks, stripes, flecks.  Warm pink, clear carmine pink, rose pink shaded salmon.  Mild fragrance.  Large, very double, in small clusters, high-centered bloom form.  Blooms in flushes throughout the season.
1                                                                                                                                         Red.  Flowers velvety red.   Moderate fragrance.  Average diameter 4".  Medium-large, full (26-40 petals), borne mostly solitary bloom form.  Blooms in flushes throughout the season.
2                                                                                                                                                                                                                            Orange-pink.  75 petals.  Large, very double  bloom form.  Blooms in flushes throughout the season.
3                                    

In [245]:
# Check if each bloom description matches the pattern

df["bloom"].str.match("pink|\w+-pink|\w+ pink")

0     True
1    False
2     True
3    False
4     True
5    False
Name: bloom, dtype: bool

- This checks for the presence of "pink", a word followed by "-pink", or a word followed by "pink" anywhere in the string.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

- **The following str.match() method checks if each entry in the specified Series matches a regex pattern from the start of the string.**

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:115%; text-align:left;"><strong>REMEMBER!!!</strong></p>

  - 👉 **``str.match(pattern)``**: This method checks if the string **``matches the pattern starting from the beginning``**. The pattern **``("pink|\w+-pink|\w+ pink")``** will **``only match if the string starts with "pink", a word followed by "-pink", or a word followed by "pink"``**.

In [246]:
# Check if each bloom description matches the pattern

df["bloom"].str.match("pink|\w+-pink|\w+ pink")

0     True
1    False
2     True
3    False
4     True
5    False
Name: bloom, dtype: bool

- **``str.match()``** is indeed used for checking matches **``starting from the beginning of the string``**.
- If we want to check for any occurrence of the pattern **``anywhere in the string``**, we would **``use str.contains()``** instead.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following str.match() method checks if each entry in the bloom column starts with the word "pink" or has a word followed by either "-pink" or " pink".**

In [247]:
# Check if each bloom description matches the pattern

df["bloom"].str.match("pink|\w+[- ]?pink")

0     True
1    False
2     True
3    False
4     True
5    False
Name: bloom, dtype: bool

- **``df['bloom'].str.match(r"pink|\w+[- ]?pink")``**:
  - **``pink``**: Matches if the string starts with "pink".
  - **``\w+[- ]?pink``**: Matches if the string starts with a word followed by either "-pink" or " pink". The **``[- ]?``** part means it will match **``either a hyphen or a space (or none) before "pink"``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression checks if each entry in the bloom column ``contains at least one character followed by the word "pink" at the start of the string``. The ``.+`` means ``"one or more of any character"``.**

In [248]:
# Check if each bloom description matches the pattern

df["bloom"].str.match(".+pink")

0     True
1    False
2     True
3    False
4     True
5    False
Name: bloom, dtype: bool

- This checks if each string **``starts with at least one character followed by "pink"``**.
- If the string starts directly with "pink" or any other characters before "pink", it will match.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>pandas.Series.str.split(pat=None, n=- 1, expand=False, *, regex=None)</strong></p>


- Split strings around given separator/delimiter.

- Splits the string in the Series/Index from the beginning, at the specified delimiter string.

### Split each rows of "bloom" feature from the dot character as sentences:

- **The following str.split() method splits the entries in the bloom column of the DataFrame by a specified delimiter.**
  - In this case, we're splitting by the string **``". "``** (**``a period followed by a space``**), which is often used to separate sentences.

In [249]:
# Split each bloom description by ". "

df["bloom"].str.split("\. ")

0                                                                                      [Carmine-pink, salmon-pink streaks, stripes, flecks,  Warm pink, clear carmine pink, rose pink shaded salmon,  Mild fragrance,  Large, very double, in small clusters, high-centered bloom form,  Blooms in flushes throughout the season.]
1                                                                                                                                         [Red,  Flowers velvety red,   Moderate fragrance,  Average diameter 4",  Medium-large, full (26-40 petals), borne mostly solitary bloom form,  Blooms in flushes throughout the season.]
2                                                                                                                                                                                                                            [Orange-pink,  75 petals,  Large, very double  bloom form,  Blooms in flushes throughout the season.]
3                              

- This splits each string in the bloom column at each occurrence of the delimiter **``". "``** (**``period followed by a space``**).
- The result is a Series where each entry is a list of sentences extracted from the original string.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression splits the entries in the bloom column by the ``delimiter ". "`` (``a period followed by a space``) and ``expands the result into separate columns``.**
- This is useful when we want to **``create a DataFrame where each sentence from the original string occupies its own column``**.

In [250]:
# Split each bloom description by ". ", expanding into separate columns

df["bloom"].str.split("\. ", expand=True)

0  \
0  Carmine-pink, salmon-pink streaks, stripes, flecks   
1                                                 Red   
2                                         Orange-pink   
3                                White or white blend   
4                                          Light pink   
5                                White, blush shading   

                                                         1  \
0   Warm pink, clear carmine pink, rose pink shaded salmon   
1                                      Flowers velvety red   
2                                                75 petals   
3                                   None to mild fragrance   
4                         [Deep pink.]  Outer petals white   
5                               Mild, wild rose fragrance    

                                 2  \
0                   Mild fragrance   
1               Moderate fragrance   
2   Large, very double  bloom form   
3                       35 petals    
4                   Expand rarely    
5                  20 to 25 petals   

                                                                  3  \
0   Large, very double, in small clusters, high-centered bloom form   
1                                               Average diameter 4"   
2                          Blooms in flushes throughout the season.   
3              Large, full (26-40 petals), high-centered bloom form   
4                                                    Mild fragrance   
5                                            Average diameter 1.25"   

                                                                      4  \
0                              Blooms in flushes throughout the season.   
1   Medium-large, full (26-40 petals), borne mostly solitary bloom form   
2                                                                  None   
3                              Blooms in flushes throughout the season.   
4                                                       35 to 40 petals   
5                       Small, very double, cluster-flowered bloom form   

                                           5  \
0                                       None   
1   Blooms in flushes throughout the season.   
2                                       None   
3                                       None   
4                      Average diameter 2.5"   
5   Blooms in flushes throughout the season.   

                                                                                                     6  \
0                                                                                                 None   
1                                                                                                 None   
2                                                                                                 None   
3                                                                                                 None   
4   Medium, double (17-25 petals), full (26-40 petals), cluster-flowered, in small clusters bloom form   
5                                                                                                 None   

                                           7  \
0                                       None   
1                                       None   
2                                       None   
3                                       None   
4   Prolific, once-blooming spring or summer   
5                                       None   

                                                    8  
0                                                None  
1                                                None  
2                                                None  
3                                                None  
4   Glandular sepals, leafy sepals, long sepals buds.  
5                                                None

- This splits each entry in the bloom column at each occurrence of the delimiter ". " and expands the result into separate columns.
- The result is a DataFrame where each sentence is placed in its own column.
- If there are fewer sentences in some entries than in others, the resulting DataFrame will have NaN or NoNe values in the empty cells.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:125%; text-align:left;"><strong>📌 EXTRA EXAMPLE ON SPLIT:</strong></p>


**The following statement creates a pandas Series from the list info and then parse the information to extract individual fields like id, age, and salary.**
- Below is an example of how to create a Series and then split the strings into a DataFrame for easier analysis.

In [251]:
# Sample data
info = ["id:345, age:25, salary:1200", "id:346, age:32, salary:1500", "id:347, age:28, salary:1400"]

# Create a pandas Series
s = pd.Series(info)

# Display the Series
s

0    id:345, age:25, salary:1200
1    id:346, age:32, salary:1500
2    id:347, age:28, salary:1400
dtype: object



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



### Split the Series to create a dataframe consisting of "id, age and salary" columns:

In [252]:
# Split the Series entries based on non-digit characters

s.str.split("\D+", expand=True)

0    1   2     3
0    345  25  1200
1    346  32  1500
2    347  28  1400

- **``\D+``** is a regex pattern that matches **``one or more non-digit characters``**.
- The **``expand=True``** argument makes the result a DataFrame rather than a Series, with each extracted number in its own column.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>🤔💭 Why is the first column empty❓</strong></p>

- The first column is empty because the split occurs at the start of the string where there are non-digit characters ("id:"). When we use s.str.split(r"\D+", expand=True), the regex \D+ matches one or more non-digit characters. This means that the splitting will occur at every non-digit character, including the very start of the string if it begins with non-digits.
- In our specific case, since the strings start with "id:", the split operation results in an empty string for the first column because there are no digits before the first non-digit characters.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>NOTE !!!</strong></p>

- If there are multiple non-digit characters at the beginning of the strings or if the first segment is empty, the first column will likely contain NaN or empty strings.
  - If we were to have strings that start with non-digit characters but do not contain any digits immediately after (e.g., "id:," or "age:,"), then we would see empty strings or NaN in the first column.
- We may want to convert the remaining columns to numeric types for further analysis using df.apply(pd.to_numeric) if needed.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following statement ``splits the Series s based on non-digit characters`` and then ``select all columns except the first one``.**
- This effectively removes the first column, which may contain empty strings or unwanted data.

In [253]:
# Split the Series entries based on non-digit characters and remove the first column
df = s.str.split("\D+", expand=True).iloc[:, 1:]

# Display the DataFrame
df

1   2     3
0  345  25  1200
1  346  32  1500
2  347  28  1400

- **``s.str.split(r"\D+", expand=True):``**
  - This splits each string in the Series s based on non-digit characters, resulting in a DataFrame where each cell contains the numeric values extracted from the original strings.
- **``.iloc[:, 1:]:``**
  - This selects all rows and all columns from the second column onward (effectively removing the first column). This is useful if the first column contains empty strings or unwanted data.



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code renames the columns of the DataFrame to ["id", "age", "salary"] after removing the empty column.**

In [254]:
# Assign new column names
df.columns = ["id", "age", "salary"]

# Display the updated DataFrame
df

id age salary
0  345  25   1200
1  346  32   1500
2  347  28   1400



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>pandas.Series.str.extract(pat, flags=0, expand=True)</strong></p>


- Extract capture groups in the regex pat as columns in a DataFrame.

- For each subject string in the Series, extract groups from the first match of regular expression pat.

### Extract just numbers:

- **The following code creates a pandas Series from the list ['a3aa', 'b4aa', 'c5aa'] as follows.**

In [255]:
# Create a pandas Series
s = pd.Series(['a3aa', 'b4aa', 'c5aa'])

# Display the Series
s

0    a3aa
1    b4aa
2    c5aa
dtype: object



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code ``extracts the first digit`` from each string in the pandas Series s. The regex pattern ``(\d) matches a single digit``.**

In [256]:
# Extract the first digit from each string

s.str.extract("(\d)")

0
0  3
1  4
2  5

- The pattern **``(\d) captures the first occurrence of any digit``** in each string.
- The result is a DataFrame where each entry contains the first digit found in the corresponding string from the Series.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

### Extract just letters:


- **The following code extracts patterns from each string in the pandas Series s where there is a ``non-digit character followed by a digit and then followed by one or more non-digit characters``.**

In [257]:
# Extract the pattern

s.str.extract("(\D)\d(\D+)")

0   1
0  a  aa
1  b  aa
2  c  aa

- **``(\D)``**: Captures a **``single non-digit character (the letter)``**.
- **``(\d)``**: Captures a **``single digit``**.
- **``(\D+)``**: Captures **``one or more non-digit characters that follow the digit``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

- **The following code extracts patterns from each string in the pandas Series s where there is a ``non-digit character followed by a digit and then two additional non-digit characters``.**

In [258]:
# Extract the pattern

s.str.extract("(\D)\d(\D)(\D)")

0  1  2
0  a  a  a
1  b  a  a
2  c  a  a

- **``Pattern Breakdown:``**
  - **``(\D)``**: Captures a **``single non-digit character (the letter)``**.
  - **``(\d)``**: Captures a **``single digit``**.
  - **``(\D)``**: Captures the **``first non-digit character following the digit``**.
  - **``(\D)``**: Captures the **``second non-digit character following the digit``**.
- **``Resulting DataFrame:``**
  - **``The resulting DataFrame will have four columns:``**
    - The first column contains the initial non-digit character.
    - The second column contains the digit.
    - The third column contains the first non-digit character after the digit.
    - The fourth column contains the second non-digit character after the digit.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

- **The following code extracts patterns from each string in the pandas Series s where there is a ``word character (alphanumeric or underscore), followed by a digit, and then two additional word characters``.**

In [259]:
# Extract the pattern

s.str.extract("(\w)\d(\w)(\w)")

0  1  2
0  a  a  a
1  b  a  a
2  c  a  a

- **``Pattern Breakdown:``**
  - **``(\w)``**: Captures a **``single word character (alphanumeric or underscore)``**.
  - **``(\d)``**: Captures a **``single digit``**.
  - **``(\w)``**: Captures the **``first word character following the digit``**.
  - **``(\w)``**: Captures the **``second word character following the digit``**.
- **``Resulting DataFrame:``**
  - **``The resulting DataFrame will have four columns:``**
    - The first column contains the initial word character.
    - The second column contains the digit.
    - The third column contains the first word character after the digit.
    - The fourth column contains the second word character after the digit.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:125%; text-align:left;"><strong>📌 EXTRA EXAMPLE ON EXTRACT:</strong></p>


### Extract "id, age and salary" values to create a dataframe consisting of "id, age and salary" columns:

- **The following statement creates a pandas Series from the list info containing strings with various fields like id, age, and salary.**

In [260]:
# Sample data
info = ["id:345, age:25, salary:1200", "id:346, age:32, salary:1500", "id:347, age:28, salary:1400"]

# Create a pandas Series
s = pd.Series(info)

# Display the Series
s

0    id:345, age:25, salary:1200
1    id:346, age:32, salary:1500
2    id:347, age:28, salary:1400
dtype: object



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following statement ``extracts the numeric values from each string`` in the pandas Series s, capturing the first, second, and third sets of digits (for id, age, and salary, respectively) and then ``assigns the output into DataFrame``. The regex pattern matches one or more digits followed by non-digit characters.**

In [261]:
# Extract the numeric values and assign the output into DataFrame
df = s.str.extract("(\d+)\D+(\d+)\D+(\d+)")

# Display the DataFrame
df

0   1     2
0  345  25  1200
1  346  32  1500
2  347  28  1400

- **``s.str.extract(r"(\d+)\D+(\d+)\D+(\d+)")``** uses regex to extract three groups of digits:
  - The **``first group``** captures the digits from the id.
  - The **``second group``** captures the digits the age.
  - The **``third group``** captures the digits the salary.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code renames the columns of the DataFrame to ["id", "age", "salary"] after removing the empty column.**

In [262]:
# Assign new column names
df.columns = ["id", "age", "salary"]

# Display the updated DataFrame
df

id age salary
0  345  25   1200
1  346  32   1500
2  347  28   1400



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code finds ``all occurrences of one or more digits`` in each string of the pandas Series s.**
- This method returns a list of strings containing the matched digits for each entry.

In [263]:
# Find all occurrences of digits in each string

s.str.findall("(\d+)")

0    [345, 25, 1200]
1    [346, 32, 1500]
2    [347, 28, 1400]
dtype: object



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:125%; text-align:left;"><strong>📌 EXTRA EXAMPLE ON EXTRACT:</strong></p>


### Extract first number:

- **The following code creates a Pandas Series named ``"s"`` that contains each ``fuel consumption`` value from a real-world dataset as an element.**

In [264]:
# Create a pandas Series
s = pd.Series(['40 l/100 km (comb)', 
               '38 l/100 km (comb)', '6.4 l/100 km (comb)',
               '8.3 kg/100 km (comb)', '5.1 kg/100 km (comb)',
               '5.4 l/100 km (comb)', '6.7 l/100 km (comb)',
               '6.2 l/100 km (comb)', '7.3 l/100 km (comb)',
               '6.3 l/100 km (comb)', '5.7 l/100 km (comb)',
               '6.1 l/100 km (comb)', '6.8 l/100 km (comb)',
               '7.5 l/100 km (comb)', '7.4 l/100 km (comb)',
               '3.6 kg/100 km (comb)', '0 l/100 km (comb)', 
               '7.8 l/100 km (comb)'])

# Display the Series
s

0       40 l/100 km (comb)
1       38 l/100 km (comb)
2      6.4 l/100 km (comb)
3     8.3 kg/100 km (comb)
4     5.1 kg/100 km (comb)
5      5.4 l/100 km (comb)
6      6.7 l/100 km (comb)
7      6.2 l/100 km (comb)
8      7.3 l/100 km (comb)
9      6.3 l/100 km (comb)
10     5.7 l/100 km (comb)
11     6.1 l/100 km (comb)
12     6.8 l/100 km (comb)
13     7.5 l/100 km (comb)
14     7.4 l/100 km (comb)
15    3.6 kg/100 km (comb)
16       0 l/100 km (comb)
17     7.8 l/100 km (comb)
dtype: object

- Given the Series s, which contains **``fuel consumption``** data in various formats (either in liters or kilograms per 100 kilometers), we can perform various operations to extract relevant information, such as the numeric values and their respective units.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code extracts the ``first sequence of non-whitespace characters`` from each string in the pandas Series s.**
- The regex pattern **``\S+``** matches **``one or more non-whitespace characters``**.

In [265]:
# Extract the first sequence of non-whitespace characters
s.str.extract("(\S+)")

# s.str.extract("(\d+\.\d+|\d+)")  # Gives the same result
# s.str.extract("(\d*\.?\d*)")     # Gives the same result

0
0    40
1    38
2   6.4
3   8.3
4   5.1
5   5.4
6   6.7
7   6.2
8   7.3
9   6.3
10  5.7
11  6.1
12  6.8
13  7.5
14  7.4
15  3.6
16    0
17  7.8



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

### Extract first and second number:

- **The following expression extract ``two groups`` from each string in the pandas Series s.**
  - The **``first group``** captures a **``floating-point number``** (which may have digits before and after a decimal point), and 
  - The **``second group``** captures an **``integer``** that appears later in the string, after any characters.

In [266]:
# Extract the specified patterns

s.str.extract('(\d*.\d*).+/(\d*)')

0    1
0   40   100
1   38   100
2   6.4  100
3   8.3  100
4   5.1  100
5   5.4  100
6   6.7  100
7   6.2  100
8   7.3  100
9   6.3  100
10  5.7  100
11  6.1  100
12  6.8  100
13  7.5  100
14  7.4  100
15  3.6  100
16   0   100
17  7.8  100

- **``(\d+\.\d+)``**: Captures a floating-point number (one or more digits followed by a decimal point and one or more digits).
- **``.+/``**: Matches one or more characters followed by a slash (not captured).
- **``(\d+)``**: Captures an integer (one or more digits).

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>Important Note !!!</strong></p>

- The pattern <b>``(\d*.\d*)``</b> may NOT capture floating-point numbers correctly due to the use of **``.``** which matches any character. It should be **``(\d+\.\d+)``** for correct matching of decimal numbers.
- Ensure that the strings contain the expected format; otherwise, NaN will be returned for entries that do NOT match the pattern.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:125%; text-align:left;"><strong>📌 EXTRA EXAMPLE ON EXTRACT:</strong></p>


### Extract date as month and year separately:

- **The following code creates a Pandas Series  from a real-world dataset, which contains ``date`` and ``fuel consumption`` information.**

In [267]:
# Create a pandas Series
s = pd.Series(['06/2020\n\n4.9 l/100 km (comb)',
               '11/2020\n\n166 g CO2/km (comb)',                                 
               '10/2019\n\n5.3 l/100 km (comb)',
               '05/2022\n\n6.3 l/100 km (comb)',
               '07/2019\n\n128 g CO2/km (comb)',
               '06/2022\n\n112 g CO2/km (comb)',                                                 
               '01/2022\n\n5.8 l/100 km (comb)',
               '11/2020\n\n106 g CO2/km (comb)',
               '04/2019\n\n105 g CO2/km (comb)',
               '08/2020\n\n133 g CO2/km (comb)',
               '04/2022\n\n133 g CO2/km (comb)'])

# Display the Series
s

0     06/2020\n\n4.9 l/100 km (comb)
1     11/2020\n\n166 g CO2/km (comb)
2     10/2019\n\n5.3 l/100 km (comb)
3     05/2022\n\n6.3 l/100 km (comb)
4     07/2019\n\n128 g CO2/km (comb)
5     06/2022\n\n112 g CO2/km (comb)
6     01/2022\n\n5.8 l/100 km (comb)
7     11/2020\n\n106 g CO2/km (comb)
8     04/2019\n\n105 g CO2/km (comb)
9     08/2020\n\n133 g CO2/km (comb)
10    04/2022\n\n133 g CO2/km (comb)
dtype: object

- Given the Series s, which contains **``fuel consumption``** and **``emissions``** information **``formatted with dates``** and various units, we can perform various operations to extract relevant information, such as the numeric values and their respective units.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression extracts ``two groups`` from each string in the pandas Series s.**
- The **``first group``** captures a **``two-digit number``**, and 
- The **``second group``** captures a **``four-digit number``**, with any character in between.

In [268]:
s.str.extract("(\d\d).(\d\d\d\d)")


#s.str.extract("(\d{2}).(\d{4})")    # Gives the same result
#s.str.extract("(\d*).(\d*)")        # Gives the same result
#s.str.extract("(\d\d)/(\d*)")       # Gives the same result
#s.str.extract("(\d\d)/(\d\d\d\d)")  # Gives the same result
#s.str.extract("(\d+).(\d+)")        # Gives the same result
#s.str.extract("(\S+)/(\S+)")        # Gives the same result

0     1
0   06  2020
1   11  2020
2   10  2019
3   05  2022
4   07  2019
5   06  2022
6   01  2022
7   11  2020
8   04  2019
9   08  2020
10  04  2022

- **``(\d\d)``** OR **``(\d{2})``**: Captures a **``two-digit number``**.
- **``.``**: Matches any character (this can lead to unexpected behavior if the character between the two groups is not as intended).
- **``(\d\d\d\d)``** OR **``(\d{4})``**: Captures a four-digit number.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

### Extract date and comsuption value:

**The following extracts **``two groups``** from each string in the pandas Series s.**
- The **``first group``** captures a **``date``** in the format **``MM/YYYY``**, and 
- The **``second group``** captures either a **``decimal number``** OR an **``integer``**.

In [269]:
# Extract the date and numeric values

s.str.extract('(\d+/\d+)\s+(\d+.\d+|\d+)')

0    1
0   06/2020  4.9
1   11/2020  166
2   10/2019  5.3
3   05/2022  6.3
4   07/2019  128
5   06/2022  112
6   01/2022  5.8
7   11/2020  106
8   04/2019  105
9   08/2020  133
10  04/2022  133

- **``(\d+/\d+)``**: Captures the date in the format **``MM/YYYY``**.
- **``\s+``**: Matches **``one or more whitespace characters``**.
- **``(\d+\.\d+|\d+)``**: Captures either a **``decimal number``** (like 4.9) or an **``integer``** (like 166).

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:125%; text-align:left;"><strong>📌 EXTRA EXAMPLE ON EXTRACT:</strong></p>


### Extract date as month and year separately:

- **The following code creates a Pandas Series from a real-world dataset, which contains ``fuel consumption`` and ``date`` information.**

In [270]:
# Create a pandas Series
s = pd.Series(['\n\n4.9 06/2020 l/100 km (comb)',
               '\n\n166 11/2020 g CO2/km (comb)',                                 
               '\n\n5.3 10/2019 l/100 km (comb)',
               '\n\n6.3 05/2022 l/100 km (comb)',
               '\n\n128 07/2019 g CO2/km (comb)',
               '\n\n112 06/2022 g CO2/km (comb)',                                                 
               '\n\n5.8 01/2022 l/100 km (comb)'])

# Display the Series
s

0    \n\n4.9 06/2020 l/100 km (comb)
1    \n\n166 11/2020 g CO2/km (comb)
2    \n\n5.3 10/2019 l/100 km (comb)
3    \n\n6.3 05/2022 l/100 km (comb)
4    \n\n128 07/2019 g CO2/km (comb)
5    \n\n112 06/2022 g CO2/km (comb)
6    \n\n5.8 01/2022 l/100 km (comb)
dtype: object



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression extracts ``two groups`` from each string in the pandas Series s.**
- The **``first group`` captures a **``sequence of digits``** representing the **``month``**, and 
- The **``second group``** captures a **``sequence of digits``** representing the **``year``**, matching the pattern that occurs after a non-whitespace sequence followed by whitespace.

In [271]:
# Extract month and year
extracted = s.str.extract(r"\S+\s(\d+)/(\d+)")

# Rename columns
extracted.columns = ['month', 'year']

# Display the result
extracted

month  year
0    06  2020
1    11  2020
2    10  2019
3    05  2022
4    07  2019
5    06  2022
6    01  2022


- **``\S+``**: This matches **``one or more non-whitespace characters``**. This would capture the initial part of the string (e.g., the fuel consumption value).
- **``\s``**: This matches a **``single whitespace character``**, which separates the initial part from the date.
- **``(\d+)``**: This captures **``one or more digits``** (the first group), which represents the **``month``**.
- **``/``**: This matches the **``literal slash``** character, **``separating``** the **``month``** from the **``year``**.
- **``(\d+)``**: This captures **``one or more digits``** (the second group), which represents the **``year``**.


<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


**The following expression extracts **``two groups of digits``** from each string in the pandas Series s.**
- The **``first group``** captures a **``sequence of digits``** (typically representing the **``month``**), and 
- The **``second group``** captures another **``sequence of digits``** (typically representing the **``year``**).

In [272]:
# Extract month and year

s.str.extract("(\d+)/(\d+)")

0     1
0  06  2020
1  11  2020
2  10  2019
3  05  2022
4  07  2019
5  06  2022
6  01  2022

- **``(\d+)``**: Captures the **``first group of digits``** (the month``**).
- **``/``**: Matches the **``literal character /``**.
- **``(\d+)``**: Captures the **``second group of digits``** (the year``**).

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>Example From PearDeck Slides:</strong></p>

**To ``extract an email address`` from the given text using regular expressions in Python, we can use the ``"re"`` module.**
- Here's a code example demonstrating how to do this:

In [273]:
# Define a string variable text with the value of "my email adress is example@gmail.com".

text = "my email adress is example@gmail.com"



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following regex pattern is designed to match email addresses in a given text string.**

In [275]:
# Search for the email address
reg = re.search("([a-zA-Z0-9_.+-]+)@([a-zA-Z0-9_.+-]+)\.([a-zA-Z0-9_.+-]+)", text)

print(reg.group())
print(reg.group(1))
print(reg.group(2))
print(reg.group(3))

example@gmail.com
example
gmail
com


- **``([a-zA-Z0-9_.+-]+)``**: This captures the **``local part``** of the email (before the @), allowing letters, digits, underscores, dots, pluses, and hyphens.
- **``@``**: This matches the @ symbol.
- **``([a-zA-Z0-9_.+-]+)``**: This captures the **``domain name``** (after the @ and before the dot).
- **``\.([a-zA-Z0-9_.+-]+)``**: This matches the dot (.) followed by the **``top-level domain (TLD)``**, capturing it as well.

**``The patterns captures:``**
- **``Group 0``**: The entire matched email address``**.
- **``Group 1``**: The **``local part``** (before the @).
- **``Group 2``**: The **``domain name``** (between the @ and the .).
- **``Group 3``**: The **``top-level domain``** (after the last .).

**``re.search scans through the string looking for the first location where the regex pattern produces a match.``**
- **``reg.group(0)``** prints the **``entire email address``**.
- **``reg.group(1)``** prints the **``local part``**.
- **``reg.group(2)``** prints the **``domain``**.
- **``reg.group(3)``** prints the **``top-level domain``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

### 🥴 weird_email:



In [276]:
# Define a weird email

text = "/er._%+-@42f.-.Ab/"



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [277]:
reg = re.search("/[\w._%+-]+@[\w.-]+\.[a-zA-Z]{2,4}/", text)

print(reg.group(0))

/er._%+-@42f.-.Ab/


**``Regex Breakdown:``**
- **``[\w._%+-]+``**: Captures the local part of the email (the part before the @). Matches one or more word characters, dots, underscores, percent signs, pluses, or hyphens in the local part of the email. It allows:
  - Letters (both uppercase and lowercase)
  - Digits
  - Special characters: _, ., +, -

- **``@``**: Matches the @ symbol, which separates the local part from the domain part.

- **``[\w.-]+``**: Captures the domain name (the part after the @ but before the .). Matches one or more word characters, dots, or hyphens in the domain name. It allows:
  - Letters (both uppercase and lowercase)
  - Digits
  - Special characters: _, ., +, -
- **``\.``**: Matches the literal . character (the dot before the top-level domain).
- **``\.[a-zA-Z]{2,4}``**: Captures the top-level domain (e.g., com, org, etc.). Matches a dot followed by 2 to 4 letters, which represents the top-level domain. It allows:
  - Letters (both uppercase and lowercase)
  - Digits
  - Special characters: _, ., +, -

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



<a id="5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#E51A59; font-size:150%; text-align:center; border-radius:10px 10px;">End of the Session - 11 (Part - 01)</p>

<p style="text-align: center;"><img src="https://i.ibb.co/TtRtYNn/healthy-lunch.jpg" width="800" height="200" class="img-fluid" alt="Lunch Time"></p>


<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>


<br><br><br>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="450" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>