<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>

<hr>

<a href="https://lms.clarusway.com/mod/lesson/view.php?id=2463&pageid=4531&startlastseen=no"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/2-DAwPY/DAwPy_S01_(Numpy_Arrays).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="90" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DAwPy_S1_%28Numpy_Arrays%29/DAwPy_S1_%28Numpy_Arrays%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="100" height="100" title="Open and Execute in nbviewer"></a><br/>

<hr>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="500" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="text-align: center;"><img src="https://i.ibb.co/XS0bxSH/best-bootcamps.png" width="300" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY_Courses"></p>

<img src=https://i.ibb.co/6gCsHd6/1200px-Pandas-logo-svg.png width="600" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Session - 05-06</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#E51A59; font-size:200%; text-align:center; border-radius:10px 10px;">Groupby & Useful Operations</p>

<a id="toc"></a>

## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [IMPORTING LIBRARIES NEEDED IN THIS NOTEBOOK](#0)
* [BASIC AGGREGATION METHODS](#1)
* [GROUPBY & AGGREGATION](#2)
    * [DataFrame.groupby()](#2.1)
* [DATAFRAME/SERIES OPERATIONS](#3)
    * [.aggregate()/agg()](#3.1)
        * [DataFrame.agg()](#3.1.1)
        * [DataFrame.groupby().agg()](#3.1.2)
    * [.filter()](#3.2)
        * [DataFrame.groupby().filter()](#3.2.1)
    * [.transform()](#3.3)
        * [DataFrame.groupby().transform()](#3.3.1)
    * [.apply()](#3.4)
        * [Series.apply() - df["col"].apply()](#3.4.1)
        * [DataFrame.apply()](#3.4.2)
    * [.applymap()](#3.5)
    * [.map()](#3.6)
        * [Series.map() - df["col"].map()](#3.6.1)
        * [DataFrame.map()](#3.6.2)
    * [df.transform() vs df.apply()](#3.7)
* [pivot() vs pivot_table()](#8)
* [.stack() & .unstack()](#9)
    * [.stack()](#9.1)
    * [.unstack()](#9.2)
* [THE END OF THE SESSION - 05 & 06](#10)

## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Importing Libraries Needed in This Notebook</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Once you've installed NumPy you can import it as a library:

In [138]:
import numpy as np
import pandas as pd
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")  # to suppress all warnings

- **``Importing Libraries``**: Make sure to import the required libraries before beginning your. You need both pandas and numpy.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

- ``import warnings``: This imports the warnings module, which is part of Python's standard library and provides a way to issue warning messages.
- ``warnings.filterwarnings("ignore")``: This function call tells Python to ignore all warning messages that would normally be printed. This can be useful when we want to focus on the output of your program without being distracted by warnings.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢 Caution ❗❗❗</strong></p>


- Ignoring warnings can sometimes hide important issues in our code, so use this approach judiciously. It's generally better to address the underlying causes of warnings rather than suppressing them.

## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Basic Aggregation Methods</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

One of the most basic analysis functions is **``grouping``** and **``aggregating data``**. In some cases, this level of analysis may be sufficient to answer real-world/business questions. In other instances, this activity might be the first step in a more complex data science analysis. In pandas, the **``groupby()``** function can be combined with one or more aggregation functions to quickly and easily summarize data. This concept is deceptively simple and most new pandas users will smootly understand this concept. However, they might be surprised at how useful complex aggregation functions can be for supporting sophisticated analysis [Source](https://pbpython.com/groupby-agg.html).

An essential piece of analysis of large data is efficient summarization: computing aggregations, such as **``sum()``**, **``mean()``**, **``median()``**, **``min()``**, and **``max()``**, in which a single number gives insight into the nature of a potentially large dataset. The **``aggregate()``** method allows you to apply a function or a list of function names to be executed along one of the axis of the DataFrame, default 0, which is the index (row) axis [Source](https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html).

Often when faced with a large amount of data, a first step is to compute summary statistics for the data in question. Perhaps the most common summary statistics are the mean and standard deviation, which allow you to summarize the "typical" values in a dataset, but other aggregates are useful as well (the sum, product, median, minimum and maximum, quantiles, etc.).

NumPy has fast built-in aggregation functions for working on arrays which are also used for Pandas Dataframes [Pandas Official Documentation](https://pandas.pydata.org/docs/reference/frame.html); we'll discuss and demonstrate some of them here:

* **``count()``** ==> Counts non-NA cells for each column or row.
* **``mean()``** ==> Returns the mean of the values over the requested axis.
* **``median()``** ==> Returns the median of the values over the requested axis.
* **``min()``** ==> Returns the minimum of the values over the requested axis.
* **``max()``** ==> Returns the maximum of the values over the requested axis.
* **``std()``** ==> Returns sample standard deviation over requested axis.
* **``var()``** ==> Returns unbiased variance over requested axis.
* **``sum()``** ==> Returns the sum of the values over the requested axis.
* **``idxmin()``** ==> Returns index of first occurrence of minimum over requested axis.
* **``idxmax()``** ==> Returns index of first occurrence of maximum over requested axis.
* **``corr()``** ==> Computes pairwise correlation of columns, excluding NA/null values.

To sum up, in this session, we'll explore aggregations in Pandas, from simple operations akin to what we've seen on NumPy arrays, to more sophisticated operations based on the concept of a groupby.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code generates a DataFrame using NumPy and pandas, with ``random integers`` and ``specific column names``.**

In [139]:
# Set random seed for reproducibility
np.random.seed(42)

# Create a DataFrame with random integers
df = pd.DataFrame(np.random.randint(0, 100, size=(7, 5)), 
                  columns=["x1", "x2", "x3", "x4", "x5"])

# Display the DataFrame
df

x1  x2  x3  x4  x5
0  51  92  14  71  60
1  20  82  86  74  74
2  87  99  23   2  21
3  52   1  87  29  37
4   1  63  59  20  32
5  75  57  21  88  48
6  90  58  41  91  59

**[The np.random.seed()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html)** function is part of the NumPy library in Python. It is used to set the random seed for the NumPy random number generator.

The random number generator in NumPy is a pseudorandom number generator, which means that it generates a sequence of numbers that appear to be random but are actually determined by a deterministic algorithm. By setting the random seed, you can ensure that the sequence of random numbers generated by NumPy is reproducible. In other words, if you set the same seed, you will get the same sequence of random numbers every time you run your program.

- **``np.random.seed()``** sets the random seed to 42 for reproducibility. It ensures that the random numbers generated will be the same each time the code is run.
- **``np.random.randint(0, 100, size=(7, 5))``** generates a 7x5 array of random integers between 0 (inclusive) and 100 (exclusive). The shape of the array is defined by size=(7, 5), meaning it will have 7 rows and 5 columns.
- **``pd.DataFrame(...)``** converts this 2D array into a pandas DataFrame with columns named "x1", "x2", "x3", "x4", and "x5".


<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code counts the number of non-null entries in each column of the DataFrame.**
- This method helps us understand how many valid (non-null) entries are present, which is useful for data cleaning and analysis.

In [140]:
# Count non-null entries in each column

df.count()

x1    7
x2    7
x3    7
x4    7
x5    7
dtype: int64

- Each value represents the count of non-null entries in the corresponding column of the DataFrame.
  - In this case, since all entries are random integers and there are NO null values, each column shows a count of 7 (the total number of rows).

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code counts the number of non-null entries specifically in the x1 column of the DataFrame.**
- This method is particularly useful when we want to check the validity of data in a specific column.

In [146]:
df['x1']

0    51
1    20
2    87
3    52
4     1
5    75
6    90
Name: x1, dtype: int32

In [145]:
# Count non-null entries in the 'x1' column

df['x1'].count()

7

- The output represents the number of non-null entries in the x1 column.
   - In this case, since all entries in the DataFrame are random integers and there are NO null values, the count will reflect the total number of rows in the DataFrame (7).

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code calculates the mean (average) of each numeric column in the DataFrame.**
- This method is useful for summarizing the central tendency of your data.



In [147]:
df

x1  x2  x3  x4  x5
0  51  92  14  71  60
1  20  82  86  74  74
2  87  99  23   2  21
3  52   1  87  29  37
4   1  63  59  20  32
5  75  57  21  88  48
6  90  58  41  91  59

In [150]:
# Calculate the mean of each column

df.mean()

x1    53.714286
x2    64.571429
x3    47.285714
x4    53.571429
x5    47.285714
dtype: float64

- Each value represents the mean of the corresponding column in the DataFrame.
  - For example, if x1 has a mean value of approximately 53.714286, it indicates that the average of all entries in the x1 column is around that number.

<img src=https://i.ibb.co/HGdvFt6/axis-direction.png width="400" height="200">

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code calculates the mean (average) of the values in the x2 column of the DataFrame.**
- In our case, the result of approximately 64.57142857142857 indicates the average value of the entries in that column.

In [151]:
# Calculate the mean of the 'x2' column

df.x2.mean()

64.57142857142857

- **``Mean Value``**: The output 64.57142857142857 represents the average of all entries in the x2 column.
- **``Interpretation``**: This means that if we were to add all the values in the x2 column and then divide by the number of entries, we would get approximately 64.57.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code calculates the median value of each numeric column in the DataFrame.**
- The median is the middle value when the data is sorted, and it provides a measure of central tendency that is less affected by outliers than the mean.

In [152]:
# Calculate the median of each column

df.median()

x1    52.0
x2    63.0
x3    41.0
x4    71.0
x5    48.0
dtype: float64

- Each value represents the median of the corresponding column in the DataFrame.
  - For example, if x1 has a median value of 52.0, this indicates that half of the values in the x1 column are below 52.0 and half are above.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code calculates the median value of the entries in the x3 column of the DataFrame.**
- In our case, the result of 41.0 indicates that when the values in the x3 column are sorted, the middle value is 41.0.

In [153]:
# Calculate the median of the 'x3' column

df.x3.median()

41.0

- **``Median Value``**: The output 41.0 represents the median of all entries in the x3 column.
- **``Interpretation``**: This means that half of the values in the x3 column are below 41.0, and half are above it. The median is a robust measure of central tendency, especially useful when the data has outliers.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code calculates the minimum value for each numeric column in the DataFrame.**
- This method is useful for quickly identifying the smallest value in our dataset.

In [154]:
# Calculate the minimum value of each column

df.min()

x1     1
x2     1
x3    14
x4     2
x5    21
dtype: int32

- Each value represents the minimum of the corresponding column in the DataFrame.
  - For example, x1 column has a minimum value of 1, that means 1 is the smallest value present in the x1 column.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code calculates the minimum value of the entries in the x4 column of the DataFrame.**
- This method is useful for finding the smallest value specifically in that column.

In [155]:
# Calculate the minimum value of the 'x4' column

df.x4.min()

2

- **``Minimum Value``**: The output will display the smallest value found in the x4 column.
  - For example, the output is 2, it indicates that 2 is the **``smallest entry``** in the **``x4 column``** of the DataFrame.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code returns the index (row labels) of the first occurrence of the minimum value for each numeric column in the DataFrame.**
- This is useful for identifying where the minimum values are located within the DataFrame.

In [157]:
df

x1  x2  x3  x4  x5
0  51  92  14  71  60
1  20  82  86  74  74
2  87  99  23   2  21
3  52   1  87  29  37
4   1  63  59  20  32
5  75  57  21  88  48
6  90  58  41  91  59

In [161]:
# Find the index of the minimum value in each column

df.idxmin()

# df.argmin()
# # Raises an error of "AttributeError: 'DataFrame' object has no attribute 'argmin'""

x1    4
x2    3
x3    0
x4    2
x5    2
dtype: int64

- Each value represents the index of the **``first occurrence of the minimum``** in the corresponding column.
  - For example, the output shows x1 has a minimum index of 1, it means that the smallest value in the x1 column is located at row index 1.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code returns the index (row label) of the first occurrence of the minimum value specifically in the x5 column of the DataFrame.**
- This method is useful for identifying the **``location of the smallest value``** in that particular column.

In [163]:
# Find the index of the minimum value in the 'x5' column

df.x5.idxmin()

# df.x5.argmin()

2

### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:100%; text-align:left;"><strong>📌 DON'T FORGET 🥴: dxmin() function returns index of first occurrence of minimum over requested axis. While finding the index of the minimum value across any index, all NA/null values are excluded.</strong></p>

- **``Index of Minimum Value``**: The output will display the index of the first occurrence of the minimum value found in the x5 column.
  - For example, the output is 1, it indicates that the **``smallest entry in the x5 column``** is **``located at row index 1``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code calculates the standard deviation for each numeric column in the DataFrame.**
- The standard deviation is a measure of the amount of variation or dispersion in a set of values.



In [164]:
# Calculate the standard deviation of each column

df.std()

x1    33.673502
x2    32.623392
x3    30.663302
x4    35.818325
x5    18.454577
dtype: float64

- Each value represents the standard deviation of the corresponding column in the DataFrame.
  - For example, if x1 has a standard deviation of approximately 27.52, this indicates a moderate level of dispersion in the values of the x1 column.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code calculates the standard deviation for the specified columns, x1 and x2, in the DataFrame.**
- This method allows us to focus on a subset of columns rather than computing the standard deviation for the entire DataFrame.

In [167]:
# Calculate the standard deviation for the 'x1' and 'x2' columns

df[["x1", "x2"]].std()

x1    33.673502
x2    32.623392
dtype: float64

- Each value represents the standard deviation of the corresponding column (x1 and x2) in the DataFrame.
  - For example, x1 has a standard deviation of approximately 33.059110, it indicates a moderate level of variability in the values of the x1 column.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code calculates the variance for each numeric column in the DataFrame.**
- Variance measures the spread of the data points around the mean, indicating how much the values differ from the average.

In [168]:
# Calculate the variance of each column

df.var()

x1    1133.904762
x2    1064.285714
x3     940.238095
x4    1282.952381
x5     340.571429
dtype: float64

- Each value represents the variance of the corresponding column in the DataFrame.
  - For example, x1 has a variance of approximately 1092.904762, it indicates a certain level of spread in the values of the x1 column around its mean.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code calculates the variance for the specified columns, x1 and x2, in the DataFrame.**
- This allows you to focus on the variability of just those two columns instead of the entire DataFrame.

In [169]:
# Calculate the variance for the 'x1' and 'x2' columns

df[["x1", "x2"]].var()

x1    1133.904762
x2    1064.285714
dtype: float64

- Each value represents the variance of the corresponding column (x1 and x2) in the DataFrame.
  - For example, x1 has a variance of approximately 1092.904762, it indicates the degree to which the values in the x1 column differ from their mean.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code calculates the sum of each column in the DataFrame.**
- The axis=0 parameter specifies that the operation should be performed along the rows, effectively summing each column.

In [170]:
df

x1  x2  x3  x4  x5
0  51  92  14  71  60
1  20  82  86  74  74
2  87  99  23   2  21
3  52   1  87  29  37
4   1  63  59  20  32
5  75  57  21  88  48
6  90  58  41  91  59

In [171]:
# Calculate the sum of each column

df.sum(axis=0)

x1    376
x2    452
x3    331
x4    375
x5    331
dtype: int64

- Each value represents the total sum of the corresponding column in the DataFrame.
  - For example, x1 has a sum of 324, it indicates that the values in the x1 column add up to 324.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code calculates the sum of each row in the DataFrame.**
- The axis=1 parameter specifies that the operation should be performed across the columns for each row, effectively summing the values horizontally.

In [172]:
# Calculate the sum of each row

df.sum(axis=1)

0    288
1    336
2    232
3    206
4    175
5    289
6    339
dtype: int64

- Each value represents the total sum of the corresponding row in the DataFrame.
  - For example, if first row has a sum of 200, it indicates that the values in that row add up to 200.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code calculates the sum of all values in the x1 column of the DataFrame.**
- This method allows us to quickly get the total for that specific column.

In [176]:
# Calculate the sum of the 'x1' column

df[["x1", "x2"]].sum()

x1    376
x2    452
dtype: int64

- The output will display the total sum of all entries in the x1 column.
  - For example, the output is 324, it indicates that the values in the x1 column add up to 324.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code provides a summary of the statistical properties of the numeric columns in a DataFrame.**
- It generates descriptive statistics, which include measures such as count, mean, standard deviation, minimum, maximum, and percentiles.

In [177]:
# Generate descriptive statistics

df.describe()

x1         x2         x3         x4         x5
count   7.000000   7.000000   7.000000   7.000000   7.000000
mean   53.714286  64.571429  47.285714  53.571429  47.285714
std    33.673502  32.623392  30.663302  35.818325  18.454577
min     1.000000   1.000000  14.000000   2.000000  21.000000
25%    35.500000  57.500000  22.000000  24.500000  34.500000
50%    52.000000  63.000000  41.000000  71.000000  48.000000
75%    81.000000  87.000000  72.500000  81.000000  59.500000
max    90.000000  99.000000  87.000000  91.000000  74.000000

- **``Count``**: Number of non-null entries in each column.
- **``Mean``**: Average value for each column.
- **``Standard Deviation (std)``**: Measure of the amount of variation or dispersion of the values.
- **``Min``**: Minimum value in each column.
- **``25% (1st Quartile)``**: Value below which 25% of the data fall.
- **``50% (Median)``**: Middle value that divides the data set in half.
- **``75% (3rd Quartile)``**: Value below which 75% of the data fall.
- **``Max``**: Maximum value in each column.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code generates the same descriptive statistics as df.describe(), but the .T method transposes the result.**
- This means that the rows and columns of the summary statistics are swapped, which can make it easier to read and interpret the statistics for each variable.

In [179]:
# df.describe().transpose()

# Generate descriptive statistics and transpose the result
df.describe().T

count       mean        std   min   25%   50%   75%   max
x1    7.0  53.714286  33.673502   1.0  35.5  52.0  81.0  90.0
x2    7.0  64.571429  32.623392   1.0  57.5  63.0  87.0  99.0
x3    7.0  47.285714  30.663302  14.0  22.0  41.0  72.5  87.0
x4    7.0  53.571429  35.818325   2.0  24.5  71.0  81.0  91.0
x5    7.0  47.285714  18.454577  21.0  34.5  48.0  59.5  74.0

- Each row corresponds to a column in the original DataFrame, and each column in the output corresponds to a statistical measure.
- This format can be helpful for quickly comparing statistics across different variables, as it lays out the information in a more compact and readable way.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Groupby & Aggregation</p>

<a id="2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In Exploratory Data Analysis (EDA), we often would like to analyze data by some categories. In SQL, the GROUP BY statement groups row that has the same category values into summary rows. In Pandas, SQL's GROUP BY operation is performed using the similarly named **``groupby()``** method. Pandas' groupby() allows us to split data into separate groups to perform computations for better analysis [Source](https://towardsdatascience.com/all-pandas-groupby-you-should-know-for-grouping-data-and-performing-operations-2a8ec1327b5).

In this part of the session, you'll learn the "group by" process (split-apply-combine) and how to use Pandas's groupby() function to group data and perform operations.

### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">DataFrame.groupby()</p>

<a id="2.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**``groupby()``** method groups DataFrame using a mapper or by a Series of columns. A groupby operation involves some combination of splitting the object, applying a function, and combining the results. This can be used to group large amounts of data and compute operations on these groups [Official Pandas Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html).

In other words, the **``groupby()``** method allows you to group rows of data together and call aggregate functions.

**SYNTAX:** <b>``DataFrame.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=NoDefault.no_default, observed=False, dropna=True)``</b>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code creates a dictionary with data related to employees in different companies and departments. This dictionary can be converted into a pandas DataFrame for further analysis.**

In [180]:
data = {'Company':['GOOG', 'GOOG', 'MSFT', 'MSFT', 'GOOG', 'MSFT', 'GOOG', 'MSFT'],
        'Department':['HR', 'IT', 'IT', 'HR', 'HR', 'IT', 'IT', 'HR'],
        'Person':['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah', 'Tom', 'Terry'],
        'Age':[30, 28, 35, 40, 42, 25, 32, 48],
        'Sales':[200, 120, 340, 124, 243, 350, 180, 220]}

- **``Company``**: The company where the employee works (GOOG or MSFT).
- **``Department``**: The department of the employee (HR or IT).
- **``Person``**: The name of the employee.
- **``Age``**: The age of the employee.
- **``Sales``**: The sales figure associated with the employee.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [181]:
# Create a DataFrame from the dictionary
df1 = pd.DataFrame(data)

# Display the DataFrame
df1

Company Department   Person  Age  Sales
0    GOOG         HR      Sam   30    200
1    GOOG         IT  Charlie   28    120
2    MSFT         IT      Amy   35    340
3    MSFT         HR  Vanessa   40    124
4    GOOG         HR     Carl   42    243
5    MSFT         IT    Sarah   25    350
6    GOOG         IT      Tom   32    180
7    MSFT         HR    Terry   48    220



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression creates a DataFrameGroupBy object.**
- This allows us to perform various aggregation functions or analysis on the grouped data, such as calculating sums, means, counts, etc.

In [182]:
# Group by 'Company' 

df1.groupby('Company')

The output <pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001FF30E25CC8> indicates that we have created a DataFrameGroupBy object using df1.groupby('Company'). This object is essentially a representation of the grouped data, but it does NOT display the grouped data itself until we perform some operations on it.

- **``How to Use the GroupBy Object?``**
  - To extract meaningful statistics from the grouped data, we typically follow the groupby() call with an aggregation function. Here are some common operations you can perform:
    - **``Aggregation``**: Calculate summary statistics like sum, mean, count, etc.
    - **``Iteration``**: Loop through the groups.
    - **``Transformation``**: Apply a function to each group and return a DataFrame with the same shape.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression calculates the mean (average) of numeric columns (like Age and Sales) for each group defined by the Company column in the DataFrame.**

In [183]:
# Group by 'Company' and calculate the mean of numeric columns

df1.groupby('Company').mean(numeric_only=True)

Age   Sales
Company              
GOOG     33.0  185.75
MSFT     37.0  258.50

The rows are indexed by the company names, with the mean values calculated for each numeric column.

- **``Age``**: The average age of employees in each company.
- **``Sales``**: The average sales figures for employees in each company.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression calculates the mean (average) sales for each company in the DataFrame.**
- This is a more specific way to focus on the Sales column after grouping by the Company column.

In [184]:
# Group by 'Company' and calculate the mean of the 'Sales' column

df1.groupby('Company')["Sales"].mean(numeric_only=True)

Company
GOOG    185.75
MSFT    258.50
Name: Sales, dtype: float64

The output is indexed by company names, showing the average sales figures calculated for each company.

- **``Mean Sales for GOOG``**: The average sales for employees at Google (GOOG).
- **``Mean Sales for MSFT``**: The average sales for employees at Microsoft (MSFT).


<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression calculates the mean (average) of the Sales column for each group defined by the Company column in the DataFrame.**
- By using double brackets, we are selecting Sales as a DataFrame, which maintains the DataFrame structure in the result.

In [185]:
# Group by 'Company' and calculate the mean of the 'Sales' column

df1.groupby('Company')[["Sales"]].mean(numeric_only=True)

Sales
Company        
GOOG     185.75
MSFT     258.50

The result is displayed as a DataFrame, maintaining the column structure, which can be useful for further operations or when merging with other DataFrames.

- **``Mean Sales for GOOG``**: The average sales for employees at Google (GOOG).
- **``Mean Sales for MSFT``**: The average sales for employees at Microsoft (MSFT).


<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression calculates the mean (average) of numeric columns for each combination of Company and Department in the DataFrame.**
- This is useful for analyzing how different departments within each company perform on average.

In [186]:
# Group by 'Company' and 'Department' and calculate the mean of numeric columns

df1.groupby(['Company', "Department"]).mean(numeric_only=True)

Age  Sales
Company Department             
GOOG    HR          36.0  221.5
        IT          30.0  150.0
MSFT    HR          44.0  172.0
        IT          30.0  345.0

The rows are multi-indexed by Company and Department, allowing for easy comparison across both categories.

- The output shows the average age and sales figures for each combination of Company and Department.
  - For example:
    - **``GOOG, HR``**: Average Age is 36.0 and Average Sales is approximately 221.5.
    - **``MSFT, IT``**: Average Age is 30.0 and Average Sales is approximately 345.0.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression calculates the mean (average) of the Sales column for each combination of Company and Department in the DataFrame.**
- By using double brackets, we are selecting Sales as a DataFrame, which maintains the DataFrame structure in the result.

In [187]:
# Group by 'Company' and 'Department' and calculate the mean of the 'Sales' column

df1.groupby(['Company', "Department"])[["Sales"]].mean(numeric_only=True)

Sales
Company Department       
GOOG    HR          221.5
        IT          150.0
MSFT    HR          172.0
        IT          345.0

The output is displayed as a DataFrame, maintaining the column structure.

- **``Sales``**: The average sales for each combination of Company and Department.
   - **``GOOG, HR``**: Average Sales is approximately 221.5.
   - **``MSFT, IT``**: Average Sales is approximately 345.0.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression generates descriptive statistics for the Sales column for each combination of Company and Department.**
- This provides a comprehensive summary, including count, mean, standard deviation, minimum, maximum, and percentiles.

In [188]:
# Group by 'Company' and 'Department' and calculate descriptive statistics for 'Sales'

df1.groupby(['Company', "Department"])[["Sales"]].describe()

Sales                                                  \
                   count   mean        std    min     25%    50%     75%   
Company Department                                                         
GOOG    HR           2.0  221.5  30.405592  200.0  210.75  221.5  232.25   
        IT           2.0  150.0  42.426407  120.0  135.00  150.0  165.00   
MSFT    HR           2.0  172.0  67.882251  124.0  148.00  172.0  196.00   
        IT           2.0  345.0   7.071068  340.0  342.50  345.0  347.50   

                           
                      max  
Company Department         
GOOG    HR          243.0  
        IT          180.0  
MSFT    HR          220.0  
        IT          350.0

The output provides several statistics for the Sales column:
Count: The number of entries in each group.
Mean: The average sales for each group.
Standard Deviation (std): The measure of the variation in sales.
Min: The minimum sales value.
25% (1st Quartile): The value below which 25% of the data fall.
50% (Median): The median sales value.
75% (3rd Quartile): The value below which 75% of the data fall.
Max: The maximum sales value.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



**Now we can use the ``.groupby()`` method to group rows together based on a column name.**
- For instance, let's group based on Company. This will create a DataFrameGroupBy object:**

In [189]:
df1.groupby('Company')

The output <pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001FF3339E3C8> indicates that you have created a DataFrameGroupBy object using df1.groupby('Company'). This object represents the grouping of the DataFrame df1 by the Company column, but it does not display the grouped data itself until you perform some operations on it.

- **``How to Use the GroupBy Object?``**
  - To extract meaningful statistics or perform operations on the grouped data, you typically follow the groupby() call with an aggregation function or other methods. Here are some common operations you can perform:

   - **``1. Aggregation``**: We can calculate summary statistics like mean, sum, count, etc. For example, to get the mean sales for each company:
   - **``2. Count of Employees in Each Company``**: We can count the number of entries for each company.
   - **``3. Iterating Through Groups``**: We can loop through each group and perform operations.
   - **``4. Descriptive Statistics``**: We can generate descriptive statistics for numeric columns.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression creates a DataFrameGroupBy object named by_comp that groups the DataFrame by the Company column.**
- This object can be used to perform a variety of operations on the grouped data, but it does NOT display any results until we apply a function to it.

In [190]:
# Save this object as a new variable

by_comp = df1.groupby('Company')



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression calculates the mean (average) for all numeric columns (like Age and Sales) in the DataFrameGroupBy object by_comp, which was created by grouping DataFrame by the Company column.**

In [191]:
# Calculate the mean of numeric columns by calling aggregate methods on the object/

by_comp.mean(numeric_only=True)

Age   Sales
Company              
GOOG     33.0  185.75
MSFT     37.0  258.50

The index is the company names, and the output DataFrame contains the mean values for each numeric column.

- **``Age``**: The average age of employees for each company.
- **``Sales``**: The average sales figures for employees in each company.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Useful Operations</p>

<a id="3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

- ### `.aggregate()`
- ### `.filter()`
- ### `.transform()`
- ### `.apply()`
- ### `.applymap()`
- ### `.map()`
- ### `.pivot() & .pivot_table()`
- ### `.stack() & .unstack()`

### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">.aggregate() / agg()</p>

<a id="3.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In pandas, when using the agg function, we can specify aggregation functions in different ways, such as using the function name directly (e.g., **``min``**) or as a string (e.g., **``"min"``**). Both approaches achieve the same result, but there are some nuances to be aware of.

**``Differences Between Using min and "min"``**
- **``Function vs. String:``**
  - **``Function (e.g., min)``**: When we pass the function directly, we're using a callable. This means we're passing the actual implementation of the function.
  - **``String (e.g., "min")``**: When we pass a string, pandas interprets it as a reference to the function name and looks it up internally.
- **``Flexibility:``**
  - Using a string can sometimes be more readable, especially when we're chaining multiple operations or using multiple aggregation functions. It also allows us to easily specify multiple functions in a list.
  - When we use the function directly, it can be more explicit, and we may have better autocompletion and error checking in some IDEs.
- **``Custom Functions:``**
  - If we're using a custom function, we must pass it directly as a callable (e.g., my_custom_function), since we can't reference it by name as a string.

#### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">DataFrame.agg()</p>

<a id="3.1.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**SYNTAX:** <b>``DataFrame.aggregate(func=None, axis=0, *args, **kwargs)``</b>

Returns: scalar, Series or DataFrame

The return can be:
- scalar : when Series.agg is called with single function
- Series : when DataFrame.agg is called with a single function
- DataFrame : when DataFrame.agg is called with several functions (Returns scalar, Series or DataFrame).

The aggregation operations are always performed over an axis, either the index (default) or the column axis. This behavior is different from numpy aggregation functions (mean, median, prod, sum, std, var), where the default is to compute the aggregation of the flattened array, e.g., numpy.mean(arr_2d) as opposed to numpy.mean(arr_2d, axis=0).

**agg()** is an **alias for aggregate()**. Use the alias [Official Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.aggregate.html).

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


In [192]:
# Create a DataFrame from the dictionary
df2 = pd.DataFrame({'groups': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
                    'var1': [10, 23, 33, 22, 11, 99, 76, 84, 45],
                    'var2': [100, 253, 333, 262, 111, 969, 405, 578, 760]})

# Display the DataFrame
df2

groups  var1  var2
0      A    10   100
1      B    23   253
2      C    33   333
3      A    22   262
4      B    11   111
5      C    99   969
6      A    76   405
7      B    84   578
8      C    45   760



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression applies the aggregation functions sum and min to each numeric column in the DataFrame.**
- This will compute both the total and the minimum for each numeric column (var1 and var2).

In [193]:
# Apply aggregation functions

df2.agg([sum, min])

groups  var1  var2
sum  ABCABCABC   403  3771
min          A    10   100

- **``sum``**: The total for each numeric column:
- **``var1``**: The sum is 403.
- **``var2``**: The sum is 3771.
- **``min``**: The minimum value for each numeric column:
- **``var1``**: The minimum is 10.
- **``var2``**: The minimum is 100.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression applies the aggregation functions sum and min to the columns var1 and var2 in the DataFrame.**
- This will compute both the total and the minimum for each of these columns.

In [195]:
df2

groups  var1  var2
0      A    10   100
1      B    23   253
2      C    33   333
3      A    22   262
4      B    11   111
5      C    99   969
6      A    76   405
7      B    84   578
8      C    45   760

In [194]:
# Apply aggregation functions to 'var1' and 'var2'

df2[["var1", "var2"]].agg([sum, min])

var1  var2
sum   403  3771
min    10   100

sum: The total for each numeric column:
var1: The sum is 403.
var2: The sum is 3771.
min: The minimum value for each numeric column:
var1: The minimum is 10.
var2: The minimum is 100.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression applies different aggregation functions to specified columns in the DataFrame.**
- Specifically, it calculates the sum for the var1 column and the minimum for the var2 column.

In [196]:
# Apply aggregation functions to 'var1' and 'var2'

df2.agg({"var1":sum, "var2":min})

var1    403
var2    100
dtype: int64

- **``var1``**: The sum of the var1 column is 403.
- **``var2``**: The minimum value of the var2 column is 100.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression applies specific aggregation functions to specified columns in the DataFrame, similar to the previous examples but structured to output results in a ``multi-level index format``.**

In [197]:
# Apply aggregation functions to 'var1' and 'var2'

df2.agg({"var1":[sum], "var2":[min]})

var1   var2
sum  403.0    NaN
min    NaN  100.0

The results are structured with a multi-level index, where the first level indicates the aggregation function (e.g., sum, min), and the second level indicates the variable name.

- **``var1``**: The sum of the var1 column is 403.
- **``var2``**: The minimum value of the var2 column is 100.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following expression apply ``multiple aggregation functions`` to the specified columns in the DataFrame.**
- In this case, we will compute the sum and mean for var1, and the minimum and maximum for var2.

In [198]:
# Apply aggregation functions to 'var1' and 'var2'

df2.agg({"var1":[sum, np.mean], "var2":["min", max]})

var1   var2
sum   403.000000    NaN
mean   44.777778    NaN
min          NaN  100.0
max          NaN  969.0

- **``var1``**:
  - **``sum``**: The total of var1 is 400.
  - **``mean``**: The average of var1 is approximately 44.44.
- **``var2``**:
  - **``min``**: The minimum value of var2 is 100.
  - **``max``**: The maximum value of var2 is 969.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## THIS IS WHERE WE LEFT



#### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">DataFrame.groupby().agg()</p>

<a id="3.1.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**``DataFrameGroupBy.agg(arg, *args, **kwargs)``**

Aggregates using one or more operations over the specified axis [Pandas Official Documentation](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.core.groupby.DataFrameGroupBy.agg.html).

[SOUREC01](https://www.shanelynn.ie/summarising-aggregation-and-grouping-data-in-python-pandas/) & [SOURCE02](https://www.analyticsvidhya.com/blog/2020/03/groupby-pandas-aggregating-data-python/)

<hr>

**The following expression groups the DataFrame by the groups column and then computes the minimum, median, and maximum for the numeric columns (var1 and var2) within each group.**

In [ ]:
# Group by 'groups' and calculate min, median, and max for numeric columns

df2.groupby('groups').aggregate([np.min, np.median, np.max])

- **``df2.groupby('groups')``**: This groups the DataFrame by the groups column, creating separate groups for 'A', 'B', and 'C'.
- **``.aggregate([np.min, np.median, np.max])``**: This applies the specified aggregation functions (minimum, median, and maximum) to each numeric column within the grouped data.
<hr>

📌 In pandas, **``amin``** and **``min``** are both functions used to ``determine the minimum value`` in a DataFrame or Series, but they differ in their behavior and usage.

- The **``min``** ``function in pandas`` is a method that can be ``called directly`` on a ``DataFrame`` or ``Series`` object. It returns the minimum value within the specified axis or across all axes by default.

- On the other hand, **``amin``** is a ``NumPy function`` that is accessible through pandas. It performs the same operation as ``min``, but it ``operates exclusively on the underlying NumPy array`` of the DataFrame or Series. This means that **``amin``** can be ``more efficient`` when working with ``large datasets``. 

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong>Multiple aggregate functions to all numeric columns in different format:</strong></p>

**The following command groups the DataFrame by the ``"groups"`` column and applies ``three (3) aggregation functions``: the ``minimum()``, ``median()``, and ``maximum()``. This allows you to compute these statistics for each numeric column (``"var1"`` and ``"var2"``) within each group.**

In [ ]:
# Group by 'groups' and calculate min, median, and max for numeric columns

df2.groupby('groups').agg([np.min, "median", max])


- **``df2.groupby('groups')``**: This groups the DataFrame by the groups column, separating the data into groups ``'A'``, ``'B'``, and ``'C'``.
- **``.agg([np.min, "median", max])``**: This applies the specified aggregation functions:
  - **``np.min``**: Computes the minimum value.
  - **``"median"``**: Computes the median value.
  - **``max``**: Computes the maximum value.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command attempts to apply ``multiple aggregation functions`` to the ``"var1"`` column and a ``single aggregation function`` to the ``"var2"`` column after grouping the DataFrame by the ``"groups"`` column.**
- However, the ``syntax for specifying multiple functions`` for a single column in this context is ``NOT correct and recommended``; nevertheless, it works.**

In [ ]:
# Group by 'groups' and apply multiple aggregations to 'var1' and median to 'var2'

df2.groupby('groups').agg({'var1':(min, 'max'), 'var2':'median'})

# (CORRECT SYNTAX)
# df2.groupby('groups').agg({'var1': [min, max], 'var2': 'median'})

- **``var1``**:
  - **``min``**: The minimum value of var1 for each group.
  - **``max``**: The maximum value of var1 for each group.
- **``var2``**:
  - **``median``**: The median value of var2 for each group.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong>Multiple aggregate functions to single numeric column in different format:</strong></p>

**The following command groups the DataFrame by the ``"groups"`` column and then computes the ``minimum`` and ``maximum`` values for the ``"var1"`` column within each group.**
- The result will be a DataFrame displaying these statistics for each group.

In [ ]:
# Group by 'groups' and apply multiple aggregations (min, max) to 'var1'

df2.groupby('groups')["var1"].agg([min, 'max'])

- **``df2.groupby('groups')``**: Groups the DataFrame by the groups column, creating separate groups for 'A', 'B', and 'C'.
- **``["var1"]``**: Selects the var1 column for aggregation.
- **``.agg([min, 'max'])``**: Applies the min and max functions to the selected var1 column.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command groups the DataFrame by the ``"groups"`` column and then computes both the ``minimum`` and ``maximum`` values for the ``"var1"`` and ``"var2"`` columns within each group.**
- The result will be a DataFrame displaying these statistics for each group.

In [ ]:
# Group by 'groups' and apply min and max functions to 'var1' and 'var2'

df2.groupby('groups')[["var1","var2"]].agg([min, 'max'])

- **``df2.groupby('groups')``**: This groups the DataFrame by the groups column, which contains categories ``'A'``, ``'B'``, and ``'C'``.
- **``[["var1", "var2"]]``**: This selects the ``"var1"`` and ``"var2"`` columns for aggregation.
- **``.agg([min, max])``**: This applies both the ``min()`` and ``max()`` functions to the selected columns.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">.filter()</p>

<a id="3.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

#### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">DataFrame.filter()</p>

<a id="3.2.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Pandas **``Dataframe.filter()``** is an inbuilt function that is used to subset columns or rows of DataFrame according to labels in the particular index. The DataFrame **``filter()``** returns subset the DataFrame rows or columns according to the detailed index labels. **One thing to note that** this routine does **NOT** filter a DataFrame on its contents. The filter() function is applied to the labels of the index [Pandas Official Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.filter.html)

[SOUREC01](https://www.sharpsightlabs.com/blog/pandas-filter/) & [SOURCE02](https://appdividend.com/2020/03/19/pandas-filter-pandas-dataframe-filter-in-python-example/)

In [ ]:
# Display the DataFrame

df2

- **``groups``**: A categorical column with values 'A', 'B', and 'C'.
- **``var1``**: A numeric column containing integer values.
- **``var2``**: Another numeric column containing integer values.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``selects specific columns`` from the DataFrame.**
- This will ``return a new DataFrame`` containing ``only the specified columns``: ``"groups"`` and ``"var1"``.

In [ ]:
# Filter the DataFrame to include only 'groups' and 'var1'

df2.filter(["groups", "var1"])

# df2[["groups", "var1"]]  # gives the same output


### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:100%; text-align:left;"><strong>📌 DON'T FORGET 🥴: The filter() method in pandas is primarily used for filtering rows or columns based on specific conditions.</strong></p>

- **``Understanding filter:``**
  - **``Filtering Rows:``**
    - You can use filter to select rows based on a condition in the DataFrame's index.
  - **``Filtering Columns:``**
    - You can use filter to select columns based on their labels or a condition on their labels.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``selects columns`` from the DataFrame that ``match a specific regular expression pattern``.**
- In our case, it selects all columns whose names start with ``"var"``.

In [ ]:
# Filter the DataFrame to include only columns that end with 'var1'

df2.filter(regex="^var", axis=1)

- **``df2``**: Refers to the DataFrame you have created.
- **``.filter(regex="^var", axis=1)``**:
  - **``regex="^var"``**: This regular expression matches any column name that starts with "var". 
    -  The ``^`` symbol denotes the beggining of the string.
  - **``regex="ar1$"``**: This regular expression matches any column name that ends with "ar1". 
    - The ``$`` symbol denotes the end of the string.
  - **``axis=1``**: Specifies that the filtering should be applied to columns (as opposed to rows).

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``selects columns`` from the DataFrame that ``contain the substring "var" in their names``.**
- This method is useful for ``filtering columns based on partial matches``.

In [ ]:
# The "like" parameter enables us to identify items that contain a certain string.

# Filter the DataFrame to include only columns that contain 'var'
df2.filter(like="var", axis=1)

- **``df2``**: Refers to the DataFrame you have created.
- **``.filter(like="var", axis=1)``**:
  - **``like="var"``**: This specifies that any **``column name``** containing the substring "var" should be included.
  - **``axis=1``**: Indicates that the filtering should be applied to columns.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``selects rows`` from the DataFrame that ``contain the substring "1" in their index labels``.**
- This command is useful for ``filtering rows`` based on ``partial matches in the index``.

In [ ]:
# Filter the DataFrame to include "only rows" with '1' in the index

df2.filter(like="1", axis=0)

- **``df2``**: Refers to the DataFrame you created earlier.
- **``.filter(like="1", axis=0)``**:
  - **``like="1"``**: This specifies that any **``row index label``** containing the substring "1" should be included.
  - **``axis=0``**: Indicates that the filtering should be applied to rows.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



#### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">DataFrame.groupby().filter()</p>

<a id="3.2.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**SYNTAX:** <b>``DataFrameGroupBy.filter(func, dropna=True, *args, **kwargs)``</b>
    
    
- Returns a copy of a DataFrame excluding filtered elements.
- Elements from groups are filtered if they do not satisfy the boolean criterion specified by func [Official Pandas Document](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.filter.html).

In [ ]:
# Retrieve unique values from the 'groups' column

df2.groups.unique()



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong>Example-1 (User Defined Function-DEF):</strong></p>

**The following command is used to ``group the DataFrame`` by the ``"groups"`` column and then ``calculate the mean`` of the numeric columns (``"var1"`` and ``"var2"``) for each group.**
- This provides a ``summary of the average values`` for those columns within each category.**

**Example-1**

In [ ]:
# Group by 'groups' and calculate the mean for var1 and var2

df2.groupby("groups").mean()

- **``df2.groupby("groups")``**: Groups the DataFrame by the groups column, resulting in separate groups for 'A', 'B', and 'C'.
- **``.mean()``**: Calculates the mean (average) for each numeric column within each group.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following function ``filter_func(x)`` is designed to be used as a filtering function, typically in the context of a group operation.**
- It checks ``whether the mean of the ``"var1"`` column for a given group exceeds 39``.

In [ ]:
# Define a User Defined filter function

def filter_func(x):
    return x["var1"].mean() > 39

- **``x``**: Represents a subset of the DataFrame, typically a group of rows corresponding to a specific category in the groups column.
- **``x["var1"].mean()``**: Calculates the mean of the var1 column for that subset.
- **``> 39``**: The function returns True if the mean is greater than 39, and False otherwise.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command filters ``"groups"`` column in the DataFrame based on the condition defined in the ``filter_func``. This function checks ``whether the mean of the ``"var1"`` column for each group exceeds a specified value (in our case, 39).**

In [ ]:
# Returns the rows that meet the condition, as a DataFrame


df2.groupby('groups').filter(filter_func)

The result ``retains only those groups`` that ``meet the condition`` defined in filter_func: 
- **``Group A``**: The mean of ``"var1"`` is (10 + 22 + 76) / 3 = ``36``, which is not greater than 39. **``NOT SHOWN``**
- **``Group B``**: The mean of ``"var1"`` is (23 + 11 + 84) / 3 = ``39.33``, which is greater than 39.
- **``Group C``**: The mean of ``"var1"`` is (33 + 99 + 45) / 3 = ``59``, which is greater than 39.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong>Example-2 (Lambda Function):</strong></p>

**The following command groups the DataFrame by the ``"groups"`` column and calculates the sum for each numeric column ("``var1"`` and ``"var2"``) within those groups.**
- This operation provides a summary of total values for each group.

In [ ]:
# Group by 'groups' and calculate the "sum" for "var1" and "var2"

df2.groupby("groups").sum()

- **``Group A:``**
  - **``var1``**: 10+22+76=``108``
  - **``var2``**: 100+262+405=``767``
- **``Group B:``**
  - **``var1``**: 23+11+84=``118``
  - **``var2``**: 253+111+578=``942``
- **``Group C:``**
  - **``var1``**: 33+99+45=``177``
  - **``var2``**: 333+969+760=``2062``

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command filters ``"groups"`` column in the DataFrame based on the condition that the sum of the ``"var2"`` column for each group is less than 800.**
- This allows you to retain only those groups that meet this criterion.

In [ ]:
# Filter "groups" where the sum of "var2" is less than 800

df2.groupby('groups').filter(lambda x : x['var2'].sum() < 800)

- **``Group A:``**
  - **``Sum of var2``**: 100+262+405=767 (``meets the condition``)
- **``Group B``**:
  - **``Sum of var2``**: 253+111+578=942 (does NOT meet the condition)
- **``Group C``**:
  - **``Sum of var2``**: 333+969+760=2062 (does NOT meet the condition)

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">.transform()</p>

<a id="3.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

#### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">DataFrame.transform()</p>

<a id="3.3.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**SYNTAX:** <b>``DataFrame.transform(func, axis=0, *args, **kwargs)``</b>

- Returns DataFrame
- Call func on self producing a DataFrame that must have the same length as self.

Python’s Transform function returns a self-produced dataframe with transformed values after applying the function specified in its parameter. This dataframe has the same length as the passed dataframe. **``transform()``** is an operation mostly used in conjunction with groupby (which is one of the most useful operations in pandas). It is a powerful function that you can lean on for **feature engineering** in Python. As the name (feature engineering) suggests, it enables us to extract new features from existing ones. Let’s understand the importance of the transform function with the help of an example. 

[SOUREC01](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.transform.html) & [SOURCE02](https://www.analyticsvidhya.com/blog/2020/03/understanding-transform-function-python/)

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


**The following command ``selects specific columns`` from the DataFrame using ``integer-based indexing``. This will create a new DataFrame ``df_num`` containing only the columns located at ``index positions`` ``1`` and ``2``.**

In [ ]:
# Select columns using iloc and assign it to an object named "df_num"
df_num = df2.iloc[:, 1:3]

# Display the selected rows
df_num

- **``df2``**: Refers to the original DataFrame.
- **``iloc``**: This is used for integer-location based indexing.
- **``[:, 1:3]``**:
  - **``The colon (:)``** indicates that we want all rows.
  - **``1:3``** specifies the columns to select: column index 1 (inclusive) to column index 3 (exclusive). This means columns 1 and 2 will be selected.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The command ``applies a transformation`` to the DataFrame df_num, ``where each element in df_num is increased by 10``. This is done using the transform method, which allows you to apply a function to each column (or row) of the DataFrame.**

In [ ]:
# Apply the transformation
df_num.transform(lambda x : x+10)

# df_num+10  # gives the same result

- **``df_num``**: Refers to the DataFrame containing the selected columns (e.g., var1 and var2).
- **``.transform(lambda x: x + 10)``**:
  - This applies a lambda function to each column in df_num.
  - The lambda function takes each element x and adds 10 to it.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:120%; text-align:left;"><strong>📌📢 Rather than simple calculations, we should use transform() method for more sophisticated/complicated ones in feature engineering:</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong>Transformation to all columns in the DataFrame:</strong></p>

**The following command ``standardizes the columns`` in the DataFrame df_num.**
- This process transforms each column to have a mean of 0 and a standard deviation of 1, which is commonly referred to as z-score normalization.**
  - score is is z = (x-μ)/σ, where x is the raw score, μ is the population mean, and σ is the population standard deviation.

In [ ]:
# Apply the transformation for standardization

df_num.transform(lambda x: (x-x.mean()) / x.std())

# This is the dataframe we get after applying Transform function:

- **``df_num``**: Refers to the DataFrame containing the selected numeric columns (e.g., var1 and var2).
- **``.transform(lambda x: (x - x.mean()) / x.std())``**:
  - **``x - x.mean()``**: Subtracts the mean of the column from ``each element in that column``.
  - **``/ x.std()``**: Divides the result by the standard deviation of the column.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``standardizes`` the ``"var1"`` column of the DataFrame df_num.**
- This transformation scales the values so that they have a mean of 0 and a standard deviation of 1.

In [ ]:
# Apply lambda function to the "var1" column via transfom() method

df_num["var1"].transform(lambda x: (x-x.mean()) / x.std())

- **``df_num.var1``**: Refers specifically to the var1 column in the df_num DataFrame.
- **``.transform(lambda x: (x - x.mean()) / x.std())``**:
  - **``x - x.mean()``**: Subtracts the mean of the ``"var1"`` column from each value in that column.
  - **``/ x.std()``**: Divides the result by the standard deviation of the ``"var1"`` column.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``applies the square root transformation to each value`` in the ``"var1"`` column of the DataFrame df_num.**
- This transformation is useful for reducing skewness in data, especially when dealing with non-negative values.

In [ ]:
# Apply square root transformation to the "var1" column via a single Numpy method
df_num["var1"].transform(np.sqrt)

# np.sqrt(df_num.var1)      # gives the same result
# df_num.var1.agg(np.sqrt)  # gives the same result

- **``df_num.var1``**: Refers specifically to the var1 column in the df_num DataFrame.
- **``.transform(np.sqrt)``**:
  - This applies the square root function from the NumPy library (np.sqrt) to each element in the var1 column.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong>Multiple transformation to a single column:</strong></p>

**The following command applies ``multiple transformations`` to the ``"var1"`` column of the DataFrame df_num.**
- In our case, it applies both the square root and the exponential functions to each element in the ``"var1"`` column.

In [ ]:
# Apply multiple transformations to the var1 column via multiple Numpy methods
df_num["var1"].transform([np.sqrt, np.exp])

# df_num.var1.agg([np.sqrt, np.exp])  # gives the same result

As seen above, transform comes in handy during feature extraction. As the name suggests, it enables us to extract new features from existing ones.


- **``df_num.var1``**: Refers specifically to the var1 column in the df_num DataFrame.
- **``.transform([np.sqrt, np.exp])``**:
  - This applies both the square root function (np.sqrt) and the exponential function (np.exp) to the var1 column.
  - The result will have a MultiIndex, with the first level indicating the transformation applied.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



#### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">DataFrame.groupby().transform()</p>

<a id="3.3.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**SYNTAX:** <b>``DataFrameGroupBy.transform(func, *args, engine=None, engine_kwargs=None, **kwargs)``</b>

- Call function producing a like-indexed DataFrame on each group and return a DataFrame having the same indexes as the original object filled with the transformed values. [Official Pandas Document](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.transform.html).

In [ ]:
# Let's remember our DataFrame

df2



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command calculates the mean (average) of the ``"var1"`` column for ``each group`` in the ``"groups"`` column of the DataFrame.**
- This operation groups the data by unique values in the groups column and computes the mean for the corresponding ``"var1"`` values.

In [ ]:
# Calculate the mean of "var1" for each group

df2.groupby("groups")["var1"].mean()

- **``Group A``**: The mean of ``"var1"`` is (10 + 22 + 76) / 3 = ``36``.
- **``Group B``**: The mean of ``"var1"`` is (23 + 11 + 84) / 3 = approximately ``39.33``.
- **``Group C``**: The mean of ``"var1"`` is (33 + 99 + 45) / 3 = ``59``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``calculates the mean`` of the ``"var1"`` column for ``each group`` defined in the ``"groups"`` column of the DataFrame.** 
- It then returns a Series where each entry corresponds to the mean of its respective group, maintaining the original DataFrame's index.**

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📌💡🤔💭 Focus on the length of the results and compare the following with the one above❗❗❗</strong></p>

In [ ]:
# Apply transform() method to calculate the mean of "var1" for each group

df2.groupby("groups")["var1"].transform("mean")

The two commands serve similar purposes but produce different outputs.
- **``1st Output``**: Returns a Series where the index consists of the unique groups, and the values are the mean of ``"var1"`` for each group.
  - Useful for summarizing data and obtaining a quick overview of the means for each group.
  - Best when you are interested in aggregating information and do not need to maintain the original DataFrame's structure.
- **``2nd Output``**: Rreturns a Series of the ``same length as the original DataFrame``, where each entry in the Series is replaced by the mean of its corresponding group.
  - Useful when you want to perform further calculations or comparisons that require the original DataFrame's shape.
  - The transform method can be less efficient for very large DataFrames because it computes the mean for each group and then broadcasts it back to match the original DataFrame's index.

<hr>

- **``Group A``**: The mean of var1 for group A is 36.0 (calculated from 10, 22, 76).
- **``Group B``**: The mean for group B is approximately 39.33 (calculated from 23, 11, 84).
- **``Group C``**: The mean for group C is 59.0 (calculated from 33, 99, 45).

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``adds a new column`` to the DataFrame df2 that contains the mean of the ``"var1"`` column for each group defined in the groups column.** 
- Each entry in this new column corresponds to the mean of the group to which that row belongs.

In [ ]:
df2.groupby("groups")["var1"].mean()

In [ ]:
# Add a new column with the "mean" of "var1" for each group
df2["var1_mean_transform"] = df2.groupby("groups")["var1"].transform("mean")

# Display the modified DataFrame
df2

By using the command above to create the ``"var1_mean_transform"`` column, we provide a way to compare individual ``"var1"`` values against their group means.

- **``df2.groupby("groups")["var1"]``**: This groups the DataFrame by the groups column and selects the ``"var1"`` column.
- **``.transform("mean")``**: Calculates the mean for each group and returns a Series where each value is the mean of the group that the corresponding row belongs to.
- **``df2["var1_mean_transform"] = ...``**: This assigns the resulting Series to a new column named var1_mean_transform in the original DataFrame.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code ``adds a new column to the DataFrame`` that contains the median of the ``"var2"`` column for each group defined in the groups column.**
- Each entry in this new column corresponds to the median of the group to which that row belongs.

In [ ]:
df2.groupby("groups")["var2"].median()

In [ ]:
# Add a new column with the "median" of "var2" for each group
df2["var2_median_transform"] = df2.groupby("groups")["var2"].transform("median")

# Display the modified DataFrame
df2

By using the command above to create the ``"var2_median_transform"`` column, we provide a way to compare individual ``"var2"`` values against their group medians,
- **``df2.groupby("groups")``**: This groups the DataFrame by the unique values in the groups column.
- **``["var2"].transform("median")``**: This selects the ``"var2"`` column and calculates the median for each group. The transform method ensures that the result maintains the same index as the original DataFrame, so each entry corresponds to the median of its respective group.
- **``df2["var2_median_transform"] = ...``**: This assigns the resulting Series to a new column named var2_median_transform in the original DataFrame.
<hr>

- **``For Group A``**: The median of var2 is ``262.0`` (the middle value of 100, 262, and 405).
- **``For Group B``**: The median of var2 is ``253.0`` (the middle value of 111, 253, and 578).
- **``For Group C``**: The median of var2 is ``333.0`` (the middle value of 333, 969, and 760).

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">.apply()</p>

<a id="3.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

One alternative to using a loop to iterate over a DataFrame is to use the pandas **``.apply()``** method. This function acts as a **``map()``** function in Python. It takes a function as an input and applies this function to an entire DataFrame. **apply()** is used to apply a function along an axis of the DataFrame or on values of Series. In other words, ``Pandas.apply()``** allow the users to pass a function and apply it on **every single value** of the Pandas series. This function does **NOT** make changes to the original DataFrame object.

[SOUREC01](https://www.geeksforgeeks.org/python-pandas-apply/), [SOURCE02](https://www.datacamp.com/community/tutorials/pandas-apply) & [SOURCE03](https://sparkbyexamples.com/pandas/pandas-apply-function-usage-examples/)

#### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Series.apply() - df["col"].apply()</p>

<a id="3.4.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**SYNTAX:** <b>``Series.apply(func, convert_dtype=True, args=(), **kwargs)``</b>

- Invoke function on values of Series.
- Can be ufunc (a NumPy function that applies to the entire Series) or a Python function that only works on single values.. [Official Pandas Document](https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.Series.apply.html).

In [ ]:
# Create a new DataFrame
df3 = pd.DataFrame({'col1':[1, 2, 3, 4],
                    'col2':[444, 555, 666, 444],
                    'col3':['abc', 'def', 'ghi', 'xyz']})

# Display the DataFrame
df3

- **``col1``**: Contains integer values from 1 to 4.
- **``col2``**: Contains integer values including duplicates: 444, 555, 666, and another 444.
- **``col3``**: Contains string values: 'abc', 'def', 'ghi', and 'xyz'.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following function takes an input ``x`` and returns its square.**

In [ ]:
# Define a User Defined Function

def squared(x):
    return x**2



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command applies the ``squared`` function to ``each element`` in the ``"col1"`` column of the DataFrame.**
- This will compute the square of each value in that column.

In [ ]:
# Apply the "squared" function to "col1"

df3['col1'].apply(squared)



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command applies the ``natural logarithm`` function from the NumPy library to ``each element`` in the ``"col2"`` column of the DataFrame.**
- This will compute the natural logarithm (base e) of each value in that column.

In [ ]:
# Apply the "natural logarithm" function to "col2"

df3['col2'].apply(np.log)



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command applies the ``built-in`` ``len()`` function to ``each element`` in the ``"col3"`` column of the DataFrame.**
- This will compute the length of each string in that column.

In [ ]:
# Apply the built-in "len" function to "col3"

df3['col3'].apply(len)



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command applies a ``lambda`` function to ``each element`` in the ``"col3"`` column of the DataFrame.**
- This specific lambda function multiplies each string in ``col3`` by 3, effectively repeating each string three times.

In [ ]:
# Apply the "lambda" function to "col3"

df3['col3'].apply(lambda x: x * 3)

When we apply the lambda function lambda x: x * 3 to the col3 column of the DataFrame df3, we're attempting to multiply each string value by 3. In Python, multiplying a string by an integer results in the string being repeated that number of times.

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:120%; text-align:left;"><strong>📌💡🔥 BE CAREFUL while creating a new feature using groupby() and apply() methods together ❗❗❗</strong></p>


<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong>Feature Engineering by apply() method:</strong></p>

**The following command applies a ``lambda`` function to ``each element`` in the ``"col2"`` column of the DataFrame.**
- This function categorizes each value in ``"col2"`` as;
  - **``"high"``** if it is **``greater than 500``**, and 
  - **``"low"``** **``otherwise``**.

In [ ]:
# Apply the "lambda" function to "col2"

df3['col2'].apply(lambda x: "high" if x > 500 else "low")

- **``col2_category``**: This new column contains categorical values based on the condition applied:
  - Values in ``"col2"`` that are ``less than or equal to 500`` are labeled as ``"low"``.
  - Values ``greater than 500`` are labeled as ``"high"``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



#### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">DataFrame.apply()</p>

<a id="3.4.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**SYNTAX:** <b>``DataFrame.apply(func, axis=0, raw=False, result_type=None, args=(), **kwargs)``</b>
- Returns Series or DataFrame
- Result of applying function along the given axis of the DataFrame. [Official Pandas Document](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html).

In [ ]:
# Display the DataFrame

df2



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code removes specific columns from the DataFrame.** 

In [ ]:
# Drop the specified columns
df2.drop(["var1_mean_transform", "var2_median_transform"], axis=1, inplace=True)

# Display the modified DataFrame
df2

- **``df2.drop(...)``**: This is the method used to drop specified labels from a DataFrame.
- **``["var1_mean_transform", "var2_median_transform"]``**: This list specifies the columns we want to drop from the DataFrame. In our case, it includes:
  - var1_mean_transform
  - var2_median_transform
- **``axis=1``**: This argument specifies that we want to drop columns (as opposed to rows, which would be axis=0).
- **``inplace=True``**: This argument modifies the original DataFrame directly, meaning that df2 will be updated without needing to assign the result to a new variable.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command applies the ``np.sum`` function from the NumPy library to ``each column`` of the DataFrame.**
- This will calculate the sum of each column, returning a Series with the sum of each column's values.

In [ ]:
# sum() functions works with putting + sign between each element of an iterable object

# Apply np.sum to calculate the sum of each column
df2.apply(np.sum)

- **``groups``**: The values are concatenated because ``np.sum`` operates on ``strings`` by ``concatenation``.
- **``var1``**: The sum of the values in var1 is 10+23+33+22+11+99=``198``.
- **``var2``**: The sum of the values in var2 is 100+253+333+262+111+969=``1978``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [ ]:
# It gives an error due to the non-numeric column : "groups"

# df2.apply(np.sum, axis=1)

**🤔💭 Why does it give an error❓**

- When we use the command ``df2.apply(np.sum, axis=1)``, it ``attempts to calculate`` the ``sum for each row across all columns`` in the DataFrame. 
 - The error occurs because ``one of the columns``, **``"groups"``**, contains **``non-numeric data (strings)``**. The np.sum function expects numeric input to perform the summation, and it **``CANNOT sum string values``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**Let's remember of df named "df_num" containing only numerical values:**

In [ ]:
# Display the DataFrame

df_num



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``computes the sum of each column`` in a DataFrame named, which is expected to contain ``only numeric data``.**
- The np.sum function from the NumPy library will be applied to each column, returning a Series with the sum of the values for each column.

In [ ]:
# Apply np.sum to calculate the sum of each "column", vertically
df_num.apply(np.sum)

# df_num.sum()  # This will give the same result. So there is no need to use apply() for simple calculations as well.

- **``var1``**: The sum is 10+23+33+22+11+99+76+84+45=``403``.
- **``var2``**: The sum is 100+253+333+262+111+969+405+578+760=``3771``.
- **``var3``**: The sum is 5+5+5=``15``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``calculates the sum of each row across all columns`` in the DataFrame.**

In [ ]:
# Apply np.sum to calculate the sum of each "row", horizontally

df_num.apply(np.sum, axis=1)

# df_num.sum(axis=1)  # This will give the same result. So there is no need to use apply() for simple calculations as well.

- **``Row 0``**: 10+100=110
- **``Row 1``**:23+253=276
- **``Row 2``**: 33+333=366
and so on

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command applies a ``lambda`` function to ``each element`` in the DataFrame, ``adding 10 to each numeric value`` in the DataFrame.**

In [ ]:
# Apply the "lambda" function to "add 10" to each element

df_num.apply(lambda x : x + 10)

- Each value in the original DataFrame has been incremented by 10.
  - For example, the original value ``10`` in ``"var1"`` becomes ``20``, and ``100`` in ``"var2"`` becomes ``110``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command calculates the ``mean (average) of numeric columns`` in the DataFrame, ``grouped by the values`` in the ``"groups"` column.**
- This operation will return a ``new DataFrame`` that shows the mean for each group.

In [ ]:

df2.groupby("groups").mean()

- **``Group A:``**
  - **``Mean of var1``**: (10+22+76)/2=``36.0``
  - **``Mean of var2``**: (100+262+405)/2=``255.666667``
- **``Group B:``**
  - **``Mean of var1``**: (23+11+84)/2=``39.333333``
  - **``Mean of var2``**: (253+111+578)/2=``314.000000``
- **``Group C:``**
  - **``Mean of var1``**: (10+99+45)/2=``59.0``
  - **``Mean of var2``**: (33+969+760)/2=``687.333333``

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📌💡🤔💭 WATCH OUT ❗❗❗ Look over what happens in the following example:</strong></p>

**The following command groups the DataFrame by the ``"groups"`` column and then applies the ``np.mean`` function to each group.**
- This operation computes the mean for each numeric column within each group and returns a new DataFrame.

In [ ]:
# Group by 'groups' and calculate the "mean" of 'var1' using np.mean
display(df2.groupby('groups').apply(np.mean))

display((10+100+22+262+76+405)/6)   # = 145.833334
display((23+253+11+111+84+578)/6)   # = 176.666667
display((33+333+99+969+45+760)/6)   # = 145.666667

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


**The following command groups the DataFrame by the ``"groups"`` column and then applies the ``np.mean`` function specifically to the ``"var1"`` column within each group.**
- This operation returns the ``mean`` of ``"var1"`` for ``each group``.

In [ ]:
# Group by 'groups' and calculate the "mean" of 'var1'

df2.groupby('groups')[["var1"]].apply(np.mean)

The result allows you to focus specifically on a ``single column`` when calculating group-wise statistics. 

- **``Group A:``**
  - **``Mean of "var1"``**: (10+22+76)/2=``36.0``
- **``Group B:``**
  - **``Mean of "var1"``**: (23+11+84)/2=``39.333333``
- **``Group C:``**
  - **``Mean of "var1"``**: (10+99+45)/2=``59.0``
  
<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong>Let's do it with transform to see/remember the difference in the output:</strong></p>

**The command computes the ``mean`` of ``each numeric column`` within ``each group`` defined by the ``"groups"`` column, and then broadcasts these mean values back to the original DataFrame structure.**
- This means that the resulting DataFrame will have the ``same shape as the original DataFrame``, with each entry in the numeric columns replaced by the mean of its respective group.

In [ ]:
# Apply "transform" to calculate the "mean" for "each group"

df2.groupby('groups').transform(np.mean)

Using ``df2.groupby('groups').transform(np.mean)`` is useful when you want to ``retain the original DataFrame structure`` while ``replacing the values with group-wise statistics``. 

- **``Group A:``**
  - **``Mean of var1``**: (10+22+76)/2=``36.0``
  - **``Mean of var2``**: (100+262+405)/2=``255.666667``
- **``Group B:``**
  - **``Mean of var1``**: (23+11+84)/2=``39.333333``
  - **``Mean of var2``**: (253+111+578)/2=``314.000000``
- **``Group C:``**
  - **``Mean of var1``**: (10+99+45)/2=``59.0``
  - **``Mean of var2``**: (33+969+760)/2=``687.333333``
    
<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">DataFrame.applymap()</p>

<a id="3.5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**SYNTAX:** <b>``DataFrame.applymap(func, na_action=None, **kwargs)``</b>
- Apply a function to a Dataframe elementwise.
- This method applies a function that accepts and returns a scalar to every element of a DataFrame. [Official Pandas Document](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.applymap.html).

In [ ]:
# Let's remember our DataFrame

df_num



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``applies a function`` to ``each element`` in the DataFrame, ``multiplying each numeric value`` by ``5``.**
- The ``applymap()`` method is specifically designed for ``element-wise operations`` on a DataFrame.

In [ ]:
# Apply the "lambda" function to multiply each element by 5
df_num.applymap(lambda x: x*5)

# df_num.apply(lambda x: x*5)  # This will give the same result.
# df_num*5                     # This will give the same result.

- Each value in ``"var1"`` and ``"var2"`` has been multiplied by 5:
  - For example, the original value ``10`` in ``"var1"`` becomes ``50``, and ``100`` in ``"var2"`` becomes ``"500"``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📌💡🤔💭 If both apply() and applymap() functions give the same results, so why do we need them seperately❓  Look over what happens in the following example:</strong></p>


**APPLYMAP()**

**The following command ``applies a applymap() function`` to ``each element`` in the DataFrame df_num, ``calculating the length of each element`` when converted to a string.**
- This method is useful for ``counting the number of characters`` in each entry.

In [ ]:
display(df_num)

# Apply the "lambda" function to calculate the length of "each element"
df_num.applymap(lambda x: len(str(x)))

- **``var1``**: Each numeric value (e.g., 10, 23, etc.) has a length of 2 characters when converted to a string.
- **``var2``**: Each numeric value (e.g., 100, 253, etc.) has a length of 3 characters when converted to a string.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**APPLY()**


**The command ``applies a apply function`` along the ``specified axis`` (default is columns) to calculate the length of the string representation of each column in the DataFrame.**

- <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📌However, this will NOT calculate the length of individual elements; instead, it will return the length of the entire Series as a whole, which effectively gives you the number of entries in each column.</strong></p>

In [ ]:
# Apply the "lambda" function to calculate the length of "each Series"

df_num.apply(lambda x: len(str(x)))

- **applymap()** is only available in DataFrame and used for **``element-wise operation``** across the whole DataFrame. It has been optimized and some cases work **much faster than apply()**


Using ``df_num.apply(lambda x: len(str(x)))`` returns the number of entries in each column rather than the length of individual elements. If you want to calculate the length of each individual element, you should use ``applymap()`` instead. 

- **``var1``**: The Series [10, 23, 33, 22, 11, 99, 76, 84, 45] when converted to a string would look something like;
  - **``'0    10\n1    23\n2    33\n3    22\n4    11\n5    99\n6    76\n7    84\n8    45\n'``**, which has a character length of ``96``.
- **``var2``**: Similarly, the Series [100, 253, 333, 262, 111, 969, 405, 578, 760] would produce a longer string representation, leading to a length of ``105``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



## Then what is the difference between applymap() & apply() ?


- **applymap()** method **``only works on a pandas DataFrame``** where function is **``applied on every element individually``**. 
- **apply()** method can be applied **``along an axis of both DataFrame``** or **``on values of Series``**; where function can be **``applied both series and individual elements based on the type of function provided``**.

### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Series.map()</p>

<a id="3.6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**SYNTAX:** <b>``Series.map(arg, na_action=None)``</b>

- Map values of Series according to an input mapping or function.
- Used for substituting each value in a Series with another value, that may be derived from a function, a dict or a Series. [Official Pandas Document](https://pandas.pydata.org/docs/reference/api/pandas.Series.map.html).

***************************************************************************************************************************

- Python's **map()** is a built-in function that allows you to process and transform all the items in an iterable without using an explicit for loop, a technique commonly known as mapping.
- **map()** is useful when you need to apply a transformation function to each item in an iterable and transform them into a new iterable [Source](https://realpython.com/python-map-function/#:~:text=Python's%20map()%20is%20a,them%20into%20a%20new%20iterable.).

- The **map()** function is used to map values of Series according to input correspondence. Used for substituting each value in a Series with another value, that may be derived from a function, a dict or a Series.
- **map()** accepts a dict or a Series. Values that are not found in the dict are converted to NaN, unless the dict has a default value [Source](https://www.w3resource.com/pandas/series/series-map.php).

In [ ]:
# Display the DataFrame

df3



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code creates a DataFrame and then uses the ``map()`` function on the ``"col1"`` column to replace its values based on a specified mapping dictionary.**

In [ ]:
# Map values in col1

df3.col1.map({1:"A", 2:"B"})

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📌💡🤔💭 WATCH OUT ❗❗❗ Values NOT in the mapping dictionary (in this case, 3 and 4) will result in NaN (Not a Number).</strong></p>

- ``Index 0``: Original value ``1`` is replaced with ``"A"``.
- ``Index 1``: Original value ``2`` is replaced with ``"B"``.
- ``Index 2``: Original value ``3`` is not found in the mapping, so it becomes ``NaN``.
- ``Index 3``: Original value ``4`` is also not found in the mapping, so it becomes ``NaN``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code ``creates a Pandas Series`` named ``s`` that contains a ``mix of strings`` and a ``missing value (NaN)``.**

In [ ]:
# Create a Series named "s"
s = pd.Series(['Data Analyst', 'Data Scientist', np.nan, 'DevOps Engineer'])

# Display the Series
s

- **``Index``**: The Series has a default index starting from 0.
- **``Values``**: The values include two job titles and one missing value (NaN).
- **``Data Type``**: The dtype of the Series is object, which is typical for a Series containing strings and NaN values.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command applies the format method to each element in the Pandas Series ``s``. This will ``transform each string`` in the Series into a ``new string`` that incorporates the original value into the phrase ``"I am a {value}"``.**

In [ ]:
# Use format method with map
s.map('I am a {}'.format)

# Use f-string format with map
# s.map(lambda x: f'I am a {x}')

- The ``map()`` function applies the specified function (in this case, the string formatting method) to each element of the Series.
- For ``each non-null element``, it substitutes the element into the placeholder {} in the string.
- **``Non-null Values``**: Each job title is incorporated into the phrase ``"I am a {job title}"``.
- **``NaN Handling``**: The ``NaN`` value remains as ``NaN`` in the output, since map will leave missing values unchanged.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command applies the format method to each element in the Pandas Series ``s``, similar to the previous example.** 
- However, with the addition of ``na_action='ignore'``, this command will ``skip any NaN values`` during the mapping process.

In [ ]:
# Use format method with map and na_action='ignore'
s.map('I am a {}'.format, na_action='ignore')

# Use f-string format with map and na_action='ignore'
# result = s.map(lambda x: f'I am a {x}' if pd.notna(x) else x, na_action='ignore')

- **``NaN Handling``**: The **``na_action='ignore'``** parameter tells the function to ``ignore any NaN values``, meaning they will ``remain unchanged in the output`` by preventing the formatting function from being applied to it.
<hr>

**WRAP UP:**

**apply()** is used to apply a function along an axis of the DataFrame or on values of Series.<br> 
**applymap()** is used to apply a function to a DataFrame elementwise.<br> 
**map()** is used to substitute each value in a Series with another value.

[SOURCE01](https://towardsdatascience.com/introduction-to-pandas-apply-applymap-and-map-5d3e044e93ff#:~:text=apply()%20is%20used%20to,a%20Series%20with%20another%20value.), [SOURCE](https://stackoverflow.com/questions/19798153/difference-between-map-applymap-and-apply-methods-in-pandas)

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">.transform() vs .apply()</p>

<a id="3.7"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Similarties
- Both apply() and transform() can be used to manipulate the **``entire DataFrame``**.
- Both apply() and transform() support **``lambda expression``**.
- Both apply() and transform() can be used for manipulating a **``single column``**.

In [ ]:
# Create the DataFrame
df5 = pd.DataFrame({'A': [1,2,3], 'B': [10,20,30] })

# Display the DataFrame
df5

- **``Index``**: The DataFrame has a default integer index starting from 0.
- **``Columns``**: It contains two columns:
  - **``Column A``**: Contains values 1, 2, and 3.
  - **``Column B``**: Contains values 10, 20, and 30.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``applies a lambda function`` to ``each column`` of the DataFrame, ``adding 10 to each element``.** 

In [ ]:
display(df5.apply(lambda x: x+10))

df5.transform(lambda x: x+10)

Using both **``appply()``** and **``transform()``** produces same results in an effective way to perform **``element-wise operations``** on all columns of a DataFrame. 
- **``Column A:``**
  - **``Original values``**: [1, 2, 3]
  - **``After adding 10``**: [11, 12, 13]
- **``Column B:``**
  - **``Original values``**: [10, 20, 30]
  - **``After adding 10``**: [20, 30, 40]
  
- **``Key Difference of transform() from apply():``**
  - **``Shape Preservation``**: Unlike apply() method, which can ``potentially change the shape`` of the output depending on the function used, ``transform()`` methhod always returns a DataFrame with the ``same shape as the input DataFrame``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code adds ``two (2) new columns`` to the DataFrame:** 
  - one using the apply() method and 
  - the other using the transform() method

In [ ]:
# Add a new column to the DataFrame by adding 10 to each element via apply() method.
df5['B_apply'] = df5['B'].apply(lambda x: x+10)

# Add a new column to the DataFrame by adding 10 to each element via transform() method.
df5['B_transform'] = df5['B'].transform(lambda x: x+10)

# Display the modified DataFrame
df5

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


### Differences between .apply() and .transform() when manupulating data
- **📌 transform()** CANNOT produce aggregated results.
- **📌 apply()** works with ``multiple Series`` at a time. 
  - But, **transform()** is only allowed to work with a ``single Series`` at a time.


**The following code modifies the DataFrame to keep only the specified columns, ``A`` and ``B``.**

In [ ]:
# Select specific columns to modify the DataFrame
df5 = df5[["A", "B"]]

# Display the modified DataFrame
df5



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command applies a function to each column of the DataFrame that **``calculates the sum of the values``** in that column.**

In [ ]:
# (1) transform() CANNOT produce aggregated results.

df5.apply(lambda x: x.sum())

# df5.transform(lambda x: x.sum()) # gives an error of "ValueError: Function did not transform"

The result is a Series where the **``index``** corresponds to the ``column names`` and the **``values``** are the ``sums of the respective columns``.
- **``Column A``**: The sum is calculated as 1 + 2 + 3 = 6.
- **``Column B``**: The sum is calculated as 10 + 20 + 30 = 60.

<hr>

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>🤔💭 WATCH OUT ❗❗❗ Why the transform() method gives an error in such a case❓ </strong></p>


- Using **``transform()``** produces an **``error``** because the transform method is **``designed to return a DataFrame or Series that has the same shape as the original input``**. When you apply a function like **``sum()``** that **``reduces the size of the input``** (e.g., collapsing multiple values into a single sum), it **``causes a shape mismatch``**.

- **Key Differences Between ``apply`` and ``transform``:**
  - **``apply:``**
    - Can return a Series or DataFrame of ``different shapes``.
      - For example, df5.apply(lambda x: x.sum()) returns a Series with the sums of each column.
  - **``transform:``**
    - Requires the output to have the ``same shape as the input``.
    - If you try to apply a function that reduces the data (like summing), it will NOT work because it doesn't return the same number of entries.


<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command computes the ``difference`` between the ``values in column "B"`` and ``column "A"`` for ``each row`` of the DataFrame.**

In [ ]:
# (2) apply() works with multiple Series at a time. But, transform() is only allowed to work with a single Series at a time

df5.apply(lambda x: x["B"]-x["A"], axis=1)

# df5.transform(lambda x: x["B"]-x["A"], axis=1) # gives an error

- The apply method is called on the DataFrame df5.
- The ``lambda function`` is executed for each row of the DataFrame, where ``x`` represents ``a Series`` corresponding to that row.
- The **``axis=1``** argument indicates that the function should be applied ``across rows`` (i.e., for each row).
<hr>

The **``transform()``** produces an **``error``** because the transform() method is ``NOT designed`` to operate with ``row-wise operations`` (i.e., when axis=1) that require access to multiple columns. Here's a detailed explanation:

- **``Key Points:``**
  - **``Transform Method Behavior:``**
    - The transform method is intended for operations that return a Series or DataFrame of the same shape as the input.
    - It operates on each column independently when axis=0 (the default), and it cannot access multiple columns when applied row-wise (axis=1).
  - **``Error Explanation:``**
    - When you try to access multiple columns in a row-wise context using transform, it fails because transform expects the output to align with the input structure.
    - As a result, when you attempt to reference x["B"] and x["A"], it leads to a shape mismatch or a key error.
<hr>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong>WRAP UP: Differences Between .apply() and .transform()</strong></p>

- **transform()** returns a DataFrame that has the ``same length as the input``, but **apply()** CANNOT.
- **apply()** works with ``multiple Series`` at a time. But, **transform()** is only allowed to work with a ``single Series`` at a time.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [ ]:
# Create the DataFrame
df6 = pd.DataFrame({'key': ['a', 'b', 'c'] * 3,
                    'A': np.arange(9),
                    'B': [1, 2, 3] * 3})

# Display the DataFrame
df6

- **``Column key``**: Contains the values [``'a'``, ``'b'``, ``'c'``] repeated three times.
- **``Column A``**: Contains a range of numbers from 0 to 8 (inclusive), generated by np.arange(9).
- **``Column B``**: Contains the values [``1``, ``2``, ``3``] repeated three times.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``groups the DataFrame`` by the values in the ``"key"`` column and then ``calculates the sum`` of the ``"A"`` column for ``each group``.**

In [ ]:
# Group by 'key' column and sum the 'A' column

df6.groupby('key')['A'].sum()

- **``df6.groupby('key')``**: This part groups the DataFrame based on the unique values in the key column ('a', 'b', and 'c').
- **``['A']``**: This selects the ``"A"`` column from the grouped DataFrame.
- **``.sum()``**: This calculates the ``sum of the "A" values`` for each group.
  - **``Group 'a'``**: Sum of A: 0 + 3 + 6 = ``9``
  - **``Group 'b'``**: Sum of A: 1 + 4 + 7 = ``12``
  - **``Group 'c'``**: Sum of A: 2 + 5 + 8 = ``15``

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command groups the DataFrame by the ``"key"`` column and then applies a lambda function to calculate the sum of the ``"A"`` column for each group.** 

In [ ]:
# Group by 'key' column and apply a lambda function to sum the 'A' column

df6.groupby('key')['A'].apply(lambda x: x.sum())

- **``df6.groupby('key')``**: This part groups the DataFrame by the unique values in the key column ('a', 'b', and 'c').
- **``['A']``**: This selects the A column from the grouped DataFrame.
- **``.apply(lambda x: x.sum())``**: This applies the lambda function to each group, where x represents the values of A for that group. The function calculates the sum of these values.
The result is ``a Series`` ``indexed`` by the ``unique values`` in the ``"key"`` column, with the ``sum of the corresponding "A" values``. 
  - **``Group 'a'``**: Sum of A: 0 + 3 + 6 = 9
  - **``Group 'b'``**: Sum of A: 1 + 4 + 7 = 12
  - **``Group 'c'``**: Sum of A: 2 + 5 + 8 = 15

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:125%; text-align:left;"><strong>Let's do same operation using transform() function now.</strong></p>


**The following command calculates the ``sum of each group`` defined by the ``"key"`` column and returns ``a Series`` that has the ``same length as the original DataFrame``.**

In [ ]:
# Use transform to calculate the sum of 'A' for each group

df6.groupby('key')['A'].transform(lambda x: x.sum())

- **``df6.groupby('key')``**: This part groups the DataFrame by the unique values in the key column ('a', 'b', and 'c').
- **``['A']``**: This selects the A column from the grouped DataFrame.
- **``.transform(lambda x: x.sum())``**: The transform method applies the lambda function to each group, which computes the sum of the values in A for that group.
  - The key difference here is that transform returns ``a Series`` with the ``same index as the original DataFrame``, meaning ``each element`` will be ``replaced with the sum of its group``.
  - **``Group 'a'``**: The sum is 0 + 3 + 6 = 9. ``Every row with key 'a'`` will show the value ``9``.
  - **``Group 'b'``**: The sum is 1 + 4 + 7 = 12. ``Every row with key 'b'`` will show the value ``12``.
  - **``Group 'c'``**: The sum is 2 + 5 + 8 = 15. ``Every row with key 'c'`` will show the value ``15``.
<hr>

<!-- The difference between ``df6.groupby('key')['A'].``**``apply``**``(lambda x: x.sum())`` and ``df6.groupby('key')['A'].``**``transform``**``(lambda x: x.sum())`` lies primarily in the **``shape of the output``** and how the results are represented. -->

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>🤔💭 WATCH OUT ❗❗❗ The difference between apply and transform lies primarily in the shape of the output and how the results are represented.</strong></p>


- **``Purpose and Use Cases:``**
  - **``apply:``**
    - **``Purpose``**: Used when you want to ``perform an operation`` that ``results in a different shape`` or when you need to ``aggregate data into a smaller representation`` (like a summary).
    - **``Use Case``**: Useful for ``summarizing data``, such as calculating totals, means, or other statistics that do ``NOT need to align with the original DataFrame's shape``.
  - **``transform:``**
    - **``Purpose``**: Used when you want to ``perform operations`` that return ``results in the same shape as the input`` DataFrame.
    - **``Use Case``**: Useful for ``generating new columns`` that reflect ``group-level statistics`` while retaining the original DataFrame's structure. For example, you might want to add a column that shows the sum for the respective group next to each row.
- **``Summary:``**
**``apply()``** gives a ``summarized view of the data``, reducing the number of rows and focusing on group statistics.
**``transform()``** provides a way to ``generate statistics while maintaining the original DataFrame's shape``, allowing for ``element-wise operations`` and ``easier integration with the original data``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



In [ ]:
# Let's remember our DataFrame

df6



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command computes the ``mean of the difference`` between the columns ``"B"`` and ``"A"`` for ``each group`` defined by the ``"key"`` column.**

In [ ]:
# (3) apply() works with multiple Series at a time. But, transform() is only allowed to work with a single Series at a time.

df6.groupby('key').apply(lambda x: (x["B"]-x["A"]).mean())

# df6.groupby('key').transform(lambda x: (x["B"]-x["A"]).mean()) # gives an error

- **``df6.groupby('key')``**: This ``groups the DataFrame`` by the ``unique values`` in the ``"key"`` column (``'a'``, ``'b'``, and ``'c'``).
- **``.apply(lambda x: (x["B"] - x["A"]).mean())``**: For ``each group``, the lambda function calculates the ``difference`` between the ``"B"`` and ``"A"`` columns. It then computes the mean of these differences.

This command effectively calculates the ``average difference`` between columns ``"B"`` and ``"A"`` for ``each group`` represented by the ``"key"`` column. 
- **``Differences for Group 'a':``**
  - **``Row 0``**: 1 - 0 = 1
  - **``Row 3``**: 1 - 3 = -2
  - **``Row 6``**: 1 - 6 = -5
    - **``Mean``**: (1 - 2 - 5) / 3 = ``-2``
- **``Differences for Group 'b':``**
  - **``Row 1``**: 2 - 1 = 1
  - **``Row 4``**: 2 - 4 = -2
  - **``Row 7``**: 2 - 7 = -5
    - **``Mean``**: (1 - 2 - 5) / 3 = ``-2``
- **``Differences for Group 'c':``**
  - **``Row 2``**: 3 - 2 = 1
  - **``Row 5``**: 3 - 5 = -2
  - **``Row 8``**: 3 - 8 = -5
    - **``Mean``**: (1 - 2 - 5) / 3 = ``-2``

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:120%; text-align:left;"><strong>📌💡🔥 BE CAREFUL while creating a new feature using groupby() and apply() methods together ❗❗❗</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``calculates the mean`` of the ``"var1"`` column for ``each group`` defined by the ``"groups"`` column and assigns this mean value to a ``new column`` named ``"mean"`` in the DataFrame.**

In [ ]:
df2["mean"] = df2.groupby("groups")["var1"].apply(np.mean)

# Display the modified DataFrame
df2

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>OOOPS🙊🙈🙉 What happened❓ </strong></p>

If all values in the new column are NaN after executing the code, it indicates that the **``index alignment``** ``between the grouped result and the original DataFrame`` is **``NOT matching properly``**. This can happen if the ``groupby operation results in a Series with a different index than the original DataFrame``.

**``Common Causes and Solutions:``**
 - **``Index Alignment:``**
    - When you use ``groupby and apply`` together, the resulting Series may NOT align correctly with the original DataFrame's index because the ``groupby operation creates a new index`` based on the ``unique values of the grouping column``.
     - **``Solution``**: ``Use transform`` instead of apply to return a Series with the ``same index as the original DataFrame``.
 - **``Check for Missing Values``**:
    - Ensure that there are NO missing values (NaN) in the ``"var1"`` column that could affect the grouping and mean calculation.
 - **``DataFrame Structure``**:
    - Make sure the ``"groups"`` column is correctly defined and ``contains valid categorical data``.
    

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``removes the column`` named ``"mean"`` from the DataFrame.**

In [ ]:
df2.drop("mean", axis=1, inplace=True)

# Display the modified DataFrame
df2

- This method is used to drop specified labels from rows or columns.
- The parameter ``"mean"`` specifies the ``column to be dropped``.
- The **``axis=1``** argument indicates that you are dropping a ``column`` (use axis=0 for rows).
- **``inplace=True``**: This modifies the DataFrame in place, meaning the ``change is applied directly to df2`` without needing to reassign it.
   - If **``inplace=False (the default)``**, the method would return a new DataFrame with the specified column removed, but df2 itself would remain unchanged.


<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">pivot() vs pivot_table()</p>

<a id="8"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**pivot_table()**
- pandas.pivot_table(data, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All', observed=False, sort=True).
- Create a spreadsheet-style pivot table as a DataFrame.
- The levels in the pivot table will be stored in MultiIndex objects (hierarchical indexes) on the index and columns of the result DataFrame.

**pivot()**
- DataFrame.pivot(index=None, columns=None, values=None).
- Return reshaped DataFrame organized by given index / column values.
- Reshape data (produce a “pivot” table) based on column values. Uses unique values from specified index / columns to form axes of the resulting DataFrame.
- This function does not support data aggregation, multiple values will result in a MultiIndex in the columns.

**Differences**
- **Pivot_table** is a generalization of pivot that **CAN** handle **duplicate values** for one pivoted index/column pair. However, **pivot()** is used for pivoting without aggregation. Therefore, it **CANNOT** deal with duplicate values for one index/column pair.
- **Pivot_table** will only allow numeric types as "values=", whereas **pivot** will take string types as "values=".
- **Pivot_table** also supports using multiple columns for the index.<br> 
[SOURCE](https://www.quora.com/In-pandas-whats-the-difference-between-dataframe-pivot-and-dataframe-pivot_table)

In [ ]:
# Create dataset
data = {'gender':['male', 'female', 'female', 'male', 'female', 'male'],
        'sport':['tennis', 'tennis', 'basketball', 'football', 'voleyball', 'basketball'],
        'status':["professional", "professional", "professional", "amateur", "amateur", "amateur"],
        'age':[20, 24, 26, 23, 22, 21],
        'height':[185, 172, 175, 178, 182, 196],
        'weight':[83, 58, 62, 80, 65, 90]}

# Create a new DataFrame
df7 = pd.DataFrame(data)

# Display the DataFrame
df7



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong> Create pivot_table():</strong></p>


**The following command ``creates a pivot table`` that summarizes the ``average age of participants`` based on their ``gender`` and the ``sport`` they play.**

In [ ]:
# Creating the Pivot Table:

df7.pivot_table(index='gender',
                columns='sport',
                values='age',
                aggfunc='mean')

- **``index='gender'``**: The rows of the pivot table will be indexed by the unique values in the gender column.
- **``columns='sport'``**: The columns of the pivot table will be created for each unique value in the sport column.
- **``values='age'``**: The values in the pivot table will be taken from the age column.
- **``aggfunc='mean'``**: The aggregation function used to summarize the values (in this case, calculating the mean age).
<hr>

This pivot table provides a clear summary of the ``average ages`` of participants by ``gender`` and ``sport``, allowing for easy comparison across groups.

- **``For Females:``**
  - **``Basketball``**: Average age is 26 (only one female).
  - **``Tennis``**: Average age is 24 (only one female).
  - **``Voleyball``**: Average age is 22 (only one female).
  - **``Football``**: No female participants, so the value is NaN.
- **``For Males:``**
  - **``Basketball``**: Average age is 21 (only one male).
  - **``Football``**: Average age is 23 (only one male).
  - **``Tennis``**: Average age is 20 (only one male).
  - **``Voleyball``**: No male participants, so the value is NaN.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``creates a pivot table`` similar to the previous one but ``specified with a list`` for the values in ``"values"`` parameter.**

In [ ]:
# Creating the Pivot Table:

df7.pivot_table(index='gender',
                columns='sport',
                values=['age'],
                aggfunc='mean')

- **``values=['age']``**: Specifies that the ``values to be aggregated`` come from the ``"age"`` column. 
  - 📌 Note that using a ``list`` allows for specifying ``multiple columns`` if needed.

  - **``Multi-level Columns``**: The output contains a ``multi-level column index``, where each set of columns corresponds to the ``"age"``, ``"height"``, and ``"weight"`` values for ``each sport``.
  - **``Mean Values:``**
    - Each cell shows the average of the specified metric for the corresponding ``sport`` and ``gender``.
    - ``NaN`` values indicate that there are ``NO participants`` for that ``gender-sport`` combination.
    

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong> Create pivot_table() with multiple features:</strong></p>


**The following command ``creates a pivot table`` that ``summarizes the mean values`` of the columns ``"age"``, ``"height"``, and ``"weight"`` for each ``combination of "gender" and "sport"``.** 

In [ ]:
# Creating the Pivot Table:

df7.pivot_table(index='gender',
                columns='sport',
                values=['age', 'height', 'weight'],
                aggfunc='mean')

- **``index='gender'``**: Rows will be indexed by the unique values in the gender column.
- **``columns='sport'``**: Columns will be created for each unique value in the sport column.
- **``📌 values=['age', 'height', 'weight']``**: Specifies that the values to be aggregated come from the age, height, and weight columns.
- **``aggfunc='mean'``**: The aggregation function used to summarize the values, calculating the mean for each specified column.

  - **``Multi-level Columns``**: The output contains a multi-level column index, where each set of columns corresponds to the age, height, and weight values for each sport.
  - **``Mean Values``**:
    - Each cell shows the average of the specified metric for the corresponding sport and gender.
    - NaN values indicate that there are no participants for that gender-sport combination.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong> Create pivot() producing the same result:</strong></p>

**The following command ``creates a pivot table`` that reorganizes the DataFrame based on ``specified`` ``index``, ``columns``, and ``values``.**

In [ ]:
# Creating the Pivot Table:

df7.pivot(index='gender',
          columns='sport',
          values=['age','height','weight'])

- **``index='gender'``**: The rows of the pivot table will be ``indexed`` by the ``unique values`` in the ``"gender"`` column.
- **``columns='sport'``**: The ``columns`` will be created for ``each unique value`` in the ``"sport"`` column.
- **``values=['age', 'height', 'weight']``**: Specifies that the pivot table will include the columns ``"age"``, ``"height"``, and ``"weigh"``.

The resulting pivot table will organize the data in a ``multi-level column format``, ``similar to the previous pivot table`` created with ``pivot_table() method``. 
- **``Multi-level Columns``**: The output contains a ``multi-level column index`` where each set of columns corresponds to ``age``, ``height``, and ``weight`` for ``each sport``.
- **``Values``**:
  - Each cell shows the corresponding value for the specified metric (age, height, weight) for the respective ``gender`` and ``sport``.
  - ``NaN`` indicates that there are ``NO participants`` for that ``specific gender-sport combination``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong> Difference in terms of aggregate function</strong></p>

**📌 1. If we have ``categoric features`` for value parameter rather than ``numerical features``, we can use just ``pivot()`` method:**

- **The following command creates a ``pivot table`` that reorganizes the DataFrame to show the ``status of participants`` based on their ``gender`` and the ``sport`` they play.**

**1. If we have categoric values for value parameter, we can use just "pivot" method.**

In [ ]:
# Creating the Pivot Table:

df7.pivot(index='gender',
          columns='sport',
          values='status')

- **``index='gender'``**: The rows of the pivot table will be indexed by the unique values in the gender column.
- **``columns='sport'``**: The columns will be created for each unique value in the sport column.
- **``values='status'``**: Specifies that the pivot table will include the status column, which indicates whether participants are professional or amateur.
  - **``Values``**: Each cell shows the status of the respective gender for the corresponding sport.
  - **``NaN Values``**: Cells with NaN indicate that there are no participants of that gender for that specific sport.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>🤔💭 WATCH OUT ❗❗❗ Why the pivot_table() method gives an error in such a case❓ </strong></p>


📌 1. The command above results in an error if you attempt to create a pivot table with a column that does ``NOT contain numeric data`` but ``still requires an aggregation`` function. This typically happens when:

  - **``Non-Numeric Values``**: The values in the column specified in values (in this case, status) are non-numeric, which means there is ``NO aggregation function that can be applied`` (like mean, sum, etc.).
  - **``Why It Occurs with status:``**
    - In our case, the **``"status"``** column contains **``categorical data``** (e.g., "professional" and "amateur"), which **``CANNOT be aggregated numerically``**. The ``pivot_table()`` function is expecting to perform a numeric aggregation but finds none.

  - **``Solution:``**
    - To create a pivot table with non-numeric data, you can simply remove the aggregation function since the goal is to display the unique values. You can use ``aggfunc='first'` or ``aggfunc='count'`` if you want to count occurrences.

📌 2. Moreover, the command above results in an error if there are ``duplicate entries`` for the ``combinations`` of ``gender`` and ``sport``. In a pivot table, ``each combination of index and column`` ``must be unique`` to avoid ambiguity.

- **``Other Common Causes of the Error:``**
  - **``Duplicate Entries:``**
    - If there are ``multiple entries`` for the ``same gender and sport combination`` in the ``"status"`` column, the pivot table CANNOT determine how to aggregate those values.
  - **``Missing Data:``**
    - If the DataFrame has ``missing`` or ``NaN`` values in critical columns, it might impact the pivoting operation, but this typically does not lead to an outright error.
  - **``Solution:``**
    - To handle duplicate entries, you can specify an aggregation function (like first, last, count, etc.) to resolve the duplicates. 

In [ ]:
# gives an error because no numeric types to aggregate

# df7.pivot_table(index='gender',
#                columns='sport',
#                values='status')



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



**📌 2. If we have ``duplicate values`` in the column selected for index parameter, we can use only ``pivot_table()`` method.**

- **The following User Define function is intended to apply ``specific styling`` to a ``particular cell`` in a DataFrame when using Pandas' Styler.** 

In [ ]:
# We want to color cell at <3, 2>. Coloring the background red, and text color Violet

# Custom function to color the desired cell
def styling_specific_cell(x, row_idx, col_idx):
    color = 'background-color: yellow; color: red'
    df_styler = pd.DataFrame('', index=x.index, columns=x.columns)
    df_styler.iloc[row_idx, col_idx] = color
    return df_styler

In [ ]:
# Let us remember our DataFrame first:

# Display the DataFrame
df7

idx_r = [1, 2]   # Row indexes of cells to be colored
idx_c = [0, 1]   # Column index of cell to be colored 

# Pass the row and column index as kwargs
df7.style.apply(styling_specific_cell, row_idx=idx_r, col_idx=idx_c, axis = None)  
# Axis set to None to work on entire dataframe



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong>Let's change the value "basketball" of observation for "sport" at the index number 2 into "tennis" to create duplicate values in the DataFrame.</strong></p>

- **The following command ``df7.loc[2, "sport"]="tennis"`` updates the value in the DataFrame at the specified row and column.** 

In [ ]:
df7.loc[2, "sport"] = "tennis"
df7

idx_r = [1, 2]   # Row indexes of cells to be colored
idx_c = [0, 1]   # Column index of cell to be colored 

# Pass the row and column index as kwargs
df7.style.apply(styling_specific_cell, row_idx=idx_r, col_idx=idx_c, axis = None)  
# Axis set to None to work on entire dataframe

- **``This uses .loc[]``** to access the value in the third row (index 2) of the sport column.
- **``= "tennis"``** This assigns the string "tennis" to that specific cell.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``creates a pivot table`` that ``summarizes the average values`` of ``age``, ``height``, and ``weight`` for each ``combination`` of ``gender and sport``.**

In [ ]:
# Creating the Pivot Table:

df7.pivot_table(index='gender',
                columns='sport',
                values=['age','height','weight'],
                aggfunc='mean')

- **``index='gender'``**: The rows of the pivot table will be indexed by the unique values in the gender column.
- **``columns='sport'``**: The columns will be created for each unique value in the sport column.
- **``values=['age', 'height', 'weight']``**: Specifies that the pivot table will include the average values for the age, height, and weight columns.
- **``aggfunc='mean'``**: The aggregation function used to summarize the values, calculating the mean for each specified metric.
- **``Multi-level Columns``**: Each metric (age, height, weight) is displayed under a separate column for each sport.
  - **``Mean Values``**: The cells show the average of each metric for the respective gender and sport.
  - **``NaN Values``**: Cells with NaN indicate that there were no participants for that gender-sport combination.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>


**⚠️☢️☣️ The following command ATTEMPTS to create a pivot table that reorganizes the DataFrame by using gender as the index and sport as the columns, displaying the specified values for age, height, and weight.**

- **``💥 Important Note:``**
  - If there are ``duplicate entries`` for any combination of gender and sport, this command will ``raise a ValueError`` because pivot requires unique index/column combinations. In such cases, you ``should use`` **``pivot_table()``** method with an aggregation function to handle duplicates.

In [ ]:
# gives an error because of the dublicate values

# df7.pivot(index='gender',
#          columns='sport',
#          values=['age','height','weight'])

📌 The **``pivot()``** function in Pandas will **``raise an error``** if there are **``duplicate entries``** for the combinations of the specified index and columns. When using pivot() method, ``each combination of gender and sport MUST be unique`` because it doesn't aggregate the data.

- **``🎯🏆🤝 Solution:``**
  - To handle duplicates, you should use the ``pivot_table()`` function instead. This allows you to specify an aggregation function that will deal with the duplicates appropriately.
    - **``aggfunc='mean'``**: This specifies that if there are duplicate entries for any combination of gender and sport, it will calculate the mean of the values in the age, height, and weight columns.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

📌 When using the **``pivot()``** method in Pandas, ``if we want to avoid errors due to duplicate values``, we **``CANNOT specify an index parameter``**, which is **"gender" where we have duplicate values``**. Instead, we can use only the columns parameter to create a wide-format DataFrame.

In [ ]:
# Creating the Pivot Table:

df7.pivot(columns='sport',
          values=['age','height','weight'])

- **``Using pivot() Without the index Parameter:``**
  - By removing the index parameter, you can pivot the DataFrame to show the specified values across the ``different sports`` ``without grouping by gender``. Here’s how to do it:
    - **``Multi-level Columns``**: The output will have a multi-level column index where each metric (age, height, weight) is displayed under each sport.
    - **``Values``**: Each cell shows the corresponding value for the specified metric (age, height, weight) across the sports.
    - **``NaN Values``**: Cells with ``NaN`` indicate that there are ``NO entries`` for that ``specific combination`` of ``sport and metric``.
- **``Important Note:``**
  - 📌 Using ``pivot()`` method without an index is useful when you want a wide format but be aware that it ``may lead to a loss of some grouping context`` (like gender, in your original case). If you need to distinguish between genders, ``consider using pivot_table() method instead``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:125%; text-align:left;"><strong>🏆 We can get the same results using both groupby() and pivot_table() as well:</strong></p>

### groupby():

**The following command groups the DataFrame by both the ``"gender"`` and ``"sport"`` columns, then ``calculates the mean`` of ``all numeric columns`` within ``each group``.**

In [ ]:
# Group by gender and sport, then calculate the mean of numeric columns
df7.groupby(["gender", "sport"]).mean(numeric_only=True)

# df7.groupby(["gender", "sport"])[['age','height','weight']].mean()

- **``df7.groupby(["gender", "sport"])``**: This groups the DataFrame by the unique combinations of values in the ``"gender"`` and ``"sport"`` columns.
- **``.mean(numeric_only=True)``**: This computes the mean for each numeric column (like ``"age"``, ``"height"``, and ``"weight"``) for each - **``group. 
- **``The numeric_only=True``** parameter ensures that only numeric columns are considered, which is useful if your DataFrame contains non-numeric data.

  - **``Grouped by Gender and Sport``**: Each row corresponds to a unique combination of gender and sport.
  - **``Mean Values``**: The numeric columns (age, height, weight) show the average values for each combination.
  - **``NaN Handling``**: If a group has no entries, it will not appear in the output.
  
<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

### pivot_table():

  
**The following command ``creates a pivot table`` that ``summarizes the average values`` of ``"age"``, ``"height"``, and ``"weight"`` for each ``combination`` of ``"gender"`` and ``"sport"``.**

In [ ]:
# Creating the Pivot Table:

df7.pivot_table(index=['gender', 'sport'],
#                 columns = "status",
                values=['age','height','weight'],
                aggfunc='mean')

- **``index=['gender', 'sport']``**: This specifies that the rows of the pivot table will be indexed by the unique combinations of values in the gender and sport columns.
- **``columns='status'``**: This indicates that the columns of the pivot table will be defined by the unique values in the status column (e.g., "professional" and "amateur").
- **``values=['age', 'height', 'weight']``**: This specifies that the pivot table will calculate the average for the age, height, and weight columns.
- **``aggfunc='mean'``**: This specifies that the mean should be calculated for the specified values.append


  - **``Multi-level Columns``**: The resulting DataFrame will have a multi-level column index where each metric (age, height, weight) is displayed under each status (amateur, professional).
  - **``Mean Values``**: Each cell shows the average of the specified metric for the respective combination of gender, sport, and status.
  - **``NaN Values``**: Cells with NaN indicate that there were no entries for that specific combination.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">.stack() & .unstack()</p>

<a id="9"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Reshape using **``stack()``** and **``unstack()``** function in Pandas python: Reshaping the data using **``stack()``** function in pandas converts the data into stacked format .i.e. the column is stacked row wise. When more than one column header is present we can stack the specific column header by specified the level. **``unstack()``** function in pandas converts the data into unstacked format [Source](https://www.datasciencemadesimple.com/reshape-using-stack-unstack-function-pandas-python/).

**Why and when should use a stack() and unstack() methods?**

[ANSWER](https://stackoverflow.com/questions/69139030/why-and-when-should-use-a-stack-and-unstack-methods)

#### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:left; border-radius:10px 10px;">.stack()</p>

<a id="9.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**SYNTAX:** <b>``DataFrame.stack(level=- 1, dropna=True)``</b>

- Stack the prescribed level(s) from columns to index.
- Return a reshaped DataFrame or Series having a multi-level index with one or more new inner-most levels compared to the current DataFrame.
- The new inner-most levels are created by pivoting the columns of the current dataframe:
    - if the columns have a single level, the output is a Series;
    - if the columns have multiple levels, the new index level(s) is (are) taken from the prescribed level(s) and the output is a DataFrame.

In [ ]:
# Let's remember our DataFrame

df7



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``adds a new column`` named ``"level"`` to the DataFrame.**
- This new column categorizes the ``weight values`` into two levels: ``"high"`` or ``"low"``.

In [ ]:
# Create the 'level' column based on the 'weight' column
df7["level"] = df7["weight"].transform(lambda x: "high" if x > 80 else "low")

# Display the modified DataFrame
df7

- This uses the **``transform()``** method to apply a function to each value in the ``"weight"`` column.
- The ``lambda function`` checks if the ``weight`` is ``greater than 80``:
    - If True, it assigns "high".
    - If False, it assigns "low".
- **``df7["level"] = ...``**: The results of the transform operation are assigned to a new column called ``"level"`` in the DataFrame.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``creates a pivot table`` from the ``DataFrame``, and stores the output in ``df8``.**
- This pivot table **``summarizes the average values``** of **``"age"``**, **``"height"``**, and **``"weight"``** based on the **``unique combinations``** of **``"gender"``**, **``"sport"``**, **``"status"``**, and **``"level"``**.**

In [ ]:
# Creating the Pivot Table:
df8 = df7.pivot_table(index=['gender','sport'],
                      columns=["status","level"],
                      values=['age','height','weight'],
                      aggfunc='mean')

# Display the Pivot Table:
df8

- **``index=['gender', 'sport']``**: This specifies that the rows of the pivot table will be indexed by the unique combinations of values in the gender and sport columns.
- **``columns=["status", "level"]``**: This indicates that the columns of the pivot table will be defined by the unique combinations of values in the status and level columns.
- **``📌 values=['age', 'height', 'weight']``**: This specifies that the pivot table will calculate the average for the age, height, and weight columns.
- **``aggfunc='mean'``**: This specifies that the mean should be calculated for the specified values.

  - **``Multi-level Index and Columns``**: The output will have a multi-level index based on gender and sport, and a multi-level column structure based on status and level.
  - **``Mean Values``**: Each cell shows the average of the specified metric for the respective combination of gender, sport, status, and level.
  - **``NaN Values``**: Cells with NaN indicate that there were NO entries for that specific combination.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command ``converts the pivot table`` from a ``wide format`` to a ``long format`` by stacking the columns.**
- This operation compresses the ``multi-level column index`` into a ``single index``, making the DataFrame easier to work with for certain types of analyses.

In [ ]:
df8.stack()  # Default level=-1

After using df8.stack(), the resulting DataFrame indeed have a ``multi-level index`` that consists of ``"gender"``, ``"sport"``, and ``"level"``, along with the corresponding values for ``"age"``, ``"height"``, and ``"weight"``.

- **``Long Format``**: The DataFrame is now in a long format where the multi-level column index has been transformed into a multi-level index.
- **``Index Levels``**: The new index consists of the original indices (``"gender"``, ``"sport"``) along with the ``"level"`` from the columns, while the columns represent the aggregated metrics (``"age"``, ``"height"``, ``"weight"``).
- **``Mean Values``**: Each row corresponds to a unique combination of the indices, showing the mean values for ``"age"``, ``"height"``, and ``"weight"`` based on the combinations of ``"gender"``, ``"sport"``, and ``"level"``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command is used to stack the columns of the pivot table, df8, specifically targeting the ``second level of the column index`` (which corresponds to ``"status"`` in this case).**
- This operation converts the specified level of the column index into part of the row index, resulting in a reshaped DataFrame.

In [ ]:
# try "-1, -2, 0, 1, 2" as level parameter


# df8.stack(level=0)

# df8.stack(level=-1)

df8.stack(level=-2)



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following command is used to stack the columns of the pivot table, df8, specifically targeting the ``last level of the column index`` (which corresponds to ``"status"`` in this case).** 
- The **``dropna=False``** parameter ensures that even if there are ``NaN`` values, they will be ``included in the output``.

In [ ]:
df8.stack(level=-2, dropna=False)
# df8.stack(level='status', dropna=False)

The output shows a ``multi-level index`` where the **``first level``** represents ``"gender"``, the **``second level``** represents ``"sport"``, and the **``third level``** represents ``"status"``. 

- **``level=-2``**: This targets the ``second level`` of the column index, which contains the metrics (``"status"``).
- **``dropna=False``**: This ensures that rows with NaN values are included in the output.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code stacks the ``last two levels`` of the column index in the pivot table df8.**
- This operation will combine the ``"level"`` and ``"status"`` into the row index, effectively reshaping your DataFrame.

In [ ]:
df8.stack(level=[-1, -2])

# df8.stack(level=[-2, -1])

- **``level=[-1, -2]``**: This specifies that the **``last level``** (which corresponds to ``"status"``) and the **``second-to-last level``** (which corresponds to ``"level"``) should be stacked.
- **``Multi-level Index``**: The new index consists of ``"gender"``, ``"sport"``, ``"level"``, and ``"status"``.
- **``Values``**: The values for ``"age"``, ``"height"``, and ``"weight"`` are organized under the corresponding combinations of ``"gender"``, ``"sport"``,   ``"level"``, and ``"status"``.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>



#### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:left; border-radius:10px 10px;">.unstack()</p>

<a id="9.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**SYNTAX:** <b>``DataFrame.unstack(level=- 1, fill_value=None)``</b>

- Pivot a level of the (necessarily hierarchical) index labels.
- Returns a DataFrame having a new level of column labels whose inner-most level consists of the pivoted index labels.
- If the index is not a MultiIndex, the output will be a Series.

**``unstack()``** function pivots a level of the (necessarily hierarchical) index labels, returning a DataFrame having a new level of column labels whose inner-most level consists of the pivoted index labels [Source](https://www.w3resource.com/pandas/dataframe/dataframe-unstack.php).

In [ ]:
# Let's remember our DataFrame

df8



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code transforms the DataFrame, df8, from a ``long format`` back to a ``wide format``.**
- This operation pivots the ``innermost level`` of the index (or the last level if not specified) into columns.

In [ ]:
df8.unstack()  # Default level=-1 (last level)

- **``Wide Format``**: The DataFrame is now in a wide format, where the metrics (``"age"``, ``"height"``, ``"weight"``) are represented across multiple columns, but NOT all combinations of ``"gender"`` and ``"sport"`` have values, resulting in many ``NaN`` entries.
- **``Column Names``**: The columns are organized by the levels of the original indices, but some metrics may be missing for certain combinations, leading to gaps in the data represented by ``NaN`` values.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code transform the DataFrame, df8, by moving the ``first level`` of the index (which corresponds to ``"gender"``) into the columns.**
- This operation reshapes the DataFrame, allowing for a clearer view of the data based on ``"gender"``.

In [ ]:
# try "-1, 0, 1" as level parameter

df8.unstack(level=-1)
df8.unstack(level=0)

- **``level=0``**: This specifies that the **``first level``** of the index (which is ``"gender"``) should be moved to the column headers.

- **``Wide Format``**: The DataFrame is now in a **``wide format``**, where the metrics (``"age"``, ``"height"``, ``"weight"``) are represented across multiple columns for each ``"sport"``. However, many combinations of ``"gender"`` and ``"sport"`` do NOT have values, resulting in numerous ``NaN`` entries.
- **``Column Names``**: The columns are organized by ``"sport"``, displaying the metrics for both ``"genders"``. Some metrics are missing for certain combinations, leading to significant gaps in the data represented by ``NaN`` values.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>🤔💭 BE CAREFUL ❗❗❗ The NaN values originating from dataset itself will retained:</strong></p>

- When you use the following code ``df8.unstack(level=-1, fill_value=0)``, you reshape the DataFrame by moving the ``last level`` of the index (typically ``"sport"``) into the columns. The **``fill_value=0``** parameter is used to fill ``NaN`` values that ``arise from the unstacking process``.

In [ ]:
df8.unstack(level=-1, fill_value=0) # Replace NaN with this value if the unstack produces missing values.

- **``Structure``**: The output shows that the DataFrame is now organized with ``"gender"`` as the ``first level`` of the index. The columns represent the metrics (like ``"age"``, ``"height"``, ``"weight"``) for each ``"sport"``.
- **``Filled Zeros``**: The **``fill_value=0``** has replaced ``NaN`` entries that arose from the unstacking process. For combinations of ``"gender"`` and ``"sport"`` that had NO data for certain metrics, zeros are shown instead.
- **``📌 Retained NaNs``**: Any original ``NaN`` values from the dataset remain ``unchanged``, which is why you still see ``NaN`` in your output.

**``Summary of Key Points:``**
- **``Last Index Level``**: When you specify **``level=-1``**, it refers to the ``last level`` of the index (in this case, ``"sport"``).
- **``Filling NaNs``**: The **``fill_value=0`` fills gaps created by unstacking but does **NOT affect existing ``NaN`` values** in the dataset.
- **``Output Interpretation``**: The output indicates the metrics for each ``"gender"`` and ``"sport"``, with zeros for missing combinations and retained ``NaN`` values from the original data.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:110%; text-align:left;"><strong>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</strong></p>

**The following code reshapes the DataFrame by moving the ``last level`` of the index (typically representing ``"status"``) into the columns via ``unstack(level=-1)``, and then it ``replaces any NaN values that result from the unstacking process with zeros`` via ``fillna(0)``.**

In [ ]:
df8.unstack(level=-1).fillna(0)

- **``.fillna(0)``**: After unstacking, any ``NaN`` values introduced ``during this operation`` (where there is NO data for a combination of the index levels) will be replaced with ``0``.

<hr>

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>🤔💭 WARNING ❗❗❗</strong></p>

Be cautious when using the **``stack()``** and **``unstack()``** methods in pandas, as unnecessary or improper usage can lead to unintended results. These methods can significantly alter the structure of your DataFrame;
  - potentially introducing complex MultiIndexes, 
  - excessive NaN values, or 
  - making the data more difficult to interpret. 
  
 Always ensure that you fully understand the implications of reshaping your data before applying these methods to avoid confusion and maintain clarity in your analysis.

<a id="10"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#E51A59; font-size:150%; text-align:center; border-radius:10px 10px;">End of the Session - 05 & 06</p>


<p style="text-align: center;"><img src="https://i.ibb.co/TtRtYNn/healthy-lunch.jpg" width="800" height="200" class="img-fluid" alt="Lunch Time"></p>


<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>


<br><br><br>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="450" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>