<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>

<hr>

<a href="https://lms.clarusway.com/mod/lesson/view.php?id=2463&pageid=4531&startlastseen=no"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/2-DAwPY/DAwPy_S01_(Numpy_Arrays).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="90" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DAwPy_S1_%28Numpy_Arrays%29/DAwPy_S1_%28Numpy_Arrays%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="100" height="100" title="Open and Execute in nbviewer"></a><br/>

<hr>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="500" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="text-align: center;"><img src="https://i.ibb.co/XS0bxSH/best-bootcamps.png" width="300" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY_Courses"></p>

<img src=https://i.ibb.co/6gCsHd6/1200px-Pandas-logo-svg.png width="600" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Session - 03</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#E51A59; font-size:200%; text-align:center; border-radius:10px 10px;">Pandas Series</p>

<a id="toc"></a>

## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Content</p>

* [IMPORTING LIBRARIES NEEDED IN THIS NOTEBOOK](#0)
* [CREATING PANDAS SERIES](#1)
    * [Using Lists](#1.1)
    * [Using Numpy Arrays](#1.2)
    * [Using Dictionaries](#1.3)
    * [Using Scalar Value](#1.4)
* [DATA IN A SERIES](#2)
* [BASIC ATTRIBUTES & METHODS OF SERIES](#3)
* [INDEXING AND SLICING WİTH PANDAS SERIES](#4)
* [Selection with Condition and Broadcasting](#5)
* [RECAP FOR SEVERAL SELECTING ATTRIBUTES](#6)
* [THE END OF THE SESSION-03](#7)

## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Importing Libraries Needed in This Notebook</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Once you've installed NumPy & Pandas you can import them as a library:

In [ ]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")  # to suppress all warnings

- ``import warnings``: This imports the warnings module, which is part of Python's standard library and provides a way to issue warning messages.
- ``warnings.filterwarnings("ignore")``: This function call tells Python to ignore all warning messages that would normally be printed. This can be useful when you want to focus on the output of your program without being distracted by warnings.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢 Caution ❗❗❗</strong></p>


- Ignoring warnings can sometimes hide important issues in your code, so use this approach judiciously. It's generally better to address the underlying causes of warnings rather than suppressing them.

## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Creating a Pandas Series</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**``A series``** is a **one-dimensional data structure**. A Series is very **similar to a NumPy array** (in fact it is built on top of the NumPy array object). **What differentiates** the NumPy array from a Series, is that a Series can **have axis labels**, meaning it can be indexed by a label, instead of just a number location. It also doesn’t need to hold numeric data, it can hold any arbitrary Python Object [Source](http://www.datasciencelovers.com/python-for-data-science/pandas-series/).


<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>🔥 So important points to remember for Pandas Series are: 🔥</strong></p>


- **``🤝 Homogeneous data``**: All the elements are of the same type. This consistency in data type allows for efficient storage and operations within the Series.
    - **``Single Data Type``**: All elements in a Series share the same data type (e.g., all integers, all floats, all strings).
    - **``Efficiency``**: Homogeneous data allows Pandas to ``optimize memory usage`` and ``computational speed`` since operations on uniform data types can be executed more efficiently.
    - **``Type Inference``**: When we create a Series, Pandas automatically infers the data type based on the input data. We can also explicitly specify the data type using the dtype parameter.
- **``⛔ Size Immutable``**: The size of a Pandas Series is immutable, meaning that once a Series is created, we CANNOT change its length (i.e., the number of elements it contains). The size (or length) of a Pandas Series is fixed once it is created. We CANNOT directly change the number of elements in the Series.
    - **``Effect``**: If we want to change the size of a Series (e.g., adding or removing elements), we CANNOT do so directly. Instead, we would need to create a new Series.
- **``🛠️ Values of Data Mutable``**: While the size of a Series is immutable, the individual values within the Series are mutable. This means we can modify the existing elements in the Series after it has been created.
    - **``Effect``**: We can change the value of an element at a specific index without needing to create a new Series. While we can modify the individual elements of an existing Series (changing their values), this does NOT affect the overall size of the Series.
<hr>


### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:125%; text-align:left;"><strong>📑✍️ Summary Key Points from the Slides:</strong></p>


- Pandas **``Series``** is a **``one-dimensional data structure``**. 
- It can hold data of many types including objects, floats, strings and integers. 
- We can create a series by calling ``pandas.Series()``. 
- A list, numpy array, dict can be turned into a pandas Series. We should use the simplest data structure that meets our needs [Source](https://pythonbasics.org/pandas-series/). 
- The **``axis labels``** are collectively called **``index``**. **``Labels``** need **``NOT be unique``** but **``MUST``** be a **``hashable type``**. The object supports both integer and label-based indexing and provides a host of methods for performing operations involving the index [Source](https://www.geeksforgeeks.org/creating-a-pandas-series/).

  - In programming, particularly in Python, the term **``hashable``** refers to an object that has a **``hash value``** that **``remains constant during its lifetime``**. Hashable objects can be used as **``keys in dictionaries``** or as **``elements in sets``**.

  - **``Key Characteristics of Hashable Objects:``**
     - **``Immutable``**: Hashable objects CANNOT change their state or value once they are created. For example, tuples and strings are hashable because they are immutable. For example, in Python, strings are immutable, which means that when you perform operations that modify a string (like concatenation), a new string is created rather than changing the original string, its id and hash value will be changed.
     - **``Consistent Hash Value``**: The hash value of a hashable object, which is generated by the built-in hash() function, must remain the same throughout the object's lifetime.
     - **``Unique Representation``**: While hashable objects do NOT need to be unique, they must have a consistent way to represent their identity. Two different objects can have the same hash value (a scenario known as a hash collision).
       - **``Examples of Hashable Types:``**
         - **``Immutable Types:``**
           - Integers
           - Floats
           - Strings
           - Tuples (as long as they contain only hashable elements)
         - **``Non-Hashable Types:``**
           - Lists (mutable)
           - Dictionaries (mutable)
           - Sets (mutable)
  - **``Usage in Pandas:``**
    - In the context of a Pandas Series, the index is used to label the data elements. While these labels do NOT have to be unique (i.e., you can have repeated labels), they MUST be of a hashable type, enabling efficient data access and manipulation. When we change the index labels of a Pandas Series, the hash values of those labels will also change.

  - **``Key Points about Index in a Pandas Series:``**
    - **``Hashable Labels``**: The labels used in the index (e.g., strings, integers, tuples) must be hashable. This is because the internal structure of Pandas often relies on using these labels as keys, similar to how dictionaries work.
    - **``Modifiable Index``**: You can change the index of a Series after it has been created. For example, you can set a new index using series.index = new_index. However, the new index must still consist of hashable types.
    - **``Uniqueness Not Required``**: While the index labels must be hashable, they do not need to be unique. This means you can have repeated labels in the index, but each label must still be a hashable type.
    - **``Immutable Hash Values``**: Each individual label in the index (like strings, integers, etc.) has a hash value that is based on its content. For instance, the hash value of the string "a" will always be the same as long as it remains unchanged.
    - **``Changing Labels``**: When we change an index label in a Pandas Series, we are essentially replacing the old label with a new one. Since the new label is a different object (even if it has similar content), it will have a different hash value.
      - When the index labels are changed, they are replaced with new labels.
      - Each new label will have a different hash value compared to the old label, reflecting that they are different objects.
      - Thus, changing index labels results in new hash values for those labels.

[SOURCE01](https://pandas.pydata.org/docs/reference/api/pandas.Series.html), [SOURCE02](https://www.datasciencemadesimple.com/create-series-in-python-pandas/), 
[SOURCE03](https://www.cbsecsip.in/2020/08/pandas-data-structure-series.html), 
[SOURCE04](https://towardsdatascience.com/pandas-series-a-lightweight-intro-b7963a0d62a2), 
[SOURCE05](https://www.educba.com/pandas-series/), 
[SOURCE06](http://www.rebellionrider.com/python-pandas-series-in-detail-part-1/), 
[SOURCE06](https://www.javatpoint.com/python-pandas-series), &
[SOURCE06](https://towardsdatascience.com/20-examples-to-master-pandas-series-bc4c68200324)<br>
<hr>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>👉 In this lecture we will discuss how to create Pandas Series, use basic attributes of Series, index Pandas Series & be familiar with Pandas Dataframes.</strong></p>

<hr>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>🏃🏃🏽‍♀👉 Let's begin our introduction by exploring how to create Pandas Series.</strong></p>


- **You can create a series by calling pandas. Series() . A list, numpy array, dict and scalar value can be turned into a pandas series.**

   - **``pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)``**

### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:125%; text-align:left;"><strong>🥳 Our First Series:</strong></p>

- We first create a variaty of objects including Python lists, Numpy Array, and Python Dictionary for our operation.

In [103]:
# Create a simple list of strings
labels = ['a', 'b', 'c']

# Create a simple list of integers
my_list = [10, 20, 30]

# Create a NumPy array from a list of integers
arr = np.array([10, 20, 30])

# Create a simple Python Dictionary
d = {'a': 10, 'b': 20, 'c': 30}

### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Using Lists</p>

<a id="1.2.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**To turn a list into a series, all you have to do is:**

In [104]:
# Create a Pandas Series from a list of strings

pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [105]:
# Create a Pandas Series from a list of integers

pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [108]:
# Create a Pandas Series from a list of integers

pd.Series((10, 20, 30))

0    10
1    20
2    30
dtype: int64

- **By default it assigns an index. First it shows the index, then the element value.**

### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Using NumPy Arrays</p>

<a id="1.2.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**You can create a Series from a Numpy ndarray.**

In [109]:
# Let's remember our array

arr

array([10, 20, 30])

In [113]:
# Create a Pandas Series from a Numpy array

pd.Series(data=arr, index=labels)

a    10
b    20
c    30
dtype: int32

### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Using Dictionaries</p>

<a id="1.2.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**If you have a Python Dictionary, you can turn it into a Series:**

In [114]:
# Let's remember our Python Dictionary

d

{'a': 10, 'b': 20, 'c': 30}

In [115]:
# Create a Pandas Series from a Python Dictionary

pd.Series(d)

a    10
b    20
c    30
dtype: int64

It used the **``dictionary keys``** as **``index``**. The keys of the dictionary match with the Index values; hence, the default Index values have NO effect in this case.

In [116]:
# Create a Series using the Python Dictionary and the labels

pd.Series(data=d, index=['q', 'c', 'y'])

q     NaN
c    30.0
y     NaN
dtype: float64

- In the example above, when we create a Pandas Series from a dictionary with a specified index, **``the NaN (Not a Number) values appear for the labels in the index that do NOT match any keys in the dictionary``**.

  - **``Index Specification:``**
    - We specified an index of ['q', 'c', 'y']. This means we want the Series to look for these labels.
      - The dictionary d only contains keys 'a', 'b', and 'c'.
  - **``Key Matching:``**
    - When Pandas constructs the Series, it looks for each label in the specified index:
      - For **``'q'``**: There is **``NO``** corresponding key in the dictionary, so it is filled with **``NaN``**.
      - For **``'c'``**: There is a corresponding value (30) in the dictionary, so it is filled with that value.
      - For **``'y'``**: There is **``NO``** corresponding key in the dictionary, so it is also filled with **``NaN``**.

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢❗🚨 Note that the Index is first build with the keys from the dictionary. After this the Series is reindexed with the given Index values, hence we get all NaN as a result.</strong></p>

### <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Using Scalar Value</p>

<a id="1.2.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

 - **``Scalars``** are **``single values``** representing one unit of data, such as an integer or bool, as **``opposed to``** data structures like a **``list``** or **``tuple``**, which are composed of scalars.

   - 📌 If data is a scalar value, an **``index must be provided``**. The value will be **``repeated``** to match the length of index [Source](https://www.tutorialspoint.com/python_pandas/python_pandas_series.htm).

In [117]:
# Create a Pandas Series using a scalar value

pd.Series(data="Matthew")

0    Matthew
dtype: object

- **``Scalar Value``**: In this case, "Matthew" is a scalar value (a single string).
- **``Default Index``**: By default, Pandas assigns a numeric index starting from 0. Since we provided a single scalar value, the Series will have one element at index 0.
- **``Data Type``**: The data type of the Series is object since it contains string data.
<HR>

In [118]:
range(3)

range(0, 3)

In [119]:
# Create a Pandas Series using a scalar value and a specified index

pd.Series(data="Matthew", index=range(3))

0    Matthew
1    Matthew
2    Matthew
dtype: object

 - **``Scalar Value``**: The scalar value "Matthew" is provided as the data for the Series.
 - **``Index Specification``**: The index is specified using range(3), which generates the indices 0, 1, and 2.
 - **``Repetition of Scalar``**: Since we provided a scalar value and specified an index with three positions, the scalar value "Matthew" is repeated for each index.
 - **``Data Type``**: The data type of the Series is object, which is typical for string data in Pandas.
<hr>

In [120]:
# Create a Pandas Series using a scalar value and a specified index

pd.Series(data=10, index=['a', 'b', 'c'])

a    10
b    10
c    10
dtype: int64

 - **``Scalar Value``**: The scalar value 10 is provided as the data for the Series.
 - **``Index Specification``**: The index is specified as ['a', 'b', 'c'], which means the Series will have these labels.
 - **``Repetition of Scalar``**: Since we provided a scalar value and specified an index with three positions, the scalar value 10 is repeated for each index label.
 - **``Data Type``**: The data type of the Series is int64 because the scalar value is an integer.
 <hr>

## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Data in a Series</p>

<a id="2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**``A series``** is a **one-dimensional data structure**. A Series is very **similar to a NumPy array** (in fact it is built on top of the NumPy array object). **What differentiates** the NumPy array from a Series, is that a Series can **have axis labels**, meaning it can be indexed by a label, instead of just a number location. It also doesn’t need to hold numeric data, it can hold any arbitrary Python Object [Source](http://www.datasciencelovers.com/python-for-data-science/pandas-series/).

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢 REMINDER: Important points to remember for Pandas Series are:</strong></p>

- **``Homogeneous data``**
- **``Size Immutable``**
- **``Values of Data Mutable``**

<hr>

### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:125%; text-align:left;"><strong>A pandas Series can hold a variety of object types:</strong></p>


In [121]:
# Create a Pandas Series with a list of data types. The Series created contains "class types" as its elements.

pd.Series([set, list, dict])

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

- **``List of Types``**: The input list contains the types set, list, and dict. These are class types in Python, not instances of those types.
- **``Index``**: By default, Pandas assigns a numeric index starting from 0 to each element in the Series.
- **``Data Type``**: The data type of the Series is object, which is the default type for storing mixed or non-numeric data in Pandas.
<hr>

In [122]:
# Call the first element of the Series (which is the set type) with a list

pd.Series([set, list, dict])                     [0]               ([2, 5, 7, 5, 8, 2])

{2, 5, 7, 8}

- **``Creating the Series:``**
  - pd.Series(set) creates a Series where the first element is the **``set type``** itself.
- **``Accessing the First Element:``**
  - series[0] retrieves the **``set class``** from the Series.
- **``Calling the Set Constructor:``**
  - By calling series[0]([2, 5, 7, 5, 8, 2]), we invoke the set constructor with a list of numbers. This constructs a set from the list, automatically removing duplicates.
- **``Result:``**
  - The result is {2, 5, 7, 8}, which is a set containing unique values from the input list.

<hr>

### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:125%; text-align:left;"><strong>Even functions can be used:</strong></p>

**The following code creates a Pandas Series from a ``list of functions (like sum, print, and len)``, we can store and access these functions as elements of the Series (although it's unlikely to use Series in such situations but the example shows the power of Series).** 

In [123]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [124]:
# Call the "print" function from the Series with the argument "a"

pd.Series([sum, print, len])    [1]     ("a")

a


- **``Creating the Series``**: The Series is created with three functions: sum, print, and len.
- **``Accessing the Function``**: series[1] retrieves the **``print function``** from the Series.
- **``Calling the Function``**: When we call series[1]("a"), we invoke the print function with the argument "a".
- **``Output``**: The print function outputs the string directly to the console, resulting in a.
<hr>

In [125]:
# Call the "len" function from the Series with the argument "a"

pd.Series([sum, print, len])            [2]               ("clarusway")

9

- **``Creating the Series``**: The Series is created with three functions: sum, print, and len.
- **``Accessing the Function``**: series[2] retrieves the **``len function``** from the Series.
- **``Calling the Function``**: When we call series[2]("clarusway"), we invoke the len function with the argument "clarusway".
- **``Output``**: The print function outputs the length of the argumnet "clarusway" directly to the console, resulting in 9.
<hr>

In [126]:
# Define a list containing mixed data types of string, integer, and boolean

mix_data = ['Matthew', 2, True]

In [127]:
# Create a Pandas Series from the mixed data
ser = pd.Series(mix_data)

# Display the Series
ser

0    Matthew
1          2
2       True
dtype: object

In [129]:
# Check the data type of the Series

ser.dtype

dtype('O')

- **``object Data Type``**: In this context, object is the default data type used by Pandas for Series that contain mixed data types. It signifies that the elements can be of different types (like strings, integers, booleans, etc.).

In Pandas, the data type object is used to represent a collection of mixed or heterogeneous data types. Here’s why the dtype of a Series containing mixed data types (like strings, integers, and booleans) is object:

- **``Reasons for object Data Type:``**
  - **``Heterogeneous Data``**:
When a Series contains elements of different types (such as strings, integers, and booleans), Pandas CANNOT assign a more specific data type (like int64, float64, or bool) because those data types are NOT UNIFORM across the Series.
  - **``Flexibility``**:
The object type allows for the storage of any Python object, making it flexible enough to accommodate various data types. This is particularly useful for cases where data might NOT be uniform.
  - **``Underlying Implementation``**:
Pandas is built on top of NumPy, which has fixed data types for efficiency. When you introduce mixed types, Pandas defaults to using object to avoid losing information or raising errors.
  - **``Performance Considerations``**:
While object type allows for flexibility, it may NOT be as performant as using specific types (like int or float). Operations on object dtype can be slower because they involve more generic handling of elements.

<hr>

In [130]:
# Check the type of the Series

type(ser)

pandas.core.series.Series

In [131]:
# Check the type of the first element

type(ser[0])

str

- **``Accessing the First Element``**: ser[0] retrieves the first element of the Series, which is string 'Matthew'.

<hr>

In [132]:
# Check the type of the first element

type(ser[1])

int

- **``Accessing the Second Element``**: ser[1] retrieves the second element of the Series, which is integer 2.

<hr>

In [133]:
# Check the type of the first element

type(ser[2])

bool

- **``Accessing the Third Element``**: ser[2] retrieves the third element of the Series, which is Boolean True.

<hr>

In [134]:
# Create a NumPy array from the mixed data
arr = np.array(mix_data)

# Display the array
arr

array(['Matthew', '2', 'True'], dtype='<U11')

- **``Data Type:``**
  - Since the list contains a string ('Matthew'), an integer (2), and a boolean (True), NumPy promotes the other types to string to maintain a consistent data type across the array.
  - As a result, the **``integer``** and **``boolean``** values are **``converted to strings``**, leading to the entire array being of type string.

In [136]:
# Check the type of the third element

type(arr[2])

numpy.str_

- **``Accessing the Element``**: arr[2] retrieves the **``third element``** of the NumPy array, which corresponds to the **``boolean value True``** from the original list.
- **``Type of the Element``**:
  - **``NumPy converts the boolean True to its string representation``** when creating the array, resulting in 'True'.
  - The type of this element is numpy.str_, which is NumPy's own string type (similar to Python's built-in str).

**[Reminder Source for Numpy Arrays](https://pythonguides.com/python-numpy-data-types/)**

## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">BASIC ATTRIBUTES & METHODS OF SERIES</p>

<a id="3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**SOME COMMON ATTRIBUTES** [Official Pandas API Document](https://pandas.pydata.org/docs/reference/api/pandas.Series.html)<br>

- **``Series.dtype``**	It returns the data type of the data.<br>
- **``Series.shape``**	It returns a tuple of shape of the data.<br>
- **``Series.size``**	    It returns the size of the data.<br>
- **``Series.ndim``**	    It returns the number of dimensions in the data.<br>
- **``Series.index``**	Defines the index of the Series.<br>
- **``Series.keys``**  	Return alias for index.<br>
- **``Series.values``**   Returns Series as ndarray or ndarray-like depending on the dtype.<br>
- **``Series.items``**	Lazily iterate over (index, value) tuples.<br>
- **``Series.head``**   	Return the first n rows.<br>
- **``Series.tail``** 	Return the last n rows.<br>
- **``Series.sample``**   Return a random sample of items from an axis of object.<br>
- **``Series.sort_index``**  Sort Series by index labels.<br>
- **``Series.sort_values``**  Sort by the values.<br>
- **``Series.isin``**     Whether elements in Series are contained in values.<br>

In [137]:
# Create a Pandas Series with 7 random integers between 0 and 99
ser = pd.Series(np.random.randint(0, 100, 7))

# Display the Series
ser

0    18
1    95
2    22
3    67
4    72
5    45
6    16
dtype: int32

- **``Generating Random Integers:``**
  - np.random.randint(0, 100, 7) generates an array of 7 random integers, where each integer is between 0 (inclusive) and 100 (exclusive).
- **``Creating the Series:``**
  - The generated array of random integers is passed to pd.Series(), creating a Series where each element corresponds to one of the random integers.
- **``Default Index:``**
  - By default, Pandas assigns a numeric index starting from 0 to each element in the Series.
<hr>

### type:


In [138]:
# Check the type of the Series

type(ser)

pandas.core.series.Series

- **``Output``**: The output indicates that **``ser``** is an instance of the Series class from the Pandas library.
  - This confirms that **``ser``** is indeed a Pandas Series object, which allows you to utilize all the functionalities provided by the Pandas library for data manipulation and analysis.

<hr>

### data type:


In [139]:
# Check the data type of the Series

ser.dtype

dtype('int32')

- **``Data Type``**: The output indicates that the elements in the Series are of type int64, which is the default integer type used by Pandas for integer data.
  - This means that the Series contains 64-bit integers.

<hr>

### shape:


In [140]:
# Check the shape of the Series

ser.shape

(7,)

- **``Shape of the Series``**: The output (7,) indicates that the Series has 7 elements.
  - The shape is represented as a tuple, where:
    - The first value (7) is the number of elements in the Series.
    - The trailing comma indicates that this is a one-dimensional object.

<hr>

### size:


In [141]:
# Check the size of the Series

ser.size

7

- **``Size of the Series``**: The output 7 indicates that there are 7 elements in the Series.
  - The **``size``** attribute specifically counts the number of elements, regardless of the index or shape.

<hr>

### length of Series:


In [142]:
# Check the length of the Series

len(ser)

7

- **``Length of the Series``**: The output 7 indicates that there are 7 elements in the Series.
  - The **``len()``** function is a built-in Python function that returns the number of items in an object, and it works seamlessly with Pandas Series.

<hr>

### number of dimension:


In [143]:
ser.ndim

1

- **``Number of Dimensions``**: The output 1 indicates that the Series is one-dimensional.
  - This means that the Series consists of a single axis, where each element can be accessed via its index.

<hr>

In [144]:
# Let's remember our Series

ser

0    18
1    95
2    22
3    67
4    72
5    45
6    16
dtype: int32

<hr>

### index:


In [145]:
# Check the index of the Series

ser.index

RangeIndex(start=0, stop=7, step=1)

- **``Index of the Series``**: The output **``RangeIndex(start=0, stop=7, step=1)``** indicates that the Series has a default index ranging **``from 0 to 6``**.
  - The **``RangeIndex``** represents a simple, integer-based index, which is the default when no custom index is provided.

<hr>

In [146]:
# Convert the index of the Series to a list

list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

- **``ser.index``**: This property retrieves the index labels of the Series.
- **``list() Conversion``**: Using list() converts the index object into a standard Python list, making it easy to work with or display.

<hr>

### keys of Series:


In [147]:
# Get the keys (index labels) of the Series

ser.keys()

RangeIndex(start=0, stop=7, step=1)

- **``Keys of the Series``**: The output RangeIndex(start=0, stop=7, step=1) indicates that the Series has a default index ranging from 0 to 6.
  - The **``keys()``** method returns the index labels, which can be thought of as the "keys" if you consider the Series to be similar to a dictionary.

<hr>

In [148]:
# Iterate over the index labels using ser.index
print("Using ser.index:")
for i in ser.index: # we can also use "keys()"
    print(i)
    
# Alternatively, using ser.keys()
print("\nUsing ser.keys():")
for i in ser.keys():
    print(i)

Using ser.index:
0
1
2
3
4
5
6

Using ser.keys():
0
1
2
3
4
5
6


- **``Iterating with ser.index:``**
  - The loop iterates over the index of the Series, printing each index label.
- **``Iterating with ser.keys():``**
  - The second loop does the same but uses the keys() method to access the index labels.

<hr>

### values of Series:


In [149]:
# Access the values of the Series

ser.values

array([18, 95, 22, 67, 72, 45, 16])

- **``Underlying Data``**: ser.values retrieves the values stored in the Series as a NumPy array.
  - This allows you to perform operations that are available for NumPy arrays, such as mathematical computations, reshaping, etc.

<hr>

In [150]:
# Create a list from the Series values using a list comprehension

[i for i in ser.values]

[18, 95, 22, 67, 72, 45, 16]

- **``List Comprehension``**: The expression **``[i for i in ser.values]``** iterates over each value in ser.values (which is a NumPy array) and constructs a new list containing those values.
- **``Conversion``**: This effectively converts the NumPy array of values into a Python list, which can be useful for further processing or when you need a list format.

<hr>

In [151]:
# Iterate over the values of the Series and print each one

for i in ser.values:
    print(i)

18
95
22
67
72
45
16


- **``Accessing Values``**: **``ser.values``** retrieves the underlying data of the Series as a NumPy array.
- **``Iteration``**: The for loop iterates over each value in this array, allowing you to perform operations (such as printing) on each individual value.

<hr>

### items:


In [152]:
# Iterate over the Series items (index-value pairs)

ser.items

<bound method Series.items of 0    18
1    95
2    22
3    67
4    72
5    45
6    16
dtype: int32>

- **``Items Method``**: The **``ser.items()``** method returns an iterator over the Series, yielding pairs of (index, value) for each item.
  - **``Iteration``**: The for loop iterates through these pairs, allowing you to access both the index and the value at the same time.

<hr>

In [153]:
# Iterate over the Series items 

ser.items()

- **``Items Method``**: The **``ser.items()``** method returns an iterator over the Series, yielding pairs of (index, value) for each element.
- **``Iteration``**: The for loop iterates through these pairs, allowing you to access both the index and the corresponding value at the same time.

<hr>

In [154]:
# Convert index-value pairs of the Series to a list of tuples

list(ser.items())

[(0, 18), (1, 95), (2, 22), (3, 67), (4, 72), (5, 45), (6, 16)]

- **``Items Method``**: The **``ser.items()``** method generates an iterator over the index-value pairs of the Series.
- **``Conversion to List``**: Using **``list()``** on this iterator converts it into a list of tuples, where each tuple contains an index and its corresponding value.

<hr>

In [155]:
# Iterate over the Series items (index-value pairs)

for index, value in ser.items():
    print(f"Index: {index}, Value: {value}")

Index: 0, Value: 18
Index: 1, Value: 95
Index: 2, Value: 22
Index: 3, Value: 67
Index: 4, Value: 72
Index: 5, Value: 45
Index: 6, Value: 16


- **``Items Method``**: The **``ser.items()``** method provides an iterator that yields pairs of index and value for each element in the Series.
- **``Iteration``**: The for loop iterates through these pairs, allowing you to access both the index and the value simultaneously.
- **``Formatted Output``**: The print statement uses an f-string to format the output, displaying the index and the corresponding value in a readable way.

<hr>

In [156]:
# Create a Pandas Series with random integers and a custom index
ser = pd.Series(data = np.random.randint(0, 25, 10), index=[i for i in "cbaefdgihj"])

# Display the Series
ser

c     5
b     4
a     1
e    22
f    23
d    24
g     1
i    22
h    21
j     9
dtype: int32

- **``Data Generation:``**
  - **``np.random.randint(0, 25, 10)``** generates an array of 10 random integers, each between 0 and 24.
- **``Custom Index:``**
  - The index is created using a list comprehension that iterates over the string **``"cbaefdgihj"``**, resulting in the following **``index: ['c', 'b', 'a', 'e', 'f', 'd', 'g', 'i', 'h', 'j']``**.
- **``Creating the Series:``**
  - **``pd.Series(data=..., index=...)``** creates a Series where each value corresponds to the specified index.

<hr>

### head:


In [157]:
# Display the first three entries of the Series

ser.head()

c     5
b     4
a     1
e    22
f    23
dtype: int32

- **``head(3) Method``**: This method returns the first three entries of the Series, along with their corresponding index labels.
  - It is a convenient way to quickly check the beginning of your data.

<hr>

### tail:


In [158]:
# Display the last two entries of the Series

ser.tail(2)

h    21
j     9
dtype: int32

- **``tail(2) Method``**: This method returns the last two entries of the Series, along with their corresponding index labels.
  - It provides a convenient way to quickly check the end of your data.

<hr>

### sample:


In [164]:
# Randomly sample 2 entries from the Series

ser.sample(2)

g    1
a    1
dtype: int32

- **``sample(2) Method``**: This method randomly selects two entries from the Series, returning them along with their corresponding index labels.
  - Each time you run this code, you may get different entries since the selection is random.

<hr>

### sorting index of Series:


In [166]:
# Sort the Series by index in ascending order

ser.sort_index(ascending=False)

j     9
i    22
h    21
g     1
f    23
e    22
d    24
c     5
b     4
a     1
dtype: int32

- **``sort_index(ascending=True)``**: This method sorts the Series based on its index labels in ascending order. By default, ascending=True, so it sorts from lowest to highest.
  - The sorted Series retains its values but rearranges them according to the sorted index.

<hr>

### sorting values of Series:


In [168]:
# Sort the Series by values in descending order

ser.sort_values(ascending=False)

d    24
f    23
e    22
i    22
h    21
j     9
c     5
b     4
a     1
g     1
dtype: int32

- **``sort_values(ascending=False)``**: This method sorts the Series based on its values in descending order. Setting ascending=False means that the largest values will appear first.
  - The sorted Series retains its index labels but rearranges them according to their corresponding sorted values.

<hr>

In [169]:
# Let's remember our Series

ser

c     5
b     4
a     1
e    22
f    23
d    24
g     1
i    22
h    21
j     9
dtype: int32

<hr>

### isin:


In [170]:
# Check which elements are in the list [5, 9]

ser.isin([5, 9])

c     True
b    False
a    False
e    False
f    False
d    False
g    False
i    False
h    False
j     True
dtype: bool

Using ser.isin([5, 9]) allows you to check which elements in the Pandas Series are contained in the specified list (in this case, [5, 9]). This method returns a boolean Series indicating whether each element is in the provided list.

- **``isin([5, 9]) Method``**: This method checks each element in the Series to see if it is present in the list [5, 9].
  - The result is a boolean Series where each True indicates that the corresponding element in the original Series is either 5 or 9, and False indicates it is NOT.

<hr>

## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Indexing & Slicing with Pandas Series</p>

<a id="4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

As stated and implemented by examples above, a Series is very similar to a NumPy array. 
- What differentiates the NumPy array from a Series is that **a Series can have axis labels**, meaning it can be indexed by a label, instead of just a number location. It also doesn’t need to hold numeric data, it can hold any arbitrary Python Object [Source](https://rpubs.com/pjozefek/659184).

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

The axis labeling information in pandas objects serves many purposes:

- Identifies data (i.e. provides metadata) using known indicators, important for analysis, visualization, and interactive console display.
- Enables automatic and explicit data alignment.
- Allows intuitive getting and setting of subsets of the data set.

In this section, we will focus on the final point: namely, how to slice, dice, and generally get and set subsets of pandas objects. The primary focus will be on Series and DataFrame as they have received more development attention in this area. For more information, please visit [pandas-docs.github.io](https://pandas-docs.github.io/pandas-docs-travis/user_guide/indexing.html)

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [180]:
# Create the first Series
ser1 = pd.Series([1, 2, 3, 4], index = ['USA', 'Germany','RF', 'Japan'])

# Create the second Series
ser2 = pd.Series([1, 2, 5, 4, 6], index = ['USA', 'Germany','Italy', 'Japan', 'Spain'])

The two main data structures in Pandas both have at least one axis.
- A **Series** has **one axis**, the index. 
- A **DataFrame** has **two axes**, the index and the columns. 

It’s useful to note here that in all the DataFrame functions that can be applied to either rows or columns;
 - an **``axis of 0``** refers to the **``index``**, 
 - an **``axis of 1``** refers to the **``columns``**.

In [181]:
# Display the first Series

ser1

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

- **``Data``**: The values are [1, 2, 3, 4].
- **``Index``**: The corresponding indices are ['USA', 'Germany', 'RF', 'Japan'].
- **``Type``**: The Series has a data type of int64.

<hr>

In [182]:
# Display the second Series

ser2

USA        1
Germany    2
Italy      5
Japan      4
Spain      6
dtype: int64

- **``Data``**: The values are [1, 2, 5, 4, 6].
- **``Index``**: The corresponding indices are ['USA', 'Germany', 'Italy', 'Japan', 'Spain'].
- **``Type``**: The Series has a data type of int64.

<hr>

- **``Summary of Differences in these two Series:``**
  - **``Values``**: Different sets of integer values.
  - **``Indices``**: Different labels and lengths, with some indices being common and others unique.
    - **``Common indices``**: ['USA', 'Germany', 'Japan'].
    - **``Unique indices``**:
      - **``In ser1``**: ['RF'].
      - **``In ser2``**: ['Italy', 'Spain'].
      - **``Length``**: ser1 has 4 entries, while ser2 has 5 entries.

<hr>

**The following code ``sorts the values of the Pandas Series ser1 by its index labels in ascending order``.**

In [183]:
# Sort the Series by index

ser1.sort_index()

Germany    2
Japan      4
RF         3
USA        1
dtype: int64

- **``Sorting by Index``**: The ``**sort_index()``** method sorts the Series based on its **``index labels in ascending order``**.
- **``Result``**: The indices are rearranged so that they appear in **``alphabetical order``**, while the corresponding values remain aligned with their respective indices.

<hr>

**The following code ``sorts the values of the Pandas Series ser2 in ascending order``. This method rearranges the Series based on the values, while the corresponding indices remain aligned with their respective values.**

In [184]:
# Sort the Series by values

ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
Spain      6
dtype: int64

- **``Sorting by Values``**: The **``sort_values()``** method sorts the Series based on its **``values in ascending order``**.
- **``Result``**: The Series is rearranged so that the **``smallest values appear first``**, while the indices are still associated with their corresponding values.

<hr>



### Indexing in Pandas Series:

- **We're going to start with the ``basic form of selecting``, using the ``[...]`` operator.**

  - If we do NOT introduce labels into our Series, the index by default will be the natural numbers starting from 0. 
    - So the index will be the number of data introduced - 1.

In [185]:
# Let's remember our first Series

ser1

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

<hr>

**The following code ``retrieves the value at the index position 3`` in the Pandas Series ser1.**

In [186]:
# Attempt to access the "value" at "index position 3"

ser1[3]

4

- **``Indexing``**: In this case, ser1[3] refers to the fourth element of the Series (using zero-based indexing). Since the Series is ordered, the fourth entry corresponds to the index 'Japan'.
- **``Value``**: The value associated with the index 'Japan' is 4.

<hr>

**The following code ``retrieves the index label at position 3`` in the Pandas Series ser1.**
- In this case, it will give you the fourth index label, since indexing is zero-based.

In [187]:
# Access the "index label" at position 3

ser1.index[3]

'Japan'

- **``Indexing``**: The code **``ser1.index[3]``** accesses the **``fourth index label``** of the Series, which corresponds to the entry at position 3.
- **``Result``**: The index label at that position is 'Japan'.

<hr>

**The following code  ``retrieves the integer location (position) of the index label 'Japan'`` in the Pandas Series ser1.**
- This method is useful for finding the positional index of a specific label.

In [188]:
# pandas.index.get_loc
# index.get_loc(key, method=None, tolerance=None)[source]
# Get integer location, slice or boolean mask for requested label.

# Get the integer location of the index label 'Japan'
ser1.index.get_loc('Japan') 

3

- **``Using get_loc()``**: The method **``get_loc('Japan')``** returns the **``integer position of the index label 'Japan'``**, which is 3 in this case (since indexing is zero-based).
- **``Result``**: This indicates that **``'Japan'``** is the **``fourth element``** in the Series.

<hr>

**The following code allows us to access the ``value associated with the index label 'Japan'`` in the Pandas Series ser1.**

Here we can see how 'calling' a label works.

In [189]:
# Access the value associated with the index 'Japan'

ser1['Japan']

4

- **``Label-Based Indexing``**: The code **``ser1['Japan']``** uses **``label-based indexing``** to directly access the value corresponding to the **``index label 'Japan'``**.
- **``Result``**: The value associated with the index 'Japan' is **``4``**.

<hr>

**The following code is another way to ``access the value associated with the index label 'Japan'`` in the Pandas Series ser1.**
- This method utilizes the **``dot notation``** for accessing attributes, which is possible when the index labels are valid Python identifiers.

In [190]:
# Access the value associated with the index 'Japan' using dot notation

ser1.Japan

4

- **``Dot Notation``**: The code ser1.Japan accesses the value associated with the index label 'Japan' using dot notation, which is a shorthand for accessing attributes in a Pandas Series.
- **``Result``**: The value associated with the index 'Japan' is 4, just like when using ser1['Japan'].

<hr>

The difference between ser1['Japan'] and ser1.Japan lies primarily in how they access the data in the Pandas Series, and there are some conceptual differences worth noting.

- **``Differences:``**
  - **``Access Method``**:
    - **``ser1['Japan']``**: This uses label-based indexing, which is the standard way to access elements in a Pandas Series using the index label. It is explicit and works with any valid label.
    - **``ser1.Japan``**: This uses attribute access (dot notation). It is a shortcut for accessing values when the index label is a valid Python identifier (e.g., does not contain spaces or special characters).
  - **``Flexibility:``**
    - **``ser1['Japan']``**: Works with any index label, even if it contains spaces or characters that are invalid for attribute access.
    - **``ser1.Japan``**: Limited to index labels that are valid Python identifiers. If the index label were something like 'Japan 2020', this access method would fail.
  - **``Conceptual Names:``**
    - The first method (ser1['Japan']) is often referred to as "indexing" or "label-based indexing".
    - The second method (ser1.Japan) is referred to as "attribute access" or simply "dot notation".
  - **``SQL Syntax:``**
    - If you were to draw an analogy to SQL, you might think of ser1['Japan'] as similar to a SELECT statement with a WHERE clause (explicitly specifying which data to retrieve).
    - In contrast, ser1.Japan could be viewed as a shorthand for directly referencing a column (like using a column name in a SELECT statement without conditions), but it lacks the explicit specificity.
  - **``Preferred Method:``**
    - **``Preference:``**
      - **``The preferred method is ser1['Japan'] because:``**
        - It is more flexible and works with any index label.
        - It is explicit, making the code clearer and easier to read, especially for those unfamiliar with the structure of the Series.
        - It avoids potential errors that might occur when using dot notation with index labels that are not valid Python identifiers.

<hr>

**The following code ``returns the value associated with the index label 'Japan'`` in the Pandas Series ser1:**

In [191]:
# Print the value for 'Japan'

print("The value for 'Japan':", ser1['Japan'])

The value for 'Japan': 4


- **``Accessing the Value``**: The code **``ser1['Japan']``** retrieves the **``value``** associated with the **``index label 'Japan'``**, which is **``4``**.
- **``Printing``**: The print() function outputs a formatted string that includes the retrieved value.

<hr>

**The following code ``returns the value associated with the 3rd index position`` in the Pandas Series ser1. Since ``indexing is zero-based``, this refers to the ``fourth element`` in the Series.**

In [192]:
# Print the value for the 3rd index position

print("The value for the 3rd index:", ser1[3])

The value for the 3rd index: 4


- **``Accessing the Value``**: The code **``ser1[3]``** retrieves the **``value``** at the **``3rd index position``** (**``fourth element``**), which corresponds to the index label **``'Japan'``**.
- **``Printing``**: The print() function outputs a formatted string that includes the retrieved value.

<hr>



In [193]:
ser1

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

In [ ]:
# ser1[4]  # IndexError: index 4 is out of bounds for axis 0 with size 4

The IndexError occurs because we are trying to access an index that is out of bounds for the Series.

- **``Zero-Based Indexing:``**
  - In Python (and thus in Pandas), indexing is zero-based. This means that the first element of the Series is accessed with index 0, the second with index 1, and so on.
- **``Size of the Series:``**
  - In your case, ser1 has 4 elements. The valid indices for accessing elements in ser1 are 0, 1, 2, and 3.
  - Attempting to access ser1[4] refers to the fifth element, which does not exist since ser1 only contains 4 elements.
- **``Error Message:``**
  **``The error message IndexError``**: index 4 is out of bounds for axis 0 with size 4 indicates that you are trying to access an index that is beyond the available range (which is 0 to 3 for a size of 4).
- **``Valid Index Access:``**
  - To successfully access the elements in ser1, you can use:
    - ser1[0] for the first element (value 1).
    - ser1[1] for the second element (value 2).
    - ser1[2] for the third element (value 3).
    - ser1[3] for the fourth element (value 4).

<hr>


**The following code correctly ``handles the IndexError that occurs when trying to access an out-of-bounds index`` in the Pandas Series ser1.**

In [194]:
# Attempt to access the fourth element

try:
    print("The value of the fourth element in the Series:", ser1[4])
except IndexError as error:
    print("Nope, the index you selected is out of bounds. That's not how you select rows (index) in a Series.")

Nope, the index you selected is out of bounds. That's not how you select rows (index) in a Series.


- As seen above, with a Series, the call will return a single scalar value that matches the value at that label in the index. If you pass in a value for a label that doesn't exist, you will get a KeyError raised. Also, if you pass in an integer and your index has that value, it will return it. But if you don't have an integer value in your index, it will return the value by position. This is convenient, but can be confusing.
<hr>

- **``Try-Except Block:``**
  - The try block attempts to access the fourth element using ser1[4].
  - If this raises an IndexError (as it will, since ser1 only has indices 0 to 3), the control shifts to the except block.
- **``Handling the Error:``**
  - **``The except IndexError as error``**: line captures the error, allowing you to handle it gracefully by printing a custom message.
  - This prevents the program from crashing and provides informative feedback to the user.

<hr>




### Slicing in Pandas Series:


- **Let's see some slicing example with Series**

In [195]:
# Let's remember our second Series

ser2

USA        1
Germany    2
Italy      5
Japan      4
Spain      6
dtype: int64

<hr>

**The following code attempts to ``access the value at the first index position`` in the Pandas Series ser2.**
- However, since the Series uses custom index labels rather than integer indices, this will NOT yield the expected result based on integer indexing.

In [196]:
# Let's remember Basic Indexing

# Access the "value" at "index position 0"
ser2[0]

1

- **``Accessing the Value``**: The code ser2[0] retrieves the value at the first index position, which corresponds to the index label 'USA'.
- **``Result``**: The value associated with the index 'USA' is 1, because the Series is ordered based on the order of creation.

<hr>

**The following code will ``slice the Pandas Series ser2 from the third element to the end``.**
- This utilizes Python's standard slicing syntax, where indexing is zero-based.

In [198]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
Spain      6
dtype: int64

In [197]:
# Slice the Series from the third element to the end

ser2[2:]

Italy    5
Japan    4
Spain    6
dtype: int64

- **``Slicing``**: The expression **``ser2[2:]``** retrieves **``all elements starting from the index position 2 (the third element) to the end of the Series``**.
- **``Result``**: The resulting Series contains the entries with indices **``'Italy'``**, **``'Japan'``**, and **``'Spain'``**, along with their corresponding values.

<hr>

**The following code ``reverses the order of the elements`` in the Pandas Series ser2.**
- This utilizes Python's slicing syntax, where the notation **``[::-1]``** means to take the **``entire Series but with a step of -1, effectively reversing it``**.

In [199]:
# Reverse the Series

ser2[::-1]

Spain      6
Japan      4
Italy      5
Germany    2
USA        1
dtype: int64

- **``Reversing``**: The expression **``ser2[::-1]``** creates a new Series where the original order of elements is reversed.
- **``Result``**: The resulting Series retains the original values but **``changes the order of the indices from last to first``**.

<hr>



### Aritmetic Operations in the Series:

- **Another huge pro of using labelled indexes is that you can perform operations between two different series and Pandas know what labels have both series in common and does the operations automatically.**

Operations are then also done based on index:

**The following code ``performs element-wise addition`` of the two Pandas Series, ser1 and ser2.**
- The addition is done based on their index labels. 
  - If an index exists in both Series, their corresponding values are added together. If an index exists in only one of the Series, the result will have NaN (Not a Number) for that index.

In [202]:
ser1, ser2

(USA        1
 Germany    2
 RF         3
 Japan      4
 dtype: int64,
 USA        1
 Germany    2
 Italy      5
 Japan      4
 Spain      6
 dtype: int64)

In [201]:
# Perform the addition

ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
RF         NaN
Spain      NaN
USA        2.0
dtype: float64

Using **``ser1 + ser2``** allows you to perform **``element-wise addition based on index labels``**, resulting in a new Series that includes combined values where applicable and **``NaN``** for **``unmatched indices``**.


- **``Element-wise Addition:``**
  - **``For the index 'USA'``**: ser1['USA'] (1) + ser2['USA'] (1) = **``2``**
  - **``For the index 'Germany'``**: ser1['Germany'] (2) + ser2['Germany'] (2) = **``4``**
  - **``For the index 'Japan'``**: ser1['Japan'] (4) + ser2['Japan'] (4) = **``8``**

For the indices **``'Italy'``**, **``'RF'``**, and **``'Spain'``**, the corresponding values in one of the Series are **``NaN``**, leading to NaN in the result.

<hr>

**The following code ``performs element-wise multiplication`` of the two Pandas Series, ser1 and ser2.**
- Similar to addition, multiplication is done based on their index labels.  
  - If an index exists in both Series, the corresponding values are multiplied together. 
  - If an index exists in only one of the Series, the result will include NaN (Not a Number) for that index.



In [203]:
# Perform the multiplication

ser1 * ser2

Germany     4.0
Italy       NaN
Japan      16.0
RF          NaN
Spain       NaN
USA         1.0
dtype: float64

Using **``ser1 * ser2``** allows you to perform **``element-wise multiplication based on index labels``**, resulting in a new Series that includes combined values where applicable and **``NaN``** for **``unmatched indices``**.


- **``Element-wise Multiplication:``**
- **``For the index 'USA'``**: ser1['USA'] (1) * ser2['USA'] (1) = **``1``**
- **``For the index 'Germany'``**: ser1['Germany'] (2) * ser2['Germany'] (2) = **``4``**
- **``For the index 'Japan'``**: ser1['Japan'] (4) * ser2['Japan'] (4) = **``16``**

For the indices **``'Italy'``**, **``'RF'``**, and **``'Spain'``**, the corresponding values in one of the Series are **``NaN``**, leading to NaN in the result.

<hr>



**Let's make changes on indexes:**

In [205]:
# Create the Series
ser = pd.Series(data=[121, 200, 150, 99], index=["terry", "micheal", "orion", "jason"])

# Display the Series
ser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

- **``Data``**: The **``values``** in the Series are **``[121, 200, 150, 99]``**.
- **``Index``**: The corresponding **``indices``** are **``["terry", "micheal", "orion", "jason"]``**.
- **``Data Type``**: The Series has a data type of int64, indicating that the values are integers.

<hr>

**The following code  will ``return the index labels`` of the Pandas Series ser.**
- This allows you to see the labels associated with each entry in the Series.

In [206]:
# Access the index of the Series

ser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

- **``Index Object``**: The output is an **``Index object``** that contains the **``labels``** **``['terry', 'micheal', 'orion', 'jason']``**.
- **``Data Type``**: The **``dtype``** is **``object``**, indicating that the index **``labels are strings``**.

<hr>

**The following code allows us to ``access the value associated with the index label 'terry'`` in the Pandas Series ser.**

In [207]:
# Access the value associated with the index 'terry'

ser['terry']

121

- **``Label-Based Indexing``**: The code **``ser['terry']``** retrieves the **``value``** corresponding to the index label **``'terry'``**, which is **``121``**.
- **``Result``**: This shows the **``value``** associated with the **``specified index label``**.

<hr>

**The following code ``accesses the value at the first positional index`` in the Pandas Series ser.**
- Since indexing in Python is zero-based, **``ser[0]``** retrieves the **``first element``** of the Series.

In [208]:
# Access the value at the first positional index

ser[0]

121

- **``Positional Indexing``**: The code **``ser[0]``** retrieves the **``value``** at the **``first index position``**, which corresponds to the index label **``'terry'``**.
Result``**: The **``value``** associated with the **``first element``** is **``121``**.

<hr>

**The following code allows you to ``access multiple elements`` from the Pandas Series ser at ``specified positional indices``.**
- In this case, it retrieves the **``values``** at index positions **``0``** and **``2``**.

In [ ]:
# Access the values at index positions 0 and 2

ser[[0, 2]]

using **``ser[[0, 2]]``** is an example of **``fancy indexing``** (or boolean indexing) in Pandas. Fancy indexing allows you to access **``multiple elements``** of a Series or DataFrame by using an array or list of indices.

- **``Key Points About Fancy Indexing:``**
  - **``Multiple Indices``**: Fancy indexing enables you to retrieve multiple elements at once based on their positional indices or labels, as demonstrated in your example.
  - **``Array-Like Input``**: You can use a list or a NumPy array of indices to specify which elements you want to access. This contrasts with standard indexing, where you would typically access a single element at a time.
  - **``Return Type``**: The result of fancy indexing is still a Series (if applied to a Series) or a DataFrame (if applied to a DataFrame), preserving the original structure while allowing for selective access.

- **``Positional Indexing``**: The code **``ser[[0, 2]]``** retrieves the values at the specified positions:
  - **``Index 0``**: corresponds to **``'terry'``** (value **``121``**).
  - **``Index 2``**: corresponds to **``'orion'``** (value **``150``**).
- **``Result``**: The result is a new Series containing the values associated with the specified positions, along with their respective index labels.

<hr>

**The following code allows us to ``access multiple elements`` from the Pandas Series ser using their index labels.**
- This is another example of **``fancy indexing``**, but this time it utilizes label-based indexing rather than positional indexing.

In [213]:
# Access the values associated with the index labels 'terry' and 'orion'

ser[["terry", "orion"]]

terry    121
orion    150
dtype: int64

- **``Label-Based Indexing``**: The code **``ser[["terry", "orion"]]``** retrieves the values associated with the specified labels.
- **``Result``**: The result is a new Series containing the values for the specified index labels along with their respective labels.

<hr>

**The following code ``slices the Pandas Series ser to retrieve a subset of elements from the first index position up to, but not including, the third index position``.**
- This utilizes Python's standard slicing syntax.

In [214]:
ser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [215]:
# Slice the Series from index position 0 to 3

ser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

- **``Slicing``**: The expression **``ser[0:3]``** retrieves the elements at index positions **``0``**, **``1``**, and **``2``**. The slicing is inclusive of the **``starting index (0)``** and **``exclusive of the stopping index (3)``**.
- **``Result``**: The resulting Series includes the values for the index labels 'terry', 'micheal', and 'orion'.

<hr>

**The following code ``slices the Pandas Series ser using label-based indexing``.**
- This retrieves all elements from the index label **``'terry'``** to the index label **``'orion'``**, ``**inclusive``**.

In [216]:
# Slice the Series from 'terry' to 'orion'

ser['terry':'orion']

terry      121
micheal    200
orion      150
dtype: int64

- **``Label-Based Slicing``**: The expression **``ser['terry':'orion']``** retrieves the **``elements starting from the index label 'terry'``** to the **``index label 'orion'``**, **``inclusive``** of both endpoints.
- **``Result``**: The resulting Series includes the values for the index labels **``'terry'``**, **``'micheal'``**, and **``'orion'``**.

<hr>



## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Selection with Condition and Broadcasting</p>

<a id="5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [217]:
# Let's remember our Series

ser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

- **``Index Labels``**: The Series has index labels: **``'terry'``**, **``'micheal'``**, **``'orion'``**, and **``'jason'``**.
- **``Values``**: The corresponding values are **``121``**, **``200``**, **``150``**, and **``99``**.
- **``Data Type``**: The data type of the Series is int64, indicating that the values are integers.

<hr>

### Conditional Selection:


**The following expression ``checks whether the index label 'terry' exists in the Pandas Series ser``.**
- This expression returns a boolean value: 
   - True if the label is present and
   - False if it is NOT.

In [218]:
# Check if 'terry' is an index label in the Series

'terry' in ser

True

- **``Membership Check``**: The expression **``'terry' in ser``** effectively checks the Series' index for the presence of the label **``'terry'``**.
- **``Result``**: Since **``'terry'``** is indeed one of the index labels in the Series, the result is **``True``**.

<hr>

**The following expression ``checks whether the index label 'bob' exists in the Pandas Series ser``.**
- This expression returns a boolean value: 
   - **``True``** if the label is **``present``** and
   - **``False``** if it is **``NOT``**.

In [219]:
# Check if 'bob' is an index label in the Series

'bob' in ser

False

- **``Membership Check``**: The expression **``'bob' in ser``** effectively checks the Series' index for the presence of the label **``'bob'``**.
- **``Result``**: Since **``'bob'``** is NOT one of the index labels in the Series, the result is **``False``**.

<hr>

**The following expression ``checks whether the value 121 exists within the values of the Pandas Series ser``.**
- This expression returns a boolean value: 
   - **``True``** if the label is **``present``** and
   - **``False``** if it is **``NOT``**.

In [220]:
ser.values

array([121, 200, 150,  99], dtype=int64)

In [221]:
# Check if 121 is in the values of the Series

121 in ser.values

True

- **``Membership Check``**: The expression **``121 in ser.values``** checks the underlying array of values in the Series to see if **``121``** is one of them.
- **``Result``**: Since **``121``** is indeed one of the values in the Series, the result is **``True``**.

<hr>

**The following expression ``checks whether the value 55 exists within the values of the Pandas Series ser``.**
- This expression returns a boolean value: 
   - **``True``** if the label is **``present``** and
   - **``False``** if it is **``NOT``**.

In [222]:
# Check if 55 is in the values of the Series

55 in ser.values

False

- **``Membership Check``**: The expression **``55 in ser.values``** checks the underlying array of values in the Series to see if **``55``** is one of them.
- **``Result``**: Since **``55``** is NOT one of the values in the Series, the result is **``False``**.

<hr>

**The following expression applies a ``comparison operation to each element in the Pandas Series ser``.**
- This will return a new Series of boolean values, indicating **``whether each corresponding value in the Series is less than 100``**.

In [224]:
ser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [223]:
# Perform the comparison

ser < 100

terry      False
micheal    False
orion      False
jason       True
dtype: bool

- **``Element-wise Comparison``**: The expression ser < 100 checks each value in the Series:
  - **``For 'terry'``**: ``121 < 100`` → **``False``**
  - **``For 'micheal'``**: ``200 < 100`` → **``False``**
  - **``For 'orion'``**: ``150 < 100`` → **``False``**
  - **``For 'jason'``**: ``99 < 100`` → **``True``**
- **``Result``**: The resulting Series contains boolean values indicating **``whether each original value is less than 100``**.

<hr>

### Broadcasting:

**The following expression ``updates the values in the Pandas Series ser where the condition (values less than 100) is true. Specifically, it sets those values to 100``.**

In [225]:
# Update values that are less than 100
ser[ser < 100] = 100

# Display the Series
ser

terry      121
micheal    200
orion      150
jason      100
dtype: int64

- **``Condition``**: The condition **``ser < 100``** checks **``each value in the Series``** and returns a boolean Series indicating which values are less than 100.
- **``Updating Values``**: The values that satisfy this condition (in this case, the **``value 99``** for index **``'jason'``**) are **``set to 100``**.
- **``Result``**: The resulting Series shows that the original value of **``99 has been replaced with 100``**, while all other values remain unchanged.

<hr>

**The following expression ``checks whether each value in the Pandas Series ser is contained within the specified list (in this case, the list containing just the value 121)``.**
- This operation returns a boolean Series indicating;
  - **``True``** for values that are **``present``** in the list and
  - **``False``** for those that are **``NOT``**.

In [226]:
# Check if values are in the list [121]

ser.isin([121])

terry       True
micheal    False
orion      False
jason      False
dtype: bool

- **``Membership Check``**: The **``isin([121])``** method checks **``each value in the Series to see if it matches 121``**.
- **``Result``**: The resulting Series indicates that only the value associated with the index label **``'terry'``** is **``121``**, hence it returns;
  - **``True``** for matching index **``'terry'``** and
  - **``False``** for all others.

<hr>

**The following expression ``updates the values in the Pandas Series ser where the condition (values equal to 121) is true, setting those values to 125``.**

In [227]:
# Update values that are equal to 121

ser[ser.isin([121])] = 125


ser

terry      125
micheal    200
orion      150
jason      100
dtype: int64

- **``Condition``**: The method **``ser.isin([121])``** checks **``each value in the Series and returns a boolean Series``**, indicating which values are equal to **``121``**.
- **``Updating Values``**: The values that satisfy this condition (in this case, the **``value 121``** for index **``'terry'``**) are set to **``125``**.
- **``Result``**: The resulting Series shows that the original value of 121 has been **``replaced with 125``**, while all other values remain unchanged.

<hr>



## <p style="background-color:#E51A59; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Recap for Several Selecting Attributes</p>

<a id="6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [228]:
# Retrieve the keys (index labels) of the Series

ser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

 - **``Index Object``**: The **``keys()``** method returns an **``Index object``** that contains the **``labels``** **``['terry', 'micheal', 'orion', 'jason']``**.
- **``Data Type``**: The **``dtype``** is **``object``**, indicating that the **``index labels``** are **``strings``**.

<hr>



In [229]:
# Retrieve the index of the Series

ser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

- **``Index Object``**: The **``index``** attribute returns an **``Index object``** that contains the **``labels``** **``['terry', 'micheal', 'orion', 'jason']``**.
- **``Data Type``**: The **``dtype``** is **``object``**, indicating that the **``index labels``** are **``strings``**.


<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>✍️👉 Both ser.keys() and ser.index return the same result when called on a Pandas Series. They both provide the index labels associated with the Series.</strong></p>



<hr>



In [230]:
# Retrieve the values of the Series

ser.values

array([125, 200, 150, 100], dtype=int64)

- **``NumPy Array``**: The values attribute returns the **``values``** as a NumPy array, which can be useful for numerical operations and compatibility with other libraries that utilize NumPy arrays.
- **``Data Type``**: The array will typically have a data type that matches the data type of the Series (in this case, int64).

<hr>



In [231]:
# Retrieve the values of the Series

ser.items

<bound method Series.items of terry      125
micheal    200
orion      150
jason      100
dtype: int64>

#### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢❗🚨 Be Careful; items is NOT attribute, but method ❗❗❗</strong></p>


<hr>



In [232]:
# Retrieve the items in the Series

ser.items()

- **``Zip Object``**: The zip object combines the index labels and values, but we need to iterate through it or convert it to a list to view its contents.

<hr>

A **``zip object``** is an iterator in Python that aggregates elements from two or more iterables (like lists or tuples) into tuples. The **``zip()``** function pairs elements from the input iterables based on their positions, creating a new iterable of tuples.

- **``Characteristics of Zip Objects:``**
  - **``Lazy Evaluation``**: Zip objects are lazily evaluated, meaning they generate their **``values``** **``on-the-fly``** and do **``NOT store them in memory``**. This makes them **``memory efficient``**, especially when dealing with large datasets.
  - **``Tuple Pairing``**: Each tuple in a zip object contains elements from each of the input iterables, taken from the same index. The iteration stops when the shortest input iterable is exhausted.
  - **``Conversion``**: Since zip objects are iterators, you often **``need to convert``** them to **``a list``** or **``another iterable type``** to view or manipulate the results.
  
  <hr>

In [233]:
# Convert the zip object to a list to display

list(ser.items())

[('terry', 125), ('micheal', 200), ('orion', 150), ('jason', 100)]

- **``Iteration``**: By converting the zip object to a list, we can **``easily display/access or process the index-value pairs``**.
  - The output yields a tuple where the **``first element``** is the **``index label``** and the **``second``** is the **``value``** associated with that label.

<hr>



In [234]:
# Iterate over the items in the Series

print("Items in the Series:")
print("*"*25)

for index, value in ser.items():
    print(f"Index: {index:<7} | Value: {value:>3}")

Items in the Series:
*************************
Index: terry   | Value: 125
Index: micheal | Value: 200
Index: orion   | Value: 150
Index: jason   | Value: 100


- **``Iteration``**: The **``items()``** method provides an efficient way to access both the index labels and their corresponding values in a Series.
- **``Tuples``**: Each iteration yields a tuple where the **``first element``** is the **``index label``** and the **``second``** is the **``value``** associated with that label.

<hr>



In [235]:
# Let's remember our Series

ser

terry      125
micheal    200
orion      150
jason      100
dtype: int64



<hr>



In [236]:
# Sort the Series by "index" in "descending order"

ser.sort_index(ascending=False)

terry      125
orion      150
micheal    200
jason      100
dtype: int64

- **``Sorting``**: The method **``sort_index(ascending=False)``** sorts the Series based on the **``index labels``** **``from Z to A (in descending order)``**.
- **``Result``**: The resulting Series maintains the original values but rearranges them according to the sorted index.

<hr>



In [237]:
# Sort the Series by "values" in "descending order"

ser.sort_values(ascending=False)

micheal    200
orion      150
terry      125
jason      100
dtype: int64

- **``Sorting``**: The method **``sort_values(ascending=False)``** sorts the Series based on the **``values``** from **``highest to lowest (in descending order)``**.
- **``Result``**: The resulting Series maintains the original index labels, but the values are rearranged according to the sorted order.

<hr>



<a id="7"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#E51A59; font-size:150%; text-align:center; border-radius:10px 10px;">End of the Session - 03</p>

<!-- <p style="text-align: center;"><img src="https://i.ibb.co/RhJpNnJ/lunch-time.jpg" width="450" height="200" class="img-fluid" alt="Lunch Time"></p>
 -->
<p style="text-align: center;"><img src="https://i.ibb.co/TtRtYNn/healthy-lunch.jpg" width="800" height="200" class="img-fluid" alt="Lunch Time"></p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>


<br><br><br>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="450" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>